bits

diff --git a/helpers/mountfile b/helpers/mountfile
--- a/helpers/mountfile
+++ b/helpers/mountfile
@@ -49,6 +49,27 @@ unmap_disk0() {
   kpartx -d -p- $1
 }
 
+cleanup() {
+  if [ ${#CLEANUP[*]} -gt 0 ]; then
+    LAST_ELEMENT=$((${#CLEANUP[*]}-1))
+    REVERSE_INDEXES=$(seq ${LAST_ELEMENT} -1 0)
+    errflag=false
+    for i in $REVERSE_INDEXES; do
+      if $errflag ; then
+        log_error "Cleanup operation not executed: ${CLEANUP[$i]}"
+      else
+        ${CLEANUP[$i]}
+        if [ $? -ne 0 ]; then
+          log_error "Cleanup operation failed: ${CLEANUP[$i]}"
+          errflag=true
+        fi
+      fi
+    done
+  fi
+}
+
+trap cleanup EXIT
+
 if [ ! -b "$disk" ]; then
   blockdev=$($LOSETUP -f --show "$disk")
   CLEANUP+=("$LOSETUP -d $blockdev")
@@ -69,7 +90,6 @@ CLEANUP+=("sync")
 read -p "Now cd to $TARGET in another terminal. When finished, press Enter here to unmount the disk -> " theenter
 
 cleanup
-trap - EXIT
 
 exit 0
 
