bits

diff --git a/helpers/mountfile b/helpers/mountfile
--- a/helpers/mountfile
+++ b/helpers/mountfile
@@ -19,32 +19,35 @@ rcommand=${0##*/}
 rpath=${0%/*}
 #*/
 
-[ -z "$M_ROOT" ] && M_ROOT=$(readlink -f "$rpath/../../")
-source "$M_ROOT/conf/mon.conf" || exit 99
-source "$M_ROOT/conf/clouds/${CLOUD}.conf" || exit 99
-source "$M_ROOT/cloud/$CLOUD_PROVIDER/functions.sh" || exit 99
-
 LOSETUP=`which losetup 2>/dev/null`
-GI=`which gnt-instance 2>/dev/null`
 
 [ -z "$LOSETUP" ] && echo "no losetup found" && exit 1
-[ -z "$GI" ] && echo "no gnt-instance found" && exit 1
+disk="$1"
 
-vm="$1"
-vmini=`$GI list --no-header --separator='|' -o oper_state,disk_template,disk.size/0 "$vm"`
-[ "X`echo "$vmini" | cut -d'|' -f1`" != "XN" ] && echo "VM must exist and be stopped" && exit 1
+map_disk0() {
+  [ -z "$1" ] && log_error "argument to map_disk0 is empty" && return 1
+  blockdev="$1"
+  filesystem_dev_base=`kpartx -l -p- $blockdev | grep -m 1 -- "-1.*$blockdev" | awk '{print $1}'`
+  if [ -z "$filesystem_dev_base" ]; then
+    log_error "Cannot interpret kpartx output and get partition mapping using command:"
+    log_error "kpartx -l -p- $blockdev | grep -m 1 -- \"-1.*$blockdev\" | awk '{print $1}'"
+    exit 1
+  fi
+  kpartx -a -p- $blockdev > /dev/null
+  filesystem_dev="/dev/mapper/$filesystem_dev_base"
+  if [ ! -b "$filesystem_dev" ]; then
+    `which dmsetup` mknodes
+  fi
+  if [ ! -b "$filesystem_dev" ]; then
+    log_error "Can't find kpartx mapped partition: $filesystem_dev"
+    exit 1
+  fi
+  echo "$filesystem_dev"
+}
 
-disktype="`echo "$vmini" | cut -d'|' -f2`"
-disksize="`echo "$vmini" | cut -d'|' -f3`"
-
-[ `expr "$disksize" : ".*[^[0-9]]*.*"` -ne 0 ] && echo "No disk found" && exit 1
-
-# now when we know that disk does exist, we can use a heavier tool to find its
-# file or device
-
-disk=`"$M_ROOT/cloud/$CLOUD_PROVIDER"/get_server_details --name="$vm" | grep '/"Disks"/"disk/0"/"on primary"|' | cut -d'|' -f2 | tail -1 | tr -d '"'`
-[ -z "$disk" ] && echo "unable to get disk details" && exit 1
-disk=`expr "$disk" : "\(.*\) ("`
+unmap_disk0() {
+  kpartx -d -p- $1
+}
 
 if [ ! -b "$disk" ]; then
   blockdev=$($LOSETUP -f --show "$disk")
@@ -69,5 +72,4 @@ cleanup
 trap - EXIT
 
 exit 0
-
 
