some enhancements

diff --git a/helpers/mssh b/helpers/mssh
--- a/helpers/mssh
+++ b/helpers/mssh
@@ -21,6 +21,15 @@ rpath=${BASH_SOURCE%/*}
 [ -z "$M_ROOT" ] && M_ROOT=$(readlink -f "$rpath/../") && export M_ROOT
 #*/
 
+name_to_ip() {
+  IP=`cat "$M_ROOT/nodes.list" 2>/dev/null | cut -d'|' -f1,4 | grep "|${1}$" | cut -d'|' -f1 | tail -1`
+  if [ -z "$IP" ]; then
+    IP=`grep -E "\ $name\ |\ $name$" /etc/hosts | tail -1`
+    IP=`expr "$IP" : ".*\([0-9.]\)[[:space:]]"`
+  fi
+  echo "$IP"
+}
+
 SSH=`which ssh 2>/dev/null`
 [ -z "$SSH" ] && echo "command ssh not found" && exit 1
 [ -n "$CLOUD" ] && source "$M_ROOT/conf/clouds/${CLOUD}.conf"
@@ -43,6 +52,8 @@ if [ -z "$host" ]; then
     host=`get_ips --cluster=$M_CLUSTER --names | sort -n | head -1`
     [ -z "$host" ] && echo "Host not found for cluster $M_CLUSTER" && exit 1
     KEY=`cat "$M_ROOT/nodes.list" | cut -d'|' -f2,4 | grep \|${host}$ | cut -d'|' -f1`
+    hostip=`name_to_ip $host`
+    [ -z "$hostip" ] && echo "Host cannot be either found or resolved" && exit 1
   else
     echo "No default cluster and host not defined"
     exit 1
@@ -58,6 +69,8 @@ if [ -n "$clline" ]; then
   host=`get_ips --cloud=$cloud --cluster=$cluster --names | sort -n | head -1`
   [ -z "$host" ] && echo "Host not found for cluster $M_CLUSTER" && exit 1
   KEY=`cat "$M_ROOT/nodes.list" | cut -d'|' -f2,4 | grep \|${host}$ | cut -d'|' -f1`
+  hostip=`name_to_ip $host`
+  [ -z "$hostip" ] && echo "Host cannot be either found or resolved for cluster $cluster" && exit 1
 else
   # if target is IP
   KEY=`grep ^${host}\| "$M_ROOT/nodes.list" | cut -d'|' -f2`
@@ -108,6 +121,9 @@ if [ ! -f "$M_ROOT/keys/$KEY" ]; then
 fi
 
 KEY="$M_ROOT/keys/$KEY"
+
+# IP is better, we don't have to rely on resolving
+[ -n "$hostip" ] && host=$hostip
 
 if [ -n "$KEY" ] ; then
   if [ -f "$KEY" ]; then
