rackspace auth response format changed

diff --git a/helpers/wrapper b/helpers/wrapper
--- a/helpers/wrapper
+++ b/helpers/wrapper
@@ -37,7 +37,7 @@ command_options=""
 necessary_options="command"
 [ $# -eq 0 ] && ${0} --help && exit 0
 IFS1=$IFS
-IFS='--'
+IFS='-'
 for s_option in "${@}"
 do
   found=0
@@ -58,7 +58,7 @@ do
   esac
   possible_options="$command_options $wrapper_options"
   
-  for option in `echo $possible_options | sed 's/ /--/g'`; do 
+  for option in `echo $possible_options | sed 's/ /-/g'`; do 
     [ -n "$s_optname" ] && [ "X$s_optname" == "X$option" ] && eval "$option=\"${s_optarg}\"" && found=1
   done
   [ "X$s_option" == "X$s_param" ] && found=1
@@ -77,6 +77,8 @@ if [ "X$help" == "Xyes" ] ; then
   exit 0
 fi
 
+
+
 trap 'exit' 0
 trap 'exit' 3
 trap 'exit' 15
@@ -89,6 +91,14 @@ fi
 [ -n "$logfile" ] || logfile="/var/log/${rcommand##*/}.log"
 [ -n "$errlogfile" ] || errlogfile=$logfile
 [ -n "$pidfile" ] || pidfile="/var/run/${rcommand##*/}.pid"
+
+for option in $necessary_options ; do
+  [ -z "$(eval echo \$$option)" ] && missing_options="$missing_options --${option}," && found=true
+done
+if $found ; then
+  echo "Necessary options: ${missing_options/%,/} not found"
+  exit 1
+fi
 
 [ -n "$chdir" ] && cdback=$PWD
 
@@ -112,18 +122,24 @@ case $s_param in
     if [ -n "$user" -a "$UID" == "0" ] ; then
       su $user -c "exec -a $rcommand $command $(for po in $command_options ; do printf " --${po}=`eval "echo \\$\${po}"`" ; done) 1>>\"$logfile\" 2>>\"$errlogfile\" </dev/null" &
       succ=$?
-      echo $! > "$pidfile"
+      pid=$!
+      echo $pid > "$pidfile"
     elif [ -n "$group" -a "$UID" == "0" ] ; then
       sg $group -c "exec -a $rcommand $command $(for po in $command_options ; do printf " --${po}=`eval "echo \\$\${po}"`" ; done) 1>>\"$logfile\" 2>>\"$errlogfile\" </dev/null" &
       succ=$?
-      echo $! > $pidfile
+      pid=$!
+      echo $pid > "$pidfile"
     else
       exec -a $rcommand $command $(for po in $command_options ; do printf " --${po}=`eval "echo \\$\${po}"`" ; done) >>"$logfile" 2>&1 </dev/null &
       succ=$?
-      echo $! > "$pidfile"
+      pid=$!
+      echo $pid > "$pidfile"
     fi
 
-    [[ $succ -eq 0 ]] && [ -n "`cat "$pidfile"|grep -v ^$|tail -1`" ] && echo "done (PID `cat "$pidfile"|grep -v ^$|tail -1`)" || echo "error" | tee -a "$logfile"
+    if [[ $succ -eq 0 ]] && [ -n "$pid" ]; then
+      [ -d /proc/$pid ] && echo "done (PID `cat "$pidfile"|grep -v ^$|tail -1`)" || echo "error" | tee -a "$logfile"
+    fi
+
     [ -n "$cdback" ] && cd "$cdback"
     ;;
   stop)
