bits & graph ARG parser changed

diff --git a/graph b/graph
--- a/graph
+++ b/graph
@@ -59,37 +59,40 @@ fi
 RSYNC=`which rsync 2>/dev/null`
 SQL3=`which sqlite3 2>/dev/null` # assuming that remote path is the same
 
+IFS1=$IFS
+IFS='-'
 for s_option in "$@"
 do
-  found=0
-  case $s_option in
-  --*=*)
-    s_optname=`expr "X$s_option" : 'X[^-]*-*\([^=]*\)'`  
-    s_optarg=`expr "X$s_option" : 'X[^=]*=\(.*\)'` 
-    ;;
-  --*)
-    s_optname=`expr "X$s_option" : 'X[^-]*-*\([^=]*\)'`    
-    s_optarg='yes' 
-    ;;
-  *=*)
-    log "Wrong syntax: options must start with a double dash"
-    exit 1
-    ;;
-  *)
-    s_param=$s_option
-    s_optname=''
-    s_optarg=''
-    ;;
-  esac
-  for option in `echo $possible_options | sed 's/,//g'`; do 
-    [ "X$s_optname" == "X$option" ] && eval "$option=$s_optarg" && found=1
+  found=false
+  s_option=${s_option/--/}
+  s_optname=${s_option%%=*}
+  s_optarg=${s_option##*=}
+  [ "X$s_optarg" == "X$s_optname" ] && s_optarg="yes"
+
+  for option in ${possible_options// /-} ; do
+    [ "X$s_optname" == "X$option" ] && eval "$s_optname=\"$s_optarg\"" && found=true && break
   done
-  [ "X$s_option" == "X$s_param" ] && found=1
-  if [[ $found -ne 1 ]]; then 
-    log "Unknown option: $s_optname"
+  
+  if ! $found ; then 
+    echo "Unknown option: $s_optname"
     exit 1
   fi
 done
+IFS=$IFS1
+
+found=false
+for option in $necessary_options ; do
+  [ -z "$(eval echo \$$option)" ] && missing_options="${missing_options} --${option}," && found=true
+done
+if $found ; then
+  echo "Necessary options: ${missing_options/%,/} not found"
+  exit 1
+fi
+
+for option in $possible_options ; do
+  eval "echo ${option}=\$${option}"
+done
+
 # "metric help from to ip new database table size width height scale padding legend fontsize strokewidth pointsize"
 if [ "X$help" == "Xyes" ] ; then
 cat << "EOF"
