bits

diff --git a/graph b/graph
--- a/graph
+++ b/graph
@@ -193,7 +193,8 @@ if [ -z "$localip" ] ; then
   sIP=`echo $server | cut -d'|' -f1`
   skey=`echo $server | cut -d'|' -f2`
   scluster=`echo $server | cut -d'|' -f5`
-  rpath=`cat ${rpath}/conf/clusters.conf|grep "^${scluster}|"|tail -1|cut -d'|' -f8`
+  mpath=`cat ${rpath}/conf/clusters.conf|grep "^${scluster}|"|tail -1|cut -d'|' -f8`
+  [ -z "$mpath" ] && echo "M-Script path for server $server not found" >> "${rpath}/dashboard.log" && exit 1
   if [ -n "$skey" ] && [ -f "${rpath}/keys/${skey}.pem" ] ; then
     thekey="-i ${rpath}/keys/${skey}.pem"
   fi
@@ -252,32 +253,36 @@ for smetric in `echo $metric | tr ',' ' '` ; do
     if [ "X$sIP" == "Xlocalhost" ] ; then
       sqlite3 "${rpath}/${database}" "${QUERY}" > ${TMPDIR}/graph.${sIP}.${dbname}.${smetric}
     else
-      $SSH $thekey -o StrictHostKeyChecking=no $sIP "sqlite3 \"${rpath}/${database}\" \"${QUERY}\"" > ${TMPDIR}/graph.${sIP}.${dbname}.${smetric}
+    # -o StrictHostKeyChecking=no 
+      $SSH $thekey $sIP "sqlite3 \"${mpath}/${database}\" \"${QUERY}\"" > ${TMPDIR}/graph.${sIP}.${dbname}.${smetric} || echo "Problem getting ${smetric} data from $sIP" >> "${rpath}/dashboard.log"
     fi
-    if [ `cat ${TMPDIR}/graph.${sIP}.${dbname}.${smetric} | wc -l` -le 5 ] ; then
+    if [ `cat ${TMPDIR}/graph.${sIP}.${dbname}.${smetric} | wc -l` -le 1 ] ; then
       echo "Too little data for graph. Might be connection to ${sIP} problems. Graph is not generated." >> "${rpath}/dashboard.log"
       exit 1
     fi
   fi
   
   smax=`cat ${TMPDIR}/graph.${sIP}.${dbname}.${smetric} | cut -d'|' -f2 | sort -n | tail -1` ; smax=${smax%.*}
-  smin=`cat ${TMPDIR}/graph.${sIP}.${dbname}.${smetric} | cut -d'|' -f2 | sort -n | head -1` ; smin=${smin%.*}
+  smin=`cat ${TMPDIR}/graph.${sIP}.${dbname}.${smetric} | cut -d'|' -f2 | grep -v ^$ | sort -n | head -1` ; smin=${smin%.*}
   [[ $metricmax -eq 0 ]] && metricmin=$smax
+  [ -z "$metricmin" ] && metricmin=0
   [[ $smax -gt $metricmax ]] && metricmax=$smax
   [[ $smin -lt $metricmin ]] && metricmin=$smin
 done
 
 if [ "X$scale" == "Xyes" ] ; then
   sn=`echo $metric | tr ',' ' ' | wc -w`
-  sadd=`solve "($metricmax - $metricmin) / $sn"`
+  sadd=`solve "($metricmax - $metricmin) / $sn"` 2>/dev/null || sadd=`solve "$metricmax / $sn"` 2>/dev/null || sadd=10
   snadd=0
   for smetric in `echo $metric | tr ',' ' '` ; do
     rm -f ${TMPDIR}/graph.${sIP}.${dbname}.${smetric}.scaled 2>/dev/null
     smax=`cat ${TMPDIR}/graph.${sIP}.${dbname}.${smetric} | cut -d'|' -f2 | sort -n | tail -1`
-    sratio=`solve "$metricmax / $smax / $sn / 1.1"`
+    [ `echo "$smax == 0" | bc` -ne 1 ] && sratio=`solve "$metricmax / $smax / $sn / 1.2"` || sratio=1
     for LINE in `cat ${TMPDIR}/graph.${sIP}.${dbname}.${smetric}` ; do
       st=`echo $LINE | cut -d'|' -f1`
+      [ -z "$st" ] && continue
       sd=`echo $LINE | cut -d'|' -f2`
+      [ -z "$sd" ] && continue
       sds=`solve "$sd * $sratio + $snadd"`
       echo "${st}|${sds}" >> ${TMPDIR}/graph.${sIP}.${dbname}.${smetric}.scaled
     done
@@ -438,11 +443,8 @@ unset nexthour theday themonth theyear themark currpoint hourX
 a=`expr $perdotY \* $countminY`
 b=`expr 2 \* $a`
 s=`expr length $b`
-echo "in 40 pixels: $b"
-echo "length: $s"
 pof=1
 for ((i=0; i<$s; i++)); do pof="${pof}0"; done
-echo "power of: $pof"
 res=`expr $pof / 10`
 if [[ $res -lt $a ]] ; then
   res=`expr $pof / 4`
@@ -468,11 +470,13 @@ do
   [[ `expr $i + $ires` -gt $imax ]] && unset imark imarkfp
   irev=`expr ${graphV} - $i`
   marksY="$marksY`echo "<line x1=\\"$mY1\\" y1=\\"$irev\\" x2=\\"$mY2\\" y2=\\"$irev\\" />"`"
-  if [ -n "$mp" ] ; then
-    [ -n "$imark" ] && imarkfp=`solve "$imark/$mp"`
-    textY="${textY}`echo "<text x=\\"$mYT1\\" y=\\"$irev\\" >$imarkfp</text>"`"
-  else
-    textY="${textY}`echo "<text x=\\"$mYT1\\" y=\\"$irev\\" >$imark</text>"`"
+  if [ "X$scale" != "Xyes" ] ; then
+    if [ -n "$mp" ] ; then
+      [ -n "$imark" ] && imarkfp=`solve "$imark/$mp"`
+      textY="${textY}`echo "<text x=\\"$mYT1\\" y=\\"$irev\\" >$imarkfp</text>"`"
+    else
+      textY="${textY}`echo "<text x=\\"$mYT1\\" y=\\"$irev\\" >$imark</text>"`"
+    fi
   fi
 done
 name=`echo $metric | tr ',' '_'`
@@ -490,22 +494,24 @@ echo "\" />" >> "${rpath}/www/graphs/${sIP}.${dbname}.${name}.svg"
 echo "</g>" >> "${rpath}/www/graphs/${sIP}.${dbname}.${name}.svg"
 
 # Marks
-echo "<g id=\"marks\" style=\"fill:none;stroke:#999;stroke-width:0.4\">" >> "${rpath}/www/graphs/${sIP}.${dbname}.${name}.svg"
+echo "<g id=\"marks\" style=\"fill:none;stroke:#999;stroke-width:0.4;font-size:12;\">" >> "${rpath}/www/graphs/${sIP}.${dbname}.${name}.svg"
 echo $marksX >> "${rpath}/www/graphs/${sIP}.${dbname}.${name}.svg"
 echo $marksY >> "${rpath}/www/graphs/${sIP}.${dbname}.${name}.svg"
 echo $textX >> "${rpath}/www/graphs/${sIP}.${dbname}.${name}.svg"
-echo $textY >> "${rpath}/www/graphs/${sIP}.${dbname}.${name}.svg"
+[ "X$scale" == "Xyes" ] || echo $textY >> "${rpath}/www/graphs/${sIP}.${dbname}.${name}.svg"
+echo "<text x=\"$axisXX\" y=\"$axisXY\">$axisX</text>" >> "${rpath}/www/graphs/${sIP}.${dbname}.${name}.svg"
+[ "X$scale" == "Xyes" ] || echo "<text x=\"$axisYX\" y=\"$axisYY\">$axisY</text>" >> "${rpath}/www/graphs/${sIP}.${dbname}.${name}.svg"
 echo "</g>" >> "${rpath}/www/graphs/${sIP}.${dbname}.${name}.svg"
 
 # Graphs
 i=0
-startlegendX=`expr $startX - $legend`
+startlegendX=`solve "$startX - $legend"`
 slegendY=$startY
-
+sadd=`expr \( $graphV - $legend - $padding \) / $sn`
 echo "<g id=\"graph\">" >> "${rpath}/www/graphs/${sIP}.${dbname}.${name}.svg"
 for smetric in `echo $metric | tr ',' ' '` ; do
-  legend="${legend}`echo "<text font-family=\\"Verdana\\" font-size=\\"8\\" fill=\\"${colors[$i]}\\" x=\\"$startlegendX\\" y=\\"$slegendY\\" >$smetric</text>"`"
-  slegendY=`solve "$slegendY + $sadd"`
+  slegend="${slegend}`echo "<text font-family=\\"Verdana\\" font-size=\\"8\\" fill=\\"${colors[$i]}\\" x=\\"$startlegendX\\" y=\\"$slegendY\\" >$smetric</text>"`"
+  slegendY=`solve "$slegendY - $sadd"`
   if [ "X$scale" == "Xyes" ] ; then
     datafile=${TMPDIR}/graph.${sIP}.${dbname}.${smetric}.scaled
   else
@@ -525,7 +531,9 @@ for smetric in `echo $metric | tr ',' ' '` ; do
   i+=1
 done
 echo "</g>" >> "${rpath}/www/graphs/${sIP}.${dbname}.${name}.svg"
-
+echo "<g id=\"legend\">" >> "${rpath}/www/graphs/${sIP}.${dbname}.${name}.svg"
+echo "$slegend" >> "${rpath}/www/graphs/${sIP}.${dbname}.${name}.svg"
+echo "</g>" >> "${rpath}/www/graphs/${sIP}.${dbname}.${name}.svg"
 echo "</svg>" >> "${rpath}/www/graphs/${sIP}.${dbname}.${name}.svg"
 
 #convert -size ${graphH}x${graphV} xc:white -family $fontfamily -pointsize $fontsize \
