bits

diff --git a/cloud/common/cloudsync b/cloud/common/cloudsync
--- a/cloud/common/cloudsync
+++ b/cloud/common/cloudsync
@@ -130,9 +130,10 @@ if [ "X$command" != "X" ] ; then
   ## Deployment system integration ##
   if [ ! -e "$from" ]; then
     source "${rpath}/../../conf/deployment.conf"
-    from=`find "$ROLES_ROOT/$role/$flavor/files/" -maxdepth 1 -name "$from" -type f -o -type l`
-    [ ! -e "$from" ] && from=`find "$ROLES_ROOT/$role/common/files/" -maxdepth 1 -name "$from" -type f -o -type l`
-    [ ! -e "$from" ] && echo "File $from not found" && exit 1
+    [ -n "$flavor" ] && from1=`find "$ROLES_ROOT/$role/$flavor/files/" -maxdepth 1 -name "$from" -type f -o -type l`
+    [ ! -e "$from1" ] && from1=`find "$ROLES_ROOT/$role/common/files/" -maxdepth 1 -name "$from" -type f -o -type l`
+    [ ! -e "$from1" ] && echo "File $from not found" && exit 1
+    from=$from1
   fi
   ##
   [ -h "$from" ] && from=`readlink -m "$from"`
