servers renamed to nodes

diff --git a/cloud/common/cloudexec b/cloud/common/cloudexec
--- a/cloud/common/cloudexec
+++ b/cloud/common/cloudexec
@@ -54,12 +54,12 @@ cleanup() {
 
 remote_exec() {
   if [ "_$verbose" == "_yes" ] ; then
-    echo -e "\n=  Server: $servername ($IP)  Cluster: $CLUSTER"
+    echo -e "\n=  Node: $nodename ($IP)  Cluster: $CLUSTER"
   fi
   if [ `echo "$localip" | grep -c "^$IP$"` -ne 0 ] ; then
     [ -z "$nolocalhost" ] && eval "$command"
   else
-    KEY=`$M_ROOT/helpers/find_key server $IP`
+    KEY=`$M_ROOT/helpers/find_key node $IP`
     [ $? -ne 0 ] && echo "Key not found for IP $IP" && continue
     if [ "_$nosudo" == "_yes" ]; then
       $SSH $TIMEOUT -i "$KEY" -p $SSHPORT "$SSH_REMOTE_USER"@"$IP" \(test -e "$M_ROOT_REMOTE/m.rc" \&\& source "$M_ROOT_REMOTE/m.rc" \; export ip=$IP \; "$command"\)
@@ -111,7 +111,7 @@ if [ "_$help" == "_yes" ] ; then
   cat <<"EOF"
 Usage: ${0##*/} <options> command
 
-Executes command on remote servers. The list of servers is defined by either
+Executes command on remote nodes. The list of nodes is defined by either
 command-line arguments or environment variables.
 
 Any option can be passed as environment variable of the same name.
@@ -120,31 +120,31 @@ Options:
 
   --cloud=[cloud name]     - limits operations by this cloud. Multiple clouds
                              are allowed, separated by comma.
-  --cluster=[cluster name] - the command will be executed on all servers
+  --cluster=[cluster name] - the command will be executed on all nodes
                              from this cluster. Multiple clusters are
                              allowed, separated by comma.
                              MUST be defined. To execute the command on all
-                             servers, use --cluster=all. Accepts also M_CLUSTER
+                             nodes, use --cluster=all. Accepts also M_CLUSTER
                              environment variable (used by msh).
   --all                    - shortcut for --cluster=all.
-  --region=[region]        - the command will be executed on all servers from
+  --region=[region]        - the command will be executed on all nodes from
                              this region.
-  --ip=IP                  - executes the command on a single server. This
+  --ip=IP                  - executes the command on a single node. This
                              allows other scripts to include this one the
                              way that makes possible to apply it to a single
-                             server or multiple servers depending on which
+                             node or multiple nodes depending on which
                              variables are defined. With this option non-empty,
                              cluster and region are ignored.
-  --verbose                - shows each server details before running the
+  --verbose                - shows each node details before running the
                              command.
-  --limit=N                - executes the command on first N servers of each
+  --limit=N                - executes the command on first N nodes of each
                              cluster defined by the --cluster option
-  --user=[username]        - connects to remote servers as user [username] and
+  --user=[username]        - connects to remote nodes as user [username] and
                              executes all commands via sudo. Default user is
                              root.
   --nosudo                 - if user is defined, executes commands without sudo.
                              If user is not defined, does nothing.
-  --threaded               - executes commands on multiple servers in parallel.
+  --threaded               - executes commands on multiple nodes in parallel.
 
 EOF
   exit 0
@@ -162,28 +162,28 @@ for cld in $CLOUD ; do
   localip=`"$M_ROOT/helpers"/localips 2>/dev/null`
   if [ -n "$ip" ] ; then
     cluster= ; region=
-    if [ `grep "|${cld}$" "$M_ROOT/servers.list" | grep -c "^$ip|"` -eq 0 ] ; then
+    if [ `grep "|${cld}$" "$M_ROOT/nodes.list" | grep -c "^$ip|"` -eq 0 ] ; then
       # if name passed as ip
-      if [ `cat "$M_ROOT/servers.list" | cut -d'|' -f4 | grep -c "$ip"` -ne 1 ] ; then
-        "$rpath"/find_server --cloud=$cld --ip=$ip --updatelist
-        [ `grep "|${cld}$" "$M_ROOT/servers.list" | grep -c "^$ip|"` -eq 0 ] && "$rpath"/find_server --cloud=$cld --name=$name --updatelist
+      if [ `cat "$M_ROOT/nodes.list" | cut -d'|' -f4 | grep -c "$ip"` -ne 1 ] ; then
+        "$rpath"/find_node --cloud=$cld --ip=$ip --updatelist
+        [ `grep "|${cld}$" "$M_ROOT/nodes.list" | grep -c "^$ip|"` -eq 0 ] && "$rpath"/find_node --cloud=$cld --name=$name --updatelist
       fi
     fi
     # again
-    if [ `grep "|${cld}$" "$M_ROOT/servers.list" | grep -c "^$ip|"` -eq 0 ] ; then
+    if [ `grep "|${cld}$" "$M_ROOT/nodes.list" | grep -c "^$ip|"` -eq 0 ] ; then
       # maybe name passed as ip
-      if [ `cat "$M_ROOT/servers.list" | cut -d'|' -f4 | grep -c "$ip"` -ne 1 ] ; then
+      if [ `cat "$M_ROOT/nodes.list" | cut -d'|' -f4 | grep -c "$ip"` -ne 1 ] ; then
         echo "Unable to find $ip in cloud $cld"
         exit 1
       else
-        ip=`cat "$M_ROOT/servers.list" | grep -vE "^#|^[[:space:]]#|^$" | grep "|${cld}$" | cut -d'|' -f1,4 | grep "|${ip}$" | cut -d'|' -f1`
-        [ -z "$ip" ] && echo "Was unable to find IP by server name." && exit 1
+        ip=`cat "$M_ROOT/nodes.list" | grep -vE "^#|^[[:space:]]#|^$" | grep "|${cld}$" | cut -d'|' -f1,4 | grep "|${ip}$" | cut -d'|' -f1`
+        [ -z "$ip" ] && echo "Was unable to find IP by node name." && exit 1
       fi
     else
       # cluster is still needed in some cases
-      server=`grep "|${cld}$" "$M_ROOT/servers.list" | grep "^$ip|"`
-      cluster=`echo "$server" | cut -d'|' -f5`
-      region=`echo "$server" | cut -d'|' -f3`
+      node=`grep "|${cld}$" "$M_ROOT/nodes.list" | grep "^$ip|"`
+      cluster=`echo "$node" | cut -d'|' -f5`
+      region=`echo "$node" | cut -d'|' -f3`
     fi
   fi
 
@@ -191,7 +191,7 @@ for cld in $CLOUD ; do
   [ -z "$cluster" ] && cluster=$M_CLUSTER
   [ -z "$cluster" ] && echo "No clusters found" && exit 1
 
-  [ "$cluster" == "all" ] && clusters=`cat "$M_ROOT/servers.list" | grep "|${cld}$" | grep -v ^$ | grep -v  ^#|grep -v ^[[:space:]]*# | cut -d'|' -f5 | sort | uniq | grep -v "^${SUPER_CLUSTER}$"` || clusters=$cluster
+  [ "$cluster" == "all" ] && clusters=`cat "$M_ROOT/nodes.list" | grep "|${cld}$" | grep -v ^$ | grep -v  ^#|grep -v ^[[:space:]]*# | cut -d'|' -f5 | sort | uniq | grep -v "^${SUPER_CLUSTER}$"` || clusters=$cluster
 
   declare -i n
   IFS1=$IFS
@@ -207,16 +207,16 @@ for cld in $CLOUD ; do
       unset CLUSTER KEY REGION NAME M_ROOT_REMOTE
       M_ROOT_REMOTE=`grep ^$icluster\| "$M_ROOT/conf/clusters.conf" | cut -d'|' -f8`
       
-      serverlist=`cat "$M_ROOT/servers.list" | grep "|${cld}$" | grep -vE "^$|^#|^[[:space:]]*#"`
-      for servername in `echo "$serverlist" | cut -d'|' -f4 | sort | uniq` ; do
-        server=`echo "$serverlist" | grep "|$servername|"`
-        if [ `echo "$server" | wc -l` -gt 1 ]; then
-          echo "more than one server named $servername is found:"
-          for s in `echo "$server"` ; do
+      nodelist=`cat "$M_ROOT/nodes.list" | grep "|${cld}$" | grep -vE "^$|^#|^[[:space:]]*#"`
+      for nodename in `echo "$nodelist" | cut -d'|' -f4 | sort | uniq` ; do
+        node=`echo "$nodelist" | grep "|$nodename|"`
+        if [ `echo "$node" | wc -l` -gt 1 ]; then
+          echo "more than one node named $nodename is found:"
+          for s in `echo "$node"` ; do
             echo "$s"
           done
         fi
-        for s in `echo "$server"` ; do
+        for s in `echo "$node"` ; do
           [ -n "$limit" ] && [[ $n -ge $limit ]] && break
           IP=${s%%|*}
           if [ -n "$ip" ] ; then
@@ -227,7 +227,7 @@ for cld in $CLOUD ; do
             [ "_$REGION" == "_$region" ] || continue
           fi
           CLUSTER=`echo $s | cut -d'|' -f5`
-          # if server's cluster is not found, it's a bug, but it's a good idea to
+          # if node's cluster is not found, it's a bug, but it's a good idea to
           # still show it in the output when --cluster=all
           if [ -z "$CLUSTER" ]; then
             [ "$cluster" == "all" ] || continue
diff --git a/cloud/common/cloudsync b/cloud/common/cloudsync
--- a/cloud/common/cloudsync
+++ b/cloud/common/cloudsync
@@ -65,16 +65,16 @@ cleanup() {
 
 remote_sync() {
   if [ "_$verbose" == "_yes" ] ; then
-    NAME=`echo $server | cut -d'|' -f4`
+    NAME=`echo $node | cut -d'|' -f4`
     echo
-    echo "=  Server: $NAME ($IP)  Cluster: $CLUSTER"
+    echo "=  Node: $NAME ($IP)  Cluster: $CLUSTER"
   fi
   if [ `echo "$localip" | grep -c "^$IP$"` -ne 0 ] ; then
     if [ -z "$nolocalhost" ]; then
       [ "$from" != "$to" ] && cp -up $from $to || echo "Same file, skipping"
     fi
   else
-    KEY=`$M_ROOT/helpers/find_key server $IP` || continue
+    KEY=`$M_ROOT/helpers/find_key node $IP` || continue
     if [ -n "$RSYNC" ] ; then
       $RSYNC -l $recursive -e "$SSH $TIMEOUT -i \"$KEY\" -p $SSHPORT" "${from%/}" "$SSH_REMOTE_USER"@"${IP}:${to}"
       [ $? -eq 0 ] && echo "Success" && continue
@@ -132,23 +132,23 @@ if [ "_$help" == "_yes" ] ; then
   cat <<"EOF"
 Usage: ${0##*/} <options> <local path> <remote path>
 
-Rsyncs (or copies over if rsync not found) local path to remote path on remote servers. The list of target servers is defined by either command-line arguments or environment variables.
+Rsyncs (or copies over if rsync not found) local path to remote path on remote nodes. The list of target nodes is defined by either command-line arguments or environment variables.
 
 Options:
 
   --recursive              - recursive sync of directories, implies --delete
-  --cluster=clustername    - syncs to all servers from this cluster.
+  --cluster=clustername    - syncs to all nodes from this cluster.
                              Multiple clusters are allowed, separated by comma.
-                             MUST be defined. To sync to all servers, use 
+                             MUST be defined. To sync to all nodes, use 
                              --cluster=all. Accepts also M_CLUSTER environment
                              variable (from msh environment).
   --all                    - shortcut for --cluster=all.
-  --ip=IP                  - ip for a single server operation.
+  --ip=IP                  - ip for a single node operation.
                              If ip is defined, cluster and region are ignored.
-  --region=region          - syncs to all servers from this region.
-  --verbose                - shows each server details before running
+  --region=region          - syncs to all nodes from this region.
+  --verbose                - shows each node details before running
                              the command.
-  --user=[username]        - connects to remote servers as user [username].
+  --user=[username]        - connects to remote nodes as user [username].
                              Default user is root.
 
 EOF
@@ -167,28 +167,28 @@ for cld in $CLOUD ; do
 
   if [ -n "$ip" ] ; then
     cluster= ; region=
-    if [ `grep "|${cld}$" "$M_ROOT/servers.list" | grep -c "^$ip|"` -eq 0 ] ; then
+    if [ `grep "|${cld}$" "$M_ROOT/nodes.list" | grep -c "^$ip|"` -eq 0 ] ; then
       # maybe name passed as ip
-      if [ `grep "|${cld}$" "$M_ROOT/servers.list" | cut -d'|' -f4 | grep -c "^${ip}$"` -eq 0 ] ; then
-        "$rpath"/find_server --cloud=$cld --ip=$ip --updatelist
-        [ `grep "|${cld}$" "$M_ROOT/servers.list" | grep -c "^$ip|"` -eq 0 ] && "$rpath"/find_server --cloud=$cld --name=$name --updatelist
+      if [ `grep "|${cld}$" "$M_ROOT/nodes.list" | cut -d'|' -f4 | grep -c "^${ip}$"` -eq 0 ] ; then
+        "$rpath"/find_node --cloud=$cld --ip=$ip --updatelist
+        [ `grep "|${cld}$" "$M_ROOT/nodes.list" | grep -c "^$ip|"` -eq 0 ] && "$rpath"/find_node --cloud=$cld --name=$name --updatelist
       fi
     fi
     # again
-    if [ `grep "|${cld}$" "$M_ROOT/servers.list" | grep -c "^$ip|"` -eq 0 ] ; then
+    if [ `grep "|${cld}$" "$M_ROOT/nodes.list" | grep -c "^$ip|"` -eq 0 ] ; then
       # maybe name passed as ip
-      if [ `cat "$M_ROOT/servers.list" | cut -d'|' -f4 | grep -c "$ip"` -ne 1 ] ; then
+      if [ `cat "$M_ROOT/nodes.list" | cut -d'|' -f4 | grep -c "$ip"` -ne 1 ] ; then
         echo "Unable to find $ip in cloud $cld"
         exit 1
       else
-        ip=`cat "$M_ROOT/servers.list" | grep -vE "^#|^[[:space:]]#|^$" | grep "|${cld}$" | cut -d'|' -f1,4 | grep "|${ip}$" | cut -d'|' -f1`
-        [ -z "$ip" ] && echo "Was unable to find IP by server name." && exit 1
+        ip=`cat "$M_ROOT/nodes.list" | grep -vE "^#|^[[:space:]]#|^$" | grep "|${cld}$" | cut -d'|' -f1,4 | grep "|${ip}$" | cut -d'|' -f1`
+        [ -z "$ip" ] && echo "Was unable to find IP by node name." && exit 1
       fi
     else
       # cluster is still needed in some cases
-      server=`grep "|${cld}$" "$M_ROOT/servers.list" | grep "^$ip|"`
-      cluster=`echo "$server" | cut -d'|' -f5`
-      region=`echo "$server" | cut -d'|' -f3`
+      node=`grep "|${cld}$" "$M_ROOT/nodes.list" | grep "^$ip|"`
+      cluster=`echo "$node" | cut -d'|' -f5`
+      region=`echo "$node" | cut -d'|' -f3`
     fi
   fi
 
@@ -196,7 +196,7 @@ for cld in $CLOUD ; do
   [ -z "$cluster" ] && cluster=$M_CLUSTER
   [ -z "$cluster" ] && echo "No clusters found" && exit 1
 
-  [ "_$cluster" == "_all" ] && clusters=`cat "$M_ROOT/servers.list" | grep "|${cld}$" | grep -v ^$ | grep -v  ^#|grep -v ^[[:space:]]*# | cut -d'|' -f5 | sort | uniq | grep -v "^${SUPER_CLUSTER}$"` || clusters=$cluster
+  [ "_$cluster" == "_all" ] && clusters=`cat "$M_ROOT/nodes.list" | grep "|${cld}$" | grep -v ^$ | grep -v  ^#|grep -v ^[[:space:]]*# | cut -d'|' -f5 | sort | uniq | grep -v "^${SUPER_CLUSTER}$"` || clusters=$cluster
 
   declare -i n
   IFS1=$IFS
@@ -226,26 +226,26 @@ for cld in $CLOUD ; do
       [ -z "$SSH_REMOTE_USER" ] && SSH_REMOTE_USER=`cat "$M_ROOT/conf/clusters.conf" | grep -vE "^#|^[[:space:]]#|^$" | grep "^$cluster|" | cut -s -d'|' -f13`
       [ -z "$SSH_REMOTE_USER" ] && SSH_REMOTE_USER="root"
 
-      serverlist=`cat "$M_ROOT/servers.list" | grep "|${cld}$" | grep -vE "^$|^#|^[[:space:]]*#"`
-      for servername in `echo "$serverlist" | cut -d'|' -f4 | sort | uniq` ; do
-        server=`echo "$serverlist" | grep "|$servername|"`
-        if [ `echo "$server" | wc -l` -gt 1 ]; then
-          echo "more than one server named $servername is found:"
-          for s in `echo "$server"` ; do
+      nodelist=`cat "$M_ROOT/nodes.list" | grep "|${cld}$" | grep -vE "^$|^#|^[[:space:]]*#"`
+      for nodename in `echo "$nodelist" | cut -d'|' -f4 | sort | uniq` ; do
+        node=`echo "$nodelist" | grep "|$nodename|"`
+        if [ `echo "$node" | wc -l` -gt 1 ]; then
+          echo "more than one node named $nodename is found:"
+          for s in `echo "$node"` ; do
             echo "$s"
           done
         fi
-        for s in `echo "$server"` ; do
-          IP=${server%%|*}
+        for s in `echo "$node"` ; do
+          IP=${s%%|*}
           if [ -n "$ip" ] ; then
             [ "_$IP" == "_$ip" ] || continue
           fi
           if [ -n "$region" ] ; then
-            REGION=`echo $server | cut -d'|' -f3`
+            REGION=`echo $s | cut -d'|' -f3`
             [ "_$REGION" == "_$region" ] || continue
           fi
           if [ -n "$cluster" ] ; then
-            CLUSTER=`echo $server | cut -d'|' -f5`
+            CLUSTER=`echo $s | cut -d'|' -f5`
             [ "_$CLUSTER" == "_$cluster" ] || continue
           fi
           if [ "_$threaded" == "_yes" ]; then
diff --git a/cloud/ec2/route53query b/cloud/ec2/route53query
--- a/cloud/ec2/route53query
+++ b/cloud/ec2/route53query
@@ -31,7 +31,7 @@ CURL="$CURL -s"
 
 possible_options="region action id zone name type value items wholezone noupdate comment hostedzoneid dnsname"
 necessary_options="action"
-[ "X$*" == "X" ] && echo "Can't run without options. Possible options are: ${possible_options}" && exit 1
+[ -z "$*" ] && echo "Can't run without options. Possible options are: ${possible_options}" && exit 1
 
 IFS1=$IFS
 IFS='--'
@@ -41,10 +41,10 @@ do
   s_option=${s_option/--/}
   s_optname=${s_option%%=*}
   s_optarg=${s_option##*=}
-  [ "X$s_optarg" == "X$s_optname" ] && s_optarg="yes"
+  [ "_$s_optarg" == "_$s_optname" ] && s_optarg="yes"
 
   for option in ${possible_options// /--} ; do
-    [ "X$s_optname" == "X$option" ] && eval "$s_optname=\"$s_optarg\"" && found=true && break
+    [ "_$s_optname" == "_$option" ] && eval "$s_optname=\"$s_optarg\"" && found=true && break
   done
   
   if ! $found ; then 
@@ -63,9 +63,9 @@ if $found ; then
   exit 1
 fi
 
-[ "X$action" == "Xlistzone" ] && [ -z "$type" ] && type="SOA"
-[ "X$action" == "Xlistzone" ] && [ -z "$name" ] && name=$zone
-[ "X$action" == "Xlistzone" ] && [ -z "$items" ] && items=1
+[ "_$action" == "_listzone" ] && [ -z "$type" ] && type="SOA"
+[ "_$action" == "_listzone" ] && [ -z "$name" ] && name=$zone
+[ "_$action" == "_listzone" ] && [ -z "$items" ] && items=1
 
 request=$M_TEMP/r53query.$$
 
diff --git a/deployment/metaexec b/deployment/metaexec
--- a/deployment/metaexec
+++ b/deployment/metaexec
@@ -172,17 +172,17 @@ run_meta() {
   fi
 }
 
-startserver() {
+createnode() {
   ip=0 
-  ip="$(IAMACHILD=1 "$rpath"/../cloud/$CLOUD_PROVIDER/start_server --cluster=$cluster --return=ip "$V" "$T" 2>>"$rpath"/../logs/cloud.log | tail -1)"
+  ip="$(IAMACHILD=1 "$rpath"/../cloud/$CLOUD_PROVIDER/create_node --cluster=$cluster --return=ip "$V" "$T" 2>>"$rpath"/../logs/cloud.log | tail -1)"
   [ $? -ne 0 ] && ip=$? 
-  log "($CLOUD) start_server returned this: $ip"
+  log "($CLOUD) create_node returned this: $ip"
 }
 
 SSH=`which ssh 2>/dev/null`
 SCP=`which scp 2>/dev/null`
 
-possible_options="help verbose debug flavor ip cloud cluster task role timestamp test dry command output repeat newserver list skip force ignoreipnotpresent ignoreemptycluster ignorenocluster usage user nosudo nolock newtimestamp name"
+possible_options="help verbose debug flavor ip cloud cluster task role timestamp test dry command output repeat newnode list skip force ignoreipnotpresent ignoreemptycluster ignorenocluster usage user nosudo nolock newtimestamp name"
 [ -z "$*" ] && usage="yes"
 
 IFSORIG=$IFS
@@ -290,20 +290,20 @@ Repeat options:
 
 Other options:
 
-  --newserver		this is a shortcut combining start_server command and
-			metascript execution on this new server when it is
+  --newnode		this is a shortcut combining create_node command and
+			metascript execution on this new node when it is
 			ready; includes all necessary automation: getting
-			new server status, repeating the call if it has failed,
+			new node status, repeating the call if it has failed,
 			inserting the IP into the list, ensuring it is up
 			and accessible etc. See documentation for more details
 			
-  --nolock   the default is to lock cloud operations if --newserver option
+  --nolock   the default is to lock cloud operations if --newnode option
       is present; this helps to avoid background API calls caused
-      by absence of the target server in servers.list which may happen
-      due to the lag with which just started server appears in the list
+      by absence of the target node in nodes.list which may happen
+      due to the lag with which just created node appears in the list
       returned by cloud API. But if the task is long enough, you may want
       to avoid locking. This should not cause any problems, but may require
-      some extra time and extra API calls to ensure the target server presence.
+      some extra time and extra API calls to ensure the target node presence.
       
 
 EOF
@@ -349,7 +349,7 @@ log "Starting metaexec with arguments $@"
 localip=`"$M_ROOT"/helpers/localips | grep -v '127.0.0.1'`
 
 if [ -n "$timestamp" ]; then
-  [ -n "$newserver" ] && echo "Repeating existing sequence is disabled for new server. If you want to repeat a meta that has brought up a previous server, it's safe to run $rcommand --repeat or $rcommand --timestamp=<timestamp> without other arguments. It will pick up IP address of that server and all relevant arguments." && exit 1
+  [ -n "$newnode" ] && echo "Repeating existing sequence is disabled for new node. If you want to repeat a meta that has brought up a previous node, it's safe to run $rcommand --repeat or $rcommand --timestamp=<timestamp> without other arguments. It will pick up IP address of that node and all relevant arguments." && exit 1
   if [ "_$timestamp" == "_repeat" ]; then
     timestampact=`ls -1tr "$M_DEPL_WORK_DIR" | tail -1` && timestampact=${timestampact##*.} && echo "Restoring process with timestamp $timestampact"
   else
@@ -358,7 +358,7 @@ if [ -n "$timestamp" ]; then
   if [ -n "$timestampact" ]; then
     argfile=`find "$M_DEPL_WORK_DIR"/*.$timestampact/ -maxdepth 1 -name ARGV`
     if [ -f "$argfile" ]; then
-      sed -i "/^newserver=/d;/^test=/d;/^verbose=/d;/^debug=/d;/^timestamp=/d" "$argfile"
+      sed -i "/^newnode=/d;/^test=/d;/^verbose=/d;/^debug=/d;/^timestamp=/d" "$argfile"
       source "$argfile"
     else
       echo "Process with timestamp $timestampact cannot be repeated, no arguments file found"
@@ -370,15 +370,15 @@ else
 fi
 
 if [ -n "$ip" ]; then
-  [ -n "$newserver" ] && echo "Both newserver and ip are defined. Not sure what to do." && exit 1
+  [ -n "$newnode" ] && echo "Both newnode and ip are defined. Not sure what to do." && exit 1
   if [ `expr "$ip" : "[^[0-9.]]*" 2>/dev/null` -ne 0 ] ; then
     echo "Something's wrong with IP: $ip"
     exit 1
   fi
-  ipcluster=`grep "^$ip|" "$M_ROOT/servers.list" | cut -d'|' -f5`
-  [ -z "$ipcluster" ] && [ -n "$CLOUD" ] && "$M_ROOT"/cloud/common/find_server --cloud=$CLOUD --ip=$ip --updatelist
-  ipcluster=`grep "^$ip|" "$M_ROOT/servers.list" | cut -d'|' -f5`
-  [ -z "$ipcluster" ] && [ -z "$ignoreemptycluster" ] && [ -z "$ignoreipnotpresent" ] && echo "IP $ip is not present in servers.list or has no cluster defined." && exit 1
+  ipcluster=`grep "^$ip|" "$M_ROOT/nodes.list" | cut -d'|' -f5`
+  [ -z "$ipcluster" ] && [ -n "$CLOUD" ] && "$M_ROOT"/cloud/common/find_node --cloud=$CLOUD --ip=$ip --updatelist
+  ipcluster=`grep "^$ip|" "$M_ROOT/nodes.list" | cut -d'|' -f5`
+  [ -z "$ipcluster" ] && [ -z "$ignoreemptycluster" ] && [ -z "$ignoreipnotpresent" ] && echo "IP $ip is not present in nodes.list or has no cluster defined." && exit 1
   if [ -n "$cluster" ]; then
     [ "$cluster" != "$ipcluster" ] && [ -z "$force" ] && echo "Cluster found for this IP is ${ipcluster}, but cluster provided as an option is $cluster" && exit 1
   else
@@ -406,7 +406,7 @@ else
     if [ -z "$role" ]; then
       role=`grep ^$cluster\| "$M_ROOT/conf/clusters.conf" | cut -d'|' -f10`
       echo "Using role ${role}, default for cluster $cluster"
-      [ -z "$role" ] && echo "Unable to find the role of this cluster/server" && exit 1
+      [ -z "$role" ] && echo "Unable to find the role of this cluster/node" && exit 1
     fi
   fi
 fi
@@ -438,50 +438,50 @@ touch "$CURRTASKDIR/log"
 
 if [ -z "$flavor" ]; then
   flavor=`grep ^$cluster\| "$M_ROOT/conf/clusters.conf" | cut -d'|' -f11`
-  [ -z "$flavor" ] && echo -e "Unable to find the flavor of this cluster/server OS\n\n (hint: option --flavor is available)\n" && exit 1 || echo "Using flavor $flavor, default for cluster $cluster"
+  [ -z "$flavor" ] && echo -e "Unable to find the flavor of this cluster/node OS\n\n (hint: option --flavor is available)\n" && exit 1 || echo "Using flavor $flavor, default for cluster $cluster"
 fi
 
-[ -z "$SERVER_CHECKS_NUMBER" ] && SERVER_CHECKS_NUMBER=20
-[ -z "$SERVER_CHECKS_PERIOD" ] && SERVER_CHECKS_PERIOD=30
+[ -z "$NODE_CHECKS_NUMBER" ] && NODE_CHECKS_NUMBER=20
+[ -z "$NODE_CHECKS_PERIOD" ] && NODE_CHECKS_PERIOD=30
 
 if [ -n "$newserver" ]; then
   
-  [ -z "$NEW_SERVER_START_TRIES" ] && NEW_SERVER_START_TRIES=3
+  [ -z "$NEW_NODE_CREATE_TRIES" ] && NEW_NODE_CREATE_TRIES=3
   [ -z "$WAIT_BETWEEN_TRIES" ] && WAIT_BETWEEN_TRIES=30
-  echo "*** Bringing up new server in cloud $CLOUD"
-  log "bringing up new server in cloud $CLOUD"
+  echo "*** Bringing up new node in cloud $CLOUD"
+  log "bringing up new node in cloud $CLOUD"
   if [ -z "$test" ]; then
 
     if [ -z "$nolock" ]; then
       log "getting cloud operations lock"
       lock_cloudops || exit 10
     fi
-    log "initiating start_server sequence"
+    log "initiating create_node sequence"
     
-    for ((i=0; i<$NEW_SERVER_START_TRIES; i++)); do
+    for ((i=0; i<$NEW_NODE_CREATE_TRIES; i++)); do
       [ $i -eq 0 ] || sleep $WAIT_BETWEEN_TRIES
-      startserver $T
+      createnode $T
       if [[ `expr "$ip" : "[0-9]*\.[0-9.]*$"` -ne 0 ]]; then
         break
       else
         # assuming it's the exit status (see the function)
         res=$ip
       fi
-      [[ $res -eq 2 ]] && log "Timeout waiting for the server ready" && break
-      [[ $res -eq 5 ]] && log "Maximum servers number for cluster $cluster has been reached, unable to add another server" && proper_exit 5 471
+      [[ $res -eq 2 ]] && log "Timeout waiting for the node ready" && break
+      [[ $res -eq 5 ]] && log "Maximum nodes number for cluster $cluster has been reached, unable to add another node" && proper_exit 5 471
       # various weird errors below, exit 1 
-      [[ $res -eq 6 ]] && log "Failed to generate a name for the new server" && proper_exit 1 473
-      [[ $res -eq 7 ]] && log "Failed to find out what image to use to create the new server, define it in clusters.conf, please" && proper_exit 1 474
-      [[ $res -eq 8 ]] && log "Failed to find out what flavor (server size) to use, define it in clusters.conf, please" && proper_exit 1 475
+      [[ $res -eq 6 ]] && log "Failed to generate a name for the new node" && proper_exit 1 473
+      [[ $res -eq 7 ]] && log "Failed to find out what image to use to create the new node, define it in clusters.conf, please" && proper_exit 1 474
+      [[ $res -eq 8 ]] && log "Failed to find out what flavor (node size) to use, define it in clusters.conf, please" && proper_exit 1 475
       [[ $res -eq 9 ]] && log "Failed to find out what region (datacenter) to use, define it in clusters.conf, please" && proper_exit 1 476
-      [[ $res -eq 1 ]] && log "Something went wrong, unable to add a server to the cluster $cluster"
+      [[ $res -eq 1 ]] && log "Something went wrong, unable to add a node to the cluster $cluster"
       if [ -z "$ip" ]; then
-        log "Was unable either to start a cloud server in the cloud $CLOUD or to get its IP address." && sleep $WAIT_BETWEEN_TRIES && continue
+        log "Was unable either to create a cloud node in the cloud $CLOUD or to get its IP address." && sleep $WAIT_BETWEEN_TRIES && continue
       fi
       [[ `expr $ip : [0-9.]*$` -eq 0 ]] && log "Something's wrong with IP: $ip"
       echo "Something went wrong, check $LOG and fix the problem, next try is in $WAIT_BETWEEN_TRIES seconds"
     done
-    [ $i -eq $NEW_SERVER_START_TRIES ] && log "Maximal number of tries reached, exiting" && proper_exit 1 483
+    [ $i -eq $NEW_NODE_CREATE_TRIES ] && log "Maximal number of tries reached, exiting" && proper_exit 1 483
   else
     echo "*** This is a test"
   fi
@@ -513,28 +513,28 @@ if [ -n "$ip" ]; then
   fi
 fi
 
-KEY=`"$M_ROOT"/helpers/find_key cluster "$cluster"` || KEY=`"$M_ROOT"/helpers/find_key server "$ip"` || proper_exit 1 509
+KEY=`"$M_ROOT"/helpers/find_key cluster "$cluster"` || KEY=`"$M_ROOT"/helpers/find_key node "$ip"` || proper_exit 1 509
 [ -z "$KEY" ] && echo "Access key not found!" && proper_exit 1 510
 [ -z "$SSH" ] && echo "SSH client not found!" && proper_exit 1 511
-# it's here because startserver function re-reads cloud config
+# it's here because createnode function re-reads cloud config
 [ -n "$SSHPORT" ] || SSHPORT=22
 if [ -z "$list" ]; then
-  $debug && log "ensuring the target server $ip is accessible"
+  $debug && log "ensuring the target node $ip is accessible"
   if [ -z "$test" -a -n "$ip" ]; then
-    for ((k=0; k<$SERVER_CHECKS_NUMBER; k++)); do
+    for ((k=0; k<$NODE_CHECKS_NUMBER; k++)); do
       $SSH -i "$KEY" -p $SSHPORT -o "StrictHostKeyChecking=no" -o "ConnectTimeout=10" -o "PasswordAuthentication=no" "$SSH_REMOTE_USER"@"$ip" echo >>$LOG 2>&1
       if [ $? -ne 0 ]; then
-        echo "Unable to login to the server $ip using key ${KEY}, trying again...">>"$LOG"
+        echo "Unable to login to the node $ip using key ${KEY}, trying again...">>"$LOG"
         loggedin=false
-        sleep $SERVER_CHECKS_PERIOD
+        sleep $NODE_CHECKS_PERIOD
       else
         loggedin=true
         break
       fi
     done
-    if ! $loggedin && [ -n "$newserver" ]; then
-      # stop useless server and tell the parent process that something's wrong
-      "$M_ROOT"/cloud/$CLOUD_PROVIDER/stop_server --ip=$ip
+    if ! $loggedin && [ -n "$newnode" ]; then
+      # stop useless node and tell the parent process that something's wrong
+      "$M_ROOT"/cloud/$CLOUD_PROVIDER/destroy_node --ip=$ip
       proper_exit 13 531
     fi
   fi
@@ -551,7 +551,7 @@ if [ -z "$list" ]; then
     done
     IFS=$IFS2
     echo -e "flavor=$flavor\ncluster=$cluster\nrole=$role\n" >> "$CURRTASKDIR/ARGV"
-    if [ -n "$newserver" ]; then
+    if [ -n "$newnode" ]; then
       echo "ip=\"$ip\"" >> "$CURRTASKDIR/ARGV"
     fi
   else
@@ -622,7 +622,7 @@ if [ -z "$list" ]; then
   find "$M_DEPL_WORK_DIR" -maxdepth 1 -mindepth 1 -type d -mtime +$KEEP_DEPLOYTMP -exec rm -rf {} \;
 fi
 echo
-if [ -n "$newserver" ]; then
+if [ -n "$newnode" ]; then
   proper_exit 0 597
 fi
 #echo "Preparing the keys"
diff --git a/deployment/testmeta b/deployment/testmeta
--- a/deployment/testmeta
+++ b/deployment/testmeta
@@ -84,18 +84,18 @@ export PATH=$M_ROOT/deployment:$M_ROOT/cloud/${cloud}:$M_ROOT/helpers:$PATH
 if [ -z "$role" -o -z "$flavor" ] ; then
   [ -z "$cluster" -a -z "$ip" ] && echo "Either role or flavor not found. In this case either ip or cluster is necessary." && exit 1
 fi
-[ -z "$cluster" -a -n "$ip" ] && cluster=`grep ^$ip\| "$rpath/../servers.list" | cut -d'|' -f5`
+[ -z "$cluster" -a -n "$ip" ] && cluster=`grep ^$ip\| "$rpath/../nodes.list" | cut -d'|' -f5`
 [ -n "$cluster" -a -z "$ip" ] && ip="127.0.0.1"
 declare -i RETVAL
 RETVAL=0
 good=true
 if [ -z "$role" ] ; then
   role=`grep ^$cluster\| "$rpath/../conf/clusters.conf" | cut -d'|' -f10`
-  [ -z "$role" ] && echo "Unable to find the role of this cluster/server. Define one of role, cluster, ip or check if you have a default role defined for this cluster in conf/clusters.conf" && exit 1
+  [ -z "$role" ] && echo "Unable to find the role of this cluster/node. Define one of role, cluster, ip or check if you have a default role defined for this cluster in conf/clusters.conf" && exit 1
 fi
 if [ -z "$flavor" ] ; then
   flavor=`grep ^$cluster\| "$rpath/../conf/clusters.conf" | cut -d'|' -f11`
-  [ -z "$flavor" ] && echo "Unable to find the flavor of this cluster/server OS. Define it as a command-line option or check if this cluster has a default flavor set in conf/cluster.conf" && exit 1
+  [ -z "$flavor" ] && echo "Unable to find the flavor of this cluster/node OS. Define it as a command-line option or check if this cluster has a default flavor set in conf/cluster.conf" && exit 1
 fi
 
 IFS1=$IFS
diff --git a/helpers/mssh b/helpers/mssh
--- a/helpers/mssh
+++ b/helpers/mssh
@@ -38,15 +38,15 @@ SSH_REMOTE_USER_ARG=`echo "$host" | cut -s -d'@' -f1`
 host=`echo "$host" | cut -d'@' -f2`
 
 # if target is IP
-KEY=`grep ^${host}\| "$M_ROOT/servers.list" | cut -d'|' -f2`
+KEY=`grep ^${host}\| "$M_ROOT/nodes.list" | cut -d'|' -f2`
 # if target is hostname
-[ -z "$KEY" ] && KEY=`cat "$M_ROOT/servers.list" | cut -d'|' -f2,4 | grep \|${host}$ | cut -d'|' -f1`
+[ -z "$KEY" ] && KEY=`cat "$M_ROOT/nodes.list" | cut -d'|' -f2,4 | grep \|${host}$ | cut -d'|' -f1`
 
-cluster=`grep ^${host}\| "$M_ROOT/servers.list" | cut -d'|' -f5`
-[ -z "$cluster" ] && cluster=`grep \|${host}\| "$M_ROOT/servers.list" | cut -d'|' -f5`
+cluster=`grep ^${host}\| "$M_ROOT/nodes.list" | cut -d'|' -f5`
+[ -z "$cluster" ] && cluster=`grep \|${host}\| "$M_ROOT/nodes.list" | cut -d'|' -f5`
 [ -z "$SSH_REMOTE_USER" ] && SSH_REMOTE_USER=`grep "^${cluster}|" "$M_ROOT/conf/clusters.conf" | cut -s -d'|' -f13`
 [ -z "$SSH_REMOTE_USER" ] && SSH_REMOTE_USER="root"
-M_ROOT_REMOTE=`grep \|${host}\| "$M_ROOT/servers.list" | cut -d'|' -f8`
+M_ROOT_REMOTE=`grep \|${host}\| "$M_ROOT/nodes.list" | cut -d'|' -f8`
 [ -z "$M_ROOT_REMOTE" ] && M_ROOT_REMOTE="$M_ROOT"
 
 if [ -n "$*" ]; then
@@ -64,7 +64,7 @@ if [ -n "$KEY" ]; then
     [ -f "$M_ROOT/keys/$KEY1" ] && KEY=$KEY1
   fi
 else
-  echo "Server $host not found in servers.list" >&2
+  echo "Server $host not found in nodes.list" >&2
 fi
 
 if [ ! -f "$M_ROOT/keys/$KEY" ]; then
