proper cluster env variable exporting

diff --git a/cloud/common/cloudexec b/cloud/common/cloudexec
--- a/cloud/common/cloudexec
+++ b/cloud/common/cloudexec
@@ -91,16 +91,20 @@ fi
 
 [ "X$IFCFG" != "X" ] && localip=`$IFCFG | sed '/inet\ /!d;s/.*r://;s/\ .*//' | grep -v '127.0.0.1'` || localip="ifconfig_not_found"
 if [ -n "$ip" ] ; then
-  cluster= && region=
+  cluster= ; region=
   if [ `grep -c "^$ip|" "${rpath}/../../servers.list"` -eq 0 ] ; then
     if [ `cat "${rpath}/../../servers.list" | cut -d'|' -f4 | grep -c "$ip"` -ne 1 ] ; then
       echo "Unable to find $ip in servers.list"
       exit 1
     else
+      # if name passed as ip
       ip=`cat "${rpath}/../../servers.list" | cut -d'|' -f1,4 | grep "|${ip}$" | cut -d'|' -f1`
+      [ -z "$ip" ] && echo "Was unable to find IP by server name." && exit 1
     fi
   fi
 fi
+[ -z "$cluster" ] && cluster=$M_CLUSTER
+# all clusters, then
 [ -n "$cluster" ] || cluster=`cat "${rpath}/../../servers.list" | grep -v ^$ | grep -v  ^#|grep -v ^[[:space:]]*# | cut -d'|' -f5 | sort | uniq`
 declare -i n
 IFS1=$IFS
diff --git a/cloud/common/cloudsync b/cloud/common/cloudsync
--- a/cloud/common/cloudsync
+++ b/cloud/common/cloudsync
@@ -111,10 +111,14 @@ if [ -n "$ip" ] ; then
       echo "Unable to find $ip in servers.list"
       exit 1
     else
+      # if name passed as ip
       ip=`cat "${rpath}/../../servers.list" | cut -d'|' -f1,4 | grep "|${ip}$" | cut -d'|' -f1`
+      [ -z "$ip" ] && echo "Was unable to find IP by server name." && exit 1
     fi
   fi
 fi
+[ -z "$cluster" ] && cluster=$M_CLUSTER
+# all clusters, then
 [ -n "$cluster" ] || cluster=`cat "${rpath}/../../servers.list" | grep -v ^$ | grep -v  ^#|grep -v ^[[:space:]]*# | cut -d'|' -f5 | sort | uniq`
 [ -z "$cluster" ] && echo "No clusters found" && exit 1
 
