fixing bad API with find_server in more places

diff --git a/cloud/common/cloudsync b/cloud/common/cloudsync
--- a/cloud/common/cloudsync
+++ b/cloud/common/cloudsync
@@ -167,13 +167,23 @@ for cld in $CLOUD ; do
   if [ -n "$ip" ] ; then
     cluster= ; region=
     if [ `grep "|${cld}$" "$M_ROOT/servers.list" | grep -c "^$ip|"` -eq 0 ] ; then
-      # if name passed as ip
+      # maybe name passed as ip
+      if [ `cat "$M_ROOT/servers.list" | cut -d'|' -f4 | grep -c "$ip"` -ne 1 ] ; then
+        find_server --cloud=$cld --ip=$ip --updatelist
+      fi
+    fi
+    # again
+    if [ `grep "|${cld}$" "$M_ROOT/servers.list" | grep -c "^$ip|"` -eq 0 ] ; then
+      # maybe name passed as ip
       if [ `cat "$M_ROOT/servers.list" | cut -d'|' -f4 | grep -c "$ip"` -ne 1 ] ; then
         echo "Unable to find $ip in cloud $cld"
         exit 1
       else
-        ip=`cat "$M_ROOT/servers.list" | grep -v ^$ | grep -v  ^#|grep -v ^[[:space:]]*# | grep "|${cld}$" | cut -d'|' -f1,4 | grep "|${ip}$" | cut -d'|' -f1`
-        [ -z "$ip" ] && echo "Was unable to find IP by server name." && exit 1
+        ip=`cat "$M_ROOT/servers.list" | grep -vE "^#|^[[:space:]]#|^$" | grep "|${cld}$" | cut -d'|' -f1,4 | grep "|${ip}$" | cut -d'|' -f1`
+        if [ -z "$ip" ]; then
+          ip=`cat "$M_ROOT/servers.list" | grep -vE "^#|^[[:space:]]#|^$" | grep "|${cld}$" | cut -d'|' -f1,4 | grep "|${ip}$" | cut -d'|' -f1`
+          if [ -z "$ip" ] && echo "Was unable to find IP by server name." && exit 1
+        fi
       fi
     else
       # cluster is still needed in some cases
diff --git a/deployment/metaexec b/deployment/metaexec
--- a/deployment/metaexec
+++ b/deployment/metaexec
@@ -301,11 +301,14 @@ EOF
   exit 0
 fi
 
+[ -n "$cloud" ] && CLOUD=$cloud
+export CLOUD
+[ -n "$CLOUD" ] && source "$rpath/../../conf/clouds/${CLOUD}.conf"
 source "$M_ROOT/conf/deployment.conf"
 source "$M_ROOT/lib/functions.sh"
 source "$M_ROOT/lib/cloud_functions.sh"
 
-export PATH="$M_ROOT/deployment:$M_ROOT/cloud/${cloud}:$M_ROOT/helpers:$PATH"
+export PATH="$M_ROOT/deployment:$M_ROOT/cloud/common:$M_ROOT/helpers:$PATH"
 [ -n "$task" ] || task=notask
 [ -n "$ignoreipnotpresent" -o -n "$force" -o -n "$ignorenocluster" ] && ignorenocluster="yes" && force="yes"
 [ -n "$user" ] && SSH_REMOTE_USER="$user"
@@ -343,6 +346,8 @@ if [ -n "$ip" ] ; then
     echo "Something's wrong with IP: $ip"
     exit 1
   fi
+  ipcluster=`grep "^$ip|" "$M_ROOT/servers.list" | cut -d'|' -f5`
+  [ -z "$ipcluster" ] && [ -n "$CLOUD" ] && find_server --cloud=$CLOUD --ip=$ip --updatelist
   ipcluster=`grep "^$ip|" "$M_ROOT/servers.list" | cut -d'|' -f5`
   [ -z "$ipcluster" ] && [ -z "$ignoreemptycluster" ] && echo "IP $ip is not present in servers.list or has no cluster defined." && exit 1
   if [ -n "$cluster" ] ; then
@@ -395,15 +400,13 @@ fi
 
 if [ -n "$newserver" ]; then
   
-  [ -n "$cloud" ] || cloud=$CLOUD
-  [ -z "$cloud" ] && echo "Cloud is not defined" && exit 1
-  source "$M_ROOT/conf/clouds/${cloud}.conf"
-  [ $? -ne 0 ] && echo "Error reading cloud $cloud configuration" && exit 1
+  [ -z "$CLOUD" ] && echo "Cloud is not defined" && exit 1
+  [ -z "$CLOUD_PROVIDER" ] && echo "CLOUD_PROVIDER is not defined. Error reading configuration?" && exit 1
   [ -n "$SSHPORT" ] || SSHPORT=22
   [ -z "$NEW_SERVER_START_TRIES" ] && NEW_SERVER_START_TRIES=3
   [ -z "$WAIT_BETWEEN_TRIES" ] && WAIT_BETWEEN_TRIES=30
-  echo "*** Bringing up new server in cloud $cloud"
-  log "bringing up new server in cloud $cloud"
+  echo "*** Bringing up new server in cloud $CLOUD"
+  log "bringing up new server in cloud $CLOUD"
   if [ -z "$test" ]; then
 
     if [ -z "$nolock" ]; then
@@ -429,7 +432,7 @@ if [ -n "$newserver" ]; then
       [[ $res -eq 8 ]] && log "Failed to find out what flavor (server size) to use, define it in clusters.conf, please" && proper_exit 1 415
       [[ $res -eq 1 ]] && log "Something went wrong, unable to add a server to the cluster $cluster"
       if [ -z "$ip" ]; then
-        log "Was unable either to start a cloud server in the cloud $cloud or to get its IP address." && sleep $WAIT_BETWEEN_TRIES && continue
+        log "Was unable either to start a cloud server in the cloud $CLOUD or to get its IP address." && sleep $WAIT_BETWEEN_TRIES && continue
       fi
       [[ `expr $ip : [0-9.]*$` -eq 0 ]] && log "Something's wrong with IP: $ip"
       echo "Something went wrong, check $LOG and fix the problem, next try is in $WAIT_BETWEEN_TRIES seconds"
