shebang fix

diff --git a/deploy/metaexec b/deploy/metaexec
--- a/deploy/metaexec
+++ b/deploy/metaexec
@@ -20,11 +20,79 @@ rpath=${0%/*}
 [ -z "$M_ROOT" ] && M_ROOT=$(cd "$rpath/../" && pwd)
 LOG="$M_ROOT/logs/deploy.log"
 
+find_metascript() {
+if [ ! -e "$ROLES_ROOT/roles/$metascript" ] ; then
+  thescript=${1##*/}
+  therest=${1%/*}
+  [ "_$thescript" == "_$therest" ] && unset therest
+  if [ -z "$therest" ]; then
+    # if both role and flavor are defined
+    if [ -e "$ROLES_ROOT/roles/$role/$flavor/$thescript" ]; then
+      metascript="$role/$flavor/$thescript"
+    else
+      # if role is known, flavor may be bound to it via cluster configuration
+      if [ -n "$role" ]; then
+        roleflavor=`cat "$M_ROOT/conf/clusters.conf" | grep -vE "^[[:space:]]*$|^[[:space:]]*#" | cut -sd'|' -f10,11 | grep "^$role|" | cut -sd'|' -f2`
+        if [ -e "$ROLES_ROOT/roles/$role/$roleflavor/$thescript" ]; then
+          metascript="$role/$roleflavor/$thescript"
+        fi
+        # if not in the configured flavor, then it is in 'common'
+        if [ -e "$ROLES_ROOT/roles/$role/common/$thescript" ]; then
+          metascript="$role/common/$thescript"
+        fi
+      fi
+      if [ -z "$metascript" ]; then
+        # last resort
+        metascript=$(cd "$ROLES_ROOT/roles"; find -name "$thescript")
+      fi
+      if [ -z "$metascript" ]; then
+        echo "metascript \"$metascript\" not found"
+        return 1
+      else
+        if [ `echo "$metascript" | wc -l` -gt 1 ]; then
+          echo "Found more than one scripts with the name ${thescript}:"
+          echo "$metascript"
+          echo "Please narrow the search conditions"
+          return 1
+        fi
+      fi
+    fi
+  else
+    therole=`echo "$therest" | cut -sd'/' -f1`
+    theflavor=`echo "$therest" | cut -sd'/' -f2`
+    if [ -z "$therole" ] && [ -z "$theflavor" ]; then
+      [ -d "$ROLES_ROOT/roles/$therest" ] && therole="$therest" || theflavor="$therest"
+    fi
+    if [ -n "$therole" ]; then
+      metascript=$(cd "$ROLES_ROOT/roles"; find "$therole" -name "$thescript")
+      if [ -z "$metascript" ]; then
+        msfoundinflavor=$(cd "$ROLES_ROOT/roles"; find */"$theflavor" -name "$thescript")
+        echo -e -n "Script $metascript not found "
+        [ -n "$msfoundinflavor" ] && echo -e "\n  Found: $msfoundinflavor"
+        return 1
+      fi
+    else
+      if [ -e "$ROLES_ROOT/roles/$role/$theflavor/$thescript" ]; then
+        metascript="$role/$theflavor/$thescript"
+      else
+        msfoundinflavor=$(cd "$ROLES_ROOT/roles"; find */"$theflavor" -name "$thescript")
+        echo -e -n "Script $metascript not found"
+        [ -n "$msfoundinflavor" ] && echo -e "\n  Found: $msfoundinflavor"
+        return 1
+      fi
+    fi
+  fi
+fi
+}
+
 genline() {
-  metatype=${1%/*}
-  metacond=${1#*/}
-  shift
+  if [ -n "$2" ]; then
+    metatype=${1%/*}
+    metacond=${1#*/}
+    shift
+  fi
   metascript=$@
+  find_metascript "$metascript" || return 1
   case $metatype in
   local)
     echo "local \"$metascript\""
@@ -84,9 +152,10 @@ run_meta() {
   res=0
   [ `grep -c ^"$*"$ "$CURRTASKDIR/log"` -ne 0 ] && echo "Skipping: $*" | tee -a "$LOG" && return 0
   [ -n "$test" -o -n "$dry" ] && dry="--dry"
-  
-  metatype=$1
-  shift
+  if [ -n "$2" ]; then
+    metatype=$1
+    shift
+  fi
   metascript="$*"
   metascript="${metascript%%|*}"
   metarole=`echo "$*" | cut -sd'|' -f2`
@@ -111,74 +180,11 @@ run_meta() {
     P="--ignoreipnotpresent"
   fi
   if [ -n "$metatype" ] && [ -n "$metascript" ] ; then
-    if [ ! -e "$ROLES_ROOT/roles/$metascript" ] ; then
-      thescript=${metascript##*/}
-      therest=${metascript%/*}
-      [ "_$thescript" == "_$therest" ] && unset therest
-      if [ -z "$therest" ]; then
-        # if both role and flavor are defined
-        if [ -e "$ROLES_ROOT/roles/$role/$flavor/$thescript" ]; then
-          metascript="$role/$flavor/$thescript"
-        else
-          # if role is known, flavor may be bound to it via cluster configuration
-          if [ -n "$role" ]; then
-            roleflavor=`cat "$M_ROOT/conf/clusters.conf" | grep -vE "^[[:space:]]*$|^[[:space:]]*#" | cut -sd'|' -f10,11 | grep "^$role|" | cut -sd'|' -f2`
-            if [ -e "$ROLES_ROOT/roles/$role/$roleflavor/$thescript" ]; then
-              metascript="$role/$roleflavor/$thescript"
-            fi
-            # if not in the configured flavor, then it is in 'common'
-            if [ -e "$ROLES_ROOT/roles/$role/common/$thescript" ]; then
-              metascript="$role/common/$thescript"
-            fi
-          fi
-          if [ -z "$metascript" ]; then
-            # last resort
-            metascript=$(cd "$ROLES_ROOT/roles"; find -name "$thescript")
-          fi
-          if [ -z "$metascript" ]; then
-            echo "$metascript not found"
-            res=1
-          else
-            if [ `echo "$metascript" | wc -l` -gt 1 ]; then
-              echo "Found more than one scripts with the name ${thescript}:"
-              echo "$metascript"
-              echo "Please narrow the search conditions"
-              res=1
-            fi
-          fi
-        fi
-      else
-        therole=`echo "$therest" | cut -sd'/' -f1`
-        theflavor=`echo "$therest" | cut -sd'/' -f2`
-        if [ -z "$therole" ] && [ -z "$theflavor" ]; then
-          [ -d "$ROLES_ROOT/roles/$therest" ] && therole="$therest" || theflavor="$therest"
-        fi
-        if [ -n "$therole" ]; then
-          metascript=$(cd "$ROLES_ROOT/roles"; find "$therole" -name "$thescript")
-          if [ -z "$metascript" ]; then
-            msfoundinflavor=$(cd "$ROLES_ROOT/roles"; find */"$theflavor" -name "$thescript")
-            echo -e -n "Script $metascript not found "
-            [ -n "$msfoundinflavor" ] && echo -e "\n  Found: $msfoundinflavor"
-            res=1
-          fi
-        else
-          if [ -e "$ROLES_ROOT/roles/$role/$theflavor/$thescript" ]; then
-            metascript="$role/$theflavor/$thescript"
-          else
-            msfoundinflavor=$(cd "$ROLES_ROOT/roles"; find */"$theflavor" -name "$thescript")
-            echo -e -n "Script $metascript not found"
-            [ -n "$msfoundinflavor" ] && echo -e "\n  Found: $msfoundinflavor"
-            res=1
-          fi
-        fi
-      fi
-    fi
-    if [ $res -eq 0 ]; then
-      [ -e "$CURRTASKDIR/$metascript" ] && rm "$CURRTASKDIR/$metascript"
-      [ -e "$CURRTASKDIR/$metascript.var" ] && rm "$CURRTASKDIR/${metascript}.var"
-      deploy.run --type=$metatype --file=$metascript --ip=$ip --key="$KEY" --cluster="$cluster" --role="$role" --flavor="$flavor" --timestamp=$timestampact --task="$task" $dry $V $D $I $F $P $SU
-      res=$?
-    fi
+    find_metascript "$metascript" || return 1
+    [ -e "$CURRTASKDIR/$metascript" ] && rm "$CURRTASKDIR/$metascript"
+    [ -e "$CURRTASKDIR/$metascript.var" ] && rm "$CURRTASKDIR/${metascript}.var"
+    deploy.run --type=$metatype --file=$metascript --ip=$ip --key="$KEY" --cluster="$cluster" --role="$role" --flavor="$flavor" --timestamp=$timestampact --task="$task" $dry $V $D $I $F $P $SU
+    res=$?
     if [ -n "$verbose" ] ; then
       if [ -n "$use_color" ] ; then
         [ $res -eq 0 ] && printf "\033[01;32mSuccess\033[0m\n\n" || printf "\033[01;31mError\033[0m\n\n"
@@ -213,7 +219,6 @@ meta_exit() {
   if [ -e "$CURRTASKDIR/messages" ]; then
     cat "$CURRTASKDIR/messages"
   fi
-  # the best place for this seems to be here
   [ -z "$KEEP_DEPLOYTMP" ] && KEEP_DEPLOYTMP=30
   find "$M_DEPL_WORK_DIR" -maxdepth 1 -mindepth 1 -type d -mtime +$KEEP_DEPLOYTMP -exec rm -rf {} \;
   fi
@@ -610,11 +615,6 @@ done
 
 
 if [ -z "$list" ]; then
-
-  #[ -z "$SCP" ] && echo "SCP not found!" && exit 1
-
-  #${rpath}/testmeta --flavor=$flavor --task=$task --role=$role || exit 1
-
   if [ -z "$timestamp" ]; then
   ## Saving arguments to make re-run simpler
     $debug && log "saving command-line arguments for possible repeat of the sequence"
@@ -628,7 +628,6 @@ if [ -z "$list" ]; then
       echo "ip=\"$ip\"" >> "$CURRTASKDIR/ARGV"
     fi
   fi
-  ##
 fi
 echo
 rm "$CURRTASKDIR"/meta "$CURRTASKDIR"/meta.pre 2>/dev/null
