passing ip when multiple nodes are deployed

diff --git a/deploy/metaexec b/deploy/metaexec
--- a/deploy/metaexec
+++ b/deploy/metaexec
@@ -702,9 +702,9 @@ if [ -n "$ip" ]; then
   $SSH -p $SSHPORT -i "$KEY" -o "StrictHostKeyChecking=no" -o "ConnectTimeout=10" -o "PasswordAuthentication=no" "$SSH_REMOTE_USER"@"$ip" echo -n
   [ $? -ne 0 ] && echo "Unable to connect to node $ip" && meta_exit 100 702
 else
-  for ip in `get_ips --cluster=$cluster`; do
-    $SSH -p $SSHPORT -i "$KEY" -o "StrictHostKeyChecking=no" -o "ConnectTimeout=10" -o "PasswordAuthentication=no" "$SSH_REMOTE_USER"@"$ip" echo -n
-    [ $? -ne 0 ] && echo "Unable to connect to node $ip in cluster $cluster" && meta_exit 100 705
+  for checkip in `get_ips --cluster=$cluster`; do
+    $SSH -p $SSHPORT -i "$KEY" -o "StrictHostKeyChecking=no" -o "ConnectTimeout=10" -o "PasswordAuthentication=no" "$SSH_REMOTE_USER"@"$checkip" echo -n
+    [ $? -ne 0 ] && echo "Unable to connect to node $checkip in cluster $cluster" && meta_exit 100 705
   done
 fi
  
