bits and new files monitor

diff --git a/deployment/deploy_file b/deployment/deploy_file
--- a/deployment/deploy_file
+++ b/deployment/deploy_file
@@ -237,17 +237,17 @@ if [ -z "$cluster" ] ; then
 fi
 [ -n "$all" -o "$cluster" == "all" ] && cluster=`cat "${rpath}/../conf/clusters.conf" | grep -v ^# | grep -v ^$ | cut -d'|' -f1`
 #[ `cat "${rpath}/../servers.list" | grep -v ^$ | grep -v  ^# | grep -v ^[[:space:]]*# | cut -d'|' -f5 | grep -c "$cluster"` -eq 0 ] && [ -z "$test" -a -z "$dry" ] && echo "${rcommand}: no servers found in cluster $cluster" && exit 1
-[ -z "$flavor" ] && flavor=`cat "${rpath}/../conf/clusters.conf" | grep -v ^# | grep -v ^$ | cut -d'|' -f10,11 | grep ^${role}\| | cut -d'|' -f2`
-[ -n "$verbose" ] && echo "### Reading configuration from ${ROLES_ROOT}/${role}/role.conf"
+[ -z "$flavor" ] && flavor=`cat "$rpath/../conf/clusters.conf" | grep -v ^# | grep -v ^$ | cut -d'|' -f10,11 | grep ^$role\| | cut -d'|' -f2`
+[ -n "$verbose" ] && echo "### Reading configuration from $ROLES_ROOT/$role/role.conf"
 
 find_source
 # fullfrom and realrole are now defined
-tmpfile=${M_TEMP}/deployment/`echo $fullfrom | tr '/' '_'`
+tmpfile="$M_TEMP/deployment/`echo $fullfrom | tr '/' '_'`"
 rm -f "$tmpfile" "${tmpfile}.orig" 2>/dev/null
   
-[ -f "${ROLES_ROOT}/common/role.conf" ] && store_vars "${ROLES_ROOT}/common/role.conf"
-[ -n "$realrole" ] && [ -f "${ROLES_ROOT}/${realrole}/role.conf" ] && store_vars "${ROLES_ROOT}/${realrole}/role.conf"
-[ -f "${ROLES_ROOT}/${role}/role.conf" ] && store_vars "${ROLES_ROOT}/${role}/role.conf"
+[ -f "$ROLES_ROOT/common/role.conf" ] && store_vars "$ROLES_ROOT/common/role.conf"
+[ -n "$realrole" ] && [ -f "$ROLES_ROOT/$realrole/role.conf" ] && store_vars "$ROLES_ROOT/$realrole/role.conf"
+[ -f "$ROLES_ROOT/$role/role.conf" ] && store_vars "$ROLES_ROOT/$role/role.conf"
 
 if [ -z "$local" ]; then
 
@@ -257,7 +257,7 @@ if [ -z "$local" ]; then
     # some ip, just to fill the vars
     export ip="10.10.10.10"
     prepare_file
-    cat "${tmpfile}"
+    cat "$tmpfile"
   else
     if [ -n "$ip" ] ; then
     # Single destination: region, cluster, cloud are ignored
@@ -266,24 +266,24 @@ if [ -z "$local" ]; then
         echo "${tmpfile##*/}...  "
         cp -up "$tmpfile" "$to" && echo "Success"
       else
-        KEY=`cat "${rpath}/../servers.list" | grep ^$ip\| | cut -d'|' -f2`
-        REGION=`cat "${rpath}/../servers.list" | grep ^$ip\| | cut -d'|' -f3`
-        CLUSTER=`cat "${rpath}/../servers.list" | grep ^$ip\| | cut -d'|' -f5`
-        [ -f "${rpath}/../keys/$KEY" ] || KEY="${KEY}.pem"
-        [ -f "${rpath}/../keys/$KEY" ] || (echo "${rcommand}: key not found for IP $ip" && exit 1)
-        if [ `$SSH -i "${rpath}/../keys/$KEY" $ip test -d "$to"` ] ; then
+        KEY=`cat "$rpath/../servers.list" | grep ^$ip\| | cut -d'|' -f2`
+        REGION=`cat "$rpath/../servers.list" | grep ^$ip\| | cut -d'|' -f3`
+        CLUSTER=`cat "$rpath/../servers.list" | grep ^$ip\| | cut -d'|' -f5`
+        [ -f "$rpath/../keys/$KEY" ] || KEY="${KEY}.pem"
+        [ -f "$rpath/../keys/$KEY" ] || (echo "${rcommand}: key not found for IP $ip" && exit 1)
+        if [ `$SSH -i "$rpath/../keys/$KEY" $ip test -d "$to"` ] ; then
           to=${to%/}/${from##*/}
-        elif [ ! `$SSH -i "${rpath}/../keys/$KEY" $ip test -d "${to%/*}"` ] ; then
-          $SSH -i "${rpath}/../keys/$KEY" $ip install -d "${to%/*}"
+        elif [ ! `$SSH -i "$rpath/../keys/$KEY" $ip test -d "${to%/*}"` ] ; then
+          $SSH -i "$rpath/../keys/$KEY" $ip install -d "${to%/*}"
         fi
         prepare_file
         echo "${tmpfile##*/}...  "
-        cloudsync --ip=$ip "$tmpfile" "${to}"
+        cloudsync --ip=$ip "$tmpfile" "$to"
       fi
     else
     # Multiple destinations
       for cl in `echo -e $cluster | tr ',' '\n'` ; do
-        for server in `cat "${rpath}/../servers.list" | grep -v ^$ | grep -v  ^#|grep -v ^[[:space:]]*#` ; do
+        for server in `cat "$rpath/../servers.list" | grep -v ^$ | grep -v  ^#|grep -v ^[[:space:]]*#` ; do
           IP=${server%%|*}
           KEY=`echo $server | cut -d'|' -f2`
           if [ -n "$region" ] ; then
@@ -304,15 +304,15 @@ if [ -z "$local" ]; then
             echo "${tmpfile##*/}...  "
             cp -up "$tmpfile" "$to" && echo "Success"
           else
-            [ -f "${rpath}/../keys/$KEY" ] || KEY="${KEY}.pem"
-            [ -f "${rpath}/../keys/$KEY" ] || (echo "${rcommand}: key not found for IP $IP" && continue)
-            if [ `$SSH -i "${rpath}/../keys/$KEY" $IP test -d "$to"` ] ; then
+            [ -f "$rpath/../keys/$KEY" ] || KEY="${KEY}.pem"
+            [ -f "$rpath/../keys/$KEY" ] || (echo "${rcommand}: key not found for IP $IP" && continue)
+            if [ `$SSH -i "$rpath/../keys/$KEY" $IP test -d "$to"` ] ; then
               to=${to%/}/${from##*/}
             fi
             ip=$IP
             prepare_file
             echo "${tmpfile##*/}...  "
-            cloudsync --ip=$IP "$tmpfile" "${to}"
+            cloudsync --ip=$IP "$tmpfile" "$to"
           fi
         done
       done
@@ -321,6 +321,9 @@ if [ -z "$local" ]; then
 else
   prepare_file
   echo "${tmpfile##*/}...  "
+  if [ -d "$to" ] ; then
+    to=${to%/}/${from##*/}
+  fi
   mv "$tmpfile" "$to" && echo "Success"
 fi
 rm -f "$tmpfile"*
