bits

diff --git a/deployment/deploy_file b/deployment/deploy_file
--- a/deployment/deploy_file
+++ b/deployment/deploy_file
@@ -22,6 +22,7 @@ rpath=${0%/*}
 [ -f "/sbin/ifconfig" ] && IFCFG=/sbin/ifconfig || IFCFG=`which ifconfig 2>/dev/null`
 SSH=`which ssh 2>/dev/null`
 [ -z "$SSH" ] && echo "SSH utility not found, exiting" && exit 1
+RSYNC=`which rsync 2>/dev/null`
 possible_options="cluster help region verbose flavor"
 commflag=0
 for s_option in "${@}"
@@ -85,16 +86,16 @@ IFS='
 '
 if [ "X$command" != "X" ] ; then
   from=${command%% *}
-  [ -f "$from" ] || (echo "$from is not a file or file not found" && exit 1)
+  [ -f "${ROLES_ROOT}/${cluster}/${flavor}/files/$from" ] || (echo "$from is not a file or file not found" && exit 1)
   fullfrom="${ROLES_ROOT}/${cluster}/${flavor}/files/${from}"
   tmpfile=/tmp/m_script/deployment/`echo $fullfrom | sed 's|/|_|g'`
   rm -f "$tmpfile"
-  for LINE in `cat "$from"` ; do
-    echo "${LINE}" >> "$tmpfile"
+  for LINE in `cat "$fullfrom"` ; do
+    eval echo $LINE | sed "s|\%\(.*\)\%|\1|" >> "$tmpfile"
   done
   to=${command#* }
   if [ -d "$to" ] ; then
-    to=${to}/${from##*/}
+    to=${to%/}/${from##*/}
   fi
   [ -n "$verbose" ] && echo "### Deploying $from to $to"
   for server in `cat "${rpath}/../servers.list" | grep -v ^$ | grep -v  ^#|grep -v ^[[:space:]]*#` ; do
@@ -116,7 +117,7 @@ if [ "X$command" != "X" ] ; then
     if [ `echo $IP | grep -c "$localip"` -ne 0 ] ; then
       cp -up $tmpfile $to
     else
-      $RSYNC ${r} -e "$SSH -i ${rpath}/../../keys/${KEY}.pem -o StrictHostKeyChecking=no" $tmpfile ${IP}:${to}
+      $RSYNC -e "$SSH -i ${rpath}/../../keys/${KEY}.pem -o StrictHostKeyChecking=no" $tmpfile ${IP}:${to} || `which scp` -i ${rpath}/../../keys/${KEY}.pem -o StrictHostKeyChecking=no $tmpfile ${IP}:${to}
     fi
   done
 fi
