bits

diff --git a/deployment/deploy_file b/deployment/deploy_file
--- a/deployment/deploy_file
+++ b/deployment/deploy_file
@@ -115,19 +115,26 @@ if [ "X$command" != "X" ] ; then
   fi
   [ -z "$flavor" ] && flavor=`cat "${rpath}/../conf/clusters.conf" | grep -v ^# | grep -v ^$ | cut -d'|' -f10,11 | grep ^${role}\| | cut -d'|' -f2`
   [ -n "$verbose" ] && echo "### Reading configuration from ${ROLES_ROOT}/${role}/role.conf"
-  [ -f "${ROLES_ROOT}/${role}/role.conf" ] && store_vars "${ROLES_ROOT}/${role}/role.conf" && source "${tmpfile}.var"
   if [ -f "$from" ] ; then
     fullfrom=$from
   else
     if [ -f "${ROLES_ROOT}/${role}/${flavor}/files/$from" ] ; then
       fullfrom="${ROLES_ROOT}/${role}/${flavor}/files/${from}"
     else
-      echo "Neither $from nor ${ROLES_ROOT}/${role}/${flavor}/files/$from is not a file or file not found"
-      exit 1
+      echo -n "Neither $from nor ${ROLES_ROOT}/${role}/${flavor}/files/$from is found, guessing flavor=$DEFAULT_ROLE ... "
+      if [ -f "${ROLES_ROOT}/${role}/${DEFAULT_ROLE}/files/$from" ] ; then
+        echo "found"
+        fullfrom="${ROLES_ROOT}/${role}/${DEFAULT_ROLE}/files/${from}"
+      else
+        echo "not found, exiting"
+        exit 1
+      fi
     fi
   fi
   tmpfile=${TMPDIR}/deployment/`echo $fullfrom | sed 's|/|_|g'`
   rm -f "$tmpfile" 2>/dev/null
+  [ -f "${ROLES_ROOT}/${role}/role.conf" ] && store_vars "${ROLES_ROOT}/${role}/role.conf" && source "${tmpfile}.var"
+  
 
   cat "$fullfrom" | sed "s|\\$|\\\\$|g;s|\%\(.*\)\%|$\{\1\}|g" | \
   sed 's|"|\\\"|g' | \
diff --git a/deployment/metaexec b/deployment/metaexec
--- a/deployment/metaexec
+++ b/deployment/metaexec
@@ -159,7 +159,7 @@ if [ -n "$ip" ] ; then
     cluster=$ipcluster
   fi
 else
-  # Cluster must be defined! If it is still not, we'll find it using role
+  # Cluster must be defined! If it is still not, we'll find it using the role
   if [ -z "$cluster" ] ; then
     if [ -z "$role" ] ; then
       if [ -n "$M_ROLE" ] ; then
@@ -168,7 +168,7 @@ else
       fi
       # Still no cluster??
       if [ -z "$cluster" ] ; then
-        echo "None of ip, role, cluster is defined."
+        echo "Unable to find what cluster to use."
         exit 1
       fi
     fi
@@ -228,10 +228,12 @@ if [ `echo $ip | grep -c "$localip"` -eq 0 ] ; then
   [ -z "$KEY" ] && echo "Either cluster ${cluster} or its key not found in ${rpath}/../conf/clusters.conf" && exit 1
   [ -z "$SSH" ] && echo "SSH client not found!" && exit 1
   [ -f "${rpath}/../keys/${KEY}" ] || KEY=${KEY}.pem
-  [ -f "${rpath}/../keys/${KEY}" ] || (echo "Key $KEY not found" ; exit 1)
+  [ ! -f "${rpath}/../keys/${KEY}" ] && echo "Key $KEY not found" && exit 1
   #SSH="$SSH -i \"${rpath}/../keys/${KEY}\" -o StrictHostKeyChecking=no"
-  $SSH -i "${rpath}/../keys/${KEY}" -o StrictHostKeyChecking=no $ip pwd >/dev/null
-  [ $? -ne 0 ] && echo "Unable to login to the server $ip" && exit 1
+  if [ -z "$test" -a -z "$list" ] ; then
+    $SSH -i "${rpath}/../keys/${KEY}" -o StrictHostKeyChecking=no $ip pwd >/dev/null
+    [ $? -ne 0 ] && echo "Unable to login to the server $ip" && exit 1
+  fi
   #[ -z "$SCP" ] && echo "SCP not found!" && exit 1
 
   #${rpath}/testmeta --flavor=$flavor --task=$task --role=$role || exit 1
