fix

diff --git a/deployment/deploy_file b/deployment/deploy_file
--- a/deployment/deploy_file
+++ b/deployment/deploy_file
@@ -236,78 +236,78 @@ if [ "X$command" != "X" ] ; then
   [ -z "$flavor" ] && flavor=`cat "${rpath}/../conf/clusters.conf" | grep -v ^# | grep -v ^$ | cut -d'|' -f10,11 | grep ^${role}\| | cut -d'|' -f2`
   [ -n "$verbose" ] && echo "### Reading configuration from ${ROLES_ROOT}/${role}/role.conf"
 
-find_source
-# fullfrom and realrole are now defined
-tmpfile=${TMPDIR}/deployment/`echo $fullfrom | tr '/' '_'`
-rm -f "$tmpfile" "${tmpfile}.orig" 2>/dev/null
-  
-[ -f "${ROLES_ROOT}/common/role.conf" ] && store_vars "${ROLES_ROOT}/common/role.conf"
-[ -n "$realrole" ] && [ -f "${ROLES_ROOT}/${realrole}/role.conf" ] && store_vars "${ROLES_ROOT}/${realrole}/role.conf"
-[ -f "${ROLES_ROOT}/${role}/role.conf" ] && store_vars "${ROLES_ROOT}/${role}/role.conf"
+  find_source
+  # fullfrom and realrole are now defined
+  tmpfile=${TMPDIR}/deployment/`echo $fullfrom | tr '/' '_'`
+  rm -f "$tmpfile" "${tmpfile}.orig" 2>/dev/null
+    
+  [ -f "${ROLES_ROOT}/common/role.conf" ] && store_vars "${ROLES_ROOT}/common/role.conf"
+  [ -n "$realrole" ] && [ -f "${ROLES_ROOT}/${realrole}/role.conf" ] && store_vars "${ROLES_ROOT}/${realrole}/role.conf"
+  [ -f "${ROLES_ROOT}/${role}/role.conf" ] && store_vars "${ROLES_ROOT}/${role}/role.conf"
 
-to=${command#* }
-[ -n "$verbose" ] && echo "### Deploying file $from to $to"
+  to=${command#* }
+  [ -n "$verbose" ] && echo "### Deploying file $from to $to"
 
-if [ -n "$test" -o -n "$dry" ] ; then
-  # some ip, just to fill the vars
-  export ip="10.10.10.10"
-  prepare_file
-  cat "${tmpfile}"
-else
-  if [ -n "$ip" ] ; then
-  # Single destination: region, cluster, cloud are ignored
-    if [ `echo $ip | grep -c "$localip"` -ne 0 ] ; then
-      cp -up $tmpfile $to
-    else
-      KEY=`cat "${rpath}/../servers.list" | grep ^$ip\| | cut -d'|' -f2`
-      REGION=`cat "${rpath}/../servers.list" | grep ^$ip\| | cut -d'|' -f3`
-      CLUSTER=`cat "${rpath}/../servers.list" | grep ^$ip\| | cut -d'|' -f5`
-      [ -f "${rpath}/../keys/$KEY" ] || KEY="${KEY}.pem"
-      [ -f "${rpath}/../keys/$KEY" ] || (echo "${rcommand}: key not found for IP $ip" && exit 1)
-      if [ `$SSH -i "${rpath}/../keys/$KEY" $ip test -d "$to"` ] ; then
-        to=${to%/}/${from##*/}
-      elif [ ! `$SSH -i "${rpath}/../keys/$KEY" $ip test -d "${to%/*}"` ] ; then
-        $SSH -i "${rpath}/../keys/$KEY" $ip install -d "${to%/*}"
-      fi
-      prepare_file
-      cloudsync --ip=$ip "$tmpfile" "${to}"
-    fi
+  if [ -n "$test" -o -n "$dry" ] ; then
+    # some ip, just to fill the vars
+    export ip="10.10.10.10"
+    prepare_file
+    cat "${tmpfile}"
   else
-  # Multiple destinations
-    for cl in `echo $cluster | tr ',' ' '` ; do
-      for server in `cat "${rpath}/../servers.list" | grep -v ^$ | grep -v  ^#|grep -v ^[[:space:]]*#` ; do
-        IP=${server%%|*}
-        KEY=`echo $server | cut -d'|' -f2`
-        if [ -n "$region" ] ; then
-          REGION=`echo $server | cut -d'|' -f3`
-          [ "X$REGION" == "X$region" ] || continue
+    if [ -n "$ip" ] ; then
+    # Single destination: region, cluster, cloud are ignored
+      if [ `echo $ip | grep -c "$localip"` -ne 0 ] ; then
+        cp -up $tmpfile $to
+      else
+        KEY=`cat "${rpath}/../servers.list" | grep ^$ip\| | cut -d'|' -f2`
+        REGION=`cat "${rpath}/../servers.list" | grep ^$ip\| | cut -d'|' -f3`
+        CLUSTER=`cat "${rpath}/../servers.list" | grep ^$ip\| | cut -d'|' -f5`
+        [ -f "${rpath}/../keys/$KEY" ] || KEY="${KEY}.pem"
+        [ -f "${rpath}/../keys/$KEY" ] || (echo "${rcommand}: key not found for IP $ip" && exit 1)
+        if [ `$SSH -i "${rpath}/../keys/$KEY" $ip test -d "$to"` ] ; then
+          to=${to%/}/${from##*/}
+        elif [ ! `$SSH -i "${rpath}/../keys/$KEY" $ip test -d "${to%/*}"` ] ; then
+          $SSH -i "${rpath}/../keys/$KEY" $ip install -d "${to%/*}"
         fi
-        if [ -n "$cl" ] ; then
-          CLUSTER=`echo $server | cut -d'|' -f5`
-          [ "X$CLUSTER" == "X$cl" ] || continue
-        fi
-        if [ "X$verbose" == "Xyes" ] ; then
-          echo
-          echo "### Server: $server"
-          echo
-        fi
-        if [ `echo $IP | grep -c "$localip"` -ne 0 ] ; then
-          cp -up $tmpfile $to
-        else
-          [ -f "${rpath}/../keys/$KEY" ] || KEY="${KEY}.pem"
-          [ -f "${rpath}/../keys/$KEY" ] || (echo "${rcommand}: key not found for IP $IP" && continue)
-          if [ `$SSH -i "${rpath}/../keys/$KEY" $IP test -d "$to"` ] ; then
-            to=${to%/}/${from##*/}
+        prepare_file
+        cloudsync --ip=$ip "$tmpfile" "${to}"
+      fi
+    else
+    # Multiple destinations
+      for cl in `echo $cluster | tr ',' ' '` ; do
+        for server in `cat "${rpath}/../servers.list" | grep -v ^$ | grep -v  ^#|grep -v ^[[:space:]]*#` ; do
+          IP=${server%%|*}
+          KEY=`echo $server | cut -d'|' -f2`
+          if [ -n "$region" ] ; then
+            REGION=`echo $server | cut -d'|' -f3`
+            [ "X$REGION" == "X$region" ] || continue
           fi
-          ip=$IP
-          prepare_file
-          cloudsync --ip=$IP "$tmpfile" "${to}"
-        fi
+          if [ -n "$cl" ] ; then
+            CLUSTER=`echo $server | cut -d'|' -f5`
+            [ "X$CLUSTER" == "X$cl" ] || continue
+          fi
+          if [ "X$verbose" == "Xyes" ] ; then
+            echo
+            echo "### Server: $server"
+            echo
+          fi
+          if [ `echo $IP | grep -c "$localip"` -ne 0 ] ; then
+            cp -up $tmpfile $to
+          else
+            [ -f "${rpath}/../keys/$KEY" ] || KEY="${KEY}.pem"
+            [ -f "${rpath}/../keys/$KEY" ] || (echo "${rcommand}: key not found for IP $IP" && continue)
+            if [ `$SSH -i "${rpath}/../keys/$KEY" $IP test -d "$to"` ] ; then
+              to=${to%/}/${from##*/}
+            fi
+            ip=$IP
+            prepare_file
+            cloudsync --ip=$IP "$tmpfile" "${to}"
+          fi
+        done
       done
-    done
+    fi
   fi
+  rm -f "$tmpfile"*
 fi
-rm -f "$tmpfile"*
-
 IFS=$IFS1
 
