Bugfix

diff --git a/deployment/deploy_file b/deployment/deploy_file
--- a/deployment/deploy_file
+++ b/deployment/deploy_file
@@ -78,6 +78,9 @@ if [ "X$help" == "Xyes" ] ; then
 fi
 [ -n "$flavor" ] || flavor=common
 source "${rpath}/../conf/deployment.conf"
+M_ROOT=$(cd "${rpath}/../" && pwd)
+export PATH=${M_ROOT}/deployment:${M_ROOT}/cloud:${M_ROOT}/cloud/ec2:${M_ROOT}/helpers:${PATH}
+source "${rpath}/../conf/deployment.conf"
 source "${ROLES_ROOT}/${cluster}/role.conf"
 [ "X$IFCFG" != "X" ] && localip=`$IFCFG | sed '/inet\ /!d;s/.*r://;s/\ .*//' | grep -v '127.0.0.1'` || localip="ifconfig_not_found"
 install -d /tmp/m_script/deployment/
@@ -86,7 +89,7 @@ IFS='
 '
 if [ "X$command" != "X" ] ; then
   from=${command%% *}
-  [ -f "${ROLES_ROOT}/${cluster}/${flavor}/files/$from" ] || (echo "$from is not a file or file not found" && exit 1)
+  [ -f "${ROLES_ROOT}/${cluster}/${flavor}/files/$from" ] || (echo "${ROLES_ROOT}/${cluster}/${flavor}/files/$from is not a file or file not found" && exit 1)
   fullfrom="${ROLES_ROOT}/${cluster}/${flavor}/files/${from}"
   tmpfile=/tmp/m_script/deployment/`echo $fullfrom | sed 's|/|_|g'`
   rm -f "$tmpfile"
@@ -117,7 +120,7 @@ if [ "X$command" != "X" ] ; then
     if [ `echo $IP | grep -c "$localip"` -ne 0 ] ; then
       cp -up $tmpfile $to
     else
-      $RSYNC -e "$SSH -i ${rpath}/../../keys/${KEY}.pem -o StrictHostKeyChecking=no" $tmpfile ${IP}:${to} || `which scp` -i ${rpath}/../../keys/${KEY}.pem -o StrictHostKeyChecking=no $tmpfile ${IP}:${to}
+      $RSYNC -e "$SSH -i ${rpath}/../keys/${KEY}.pem -o StrictHostKeyChecking=no" $tmpfile ${IP}:${to} || `which scp` -i ${rpath}/../keys/${KEY}.pem -o StrictHostKeyChecking=no $tmpfile ${IP}:${to}
     fi
   done
 fi
