cluster replaced with role

diff --git a/deployment/deploy_file b/deployment/deploy_file
--- a/deployment/deploy_file
+++ b/deployment/deploy_file
@@ -23,7 +23,7 @@ rpath=${0%/*}
 SSH=`which ssh 2>/dev/null`
 [ -z "$SSH" ] && echo "SSH utility not found, exiting" && exit 1
 RSYNC=`which rsync 2>/dev/null`
-possible_options="cluster help region verbose flavor ip"
+possible_options="cluster help region verbose flavor role ip"
 commflag=0
 for s_option in "${@}"
 do
@@ -81,7 +81,7 @@ source "${rpath}/../conf/deployment.conf"
 M_ROOT=$(cd "${rpath}/../" && pwd)
 export PATH=${M_ROOT}/deployment:${M_ROOT}/cloud:${M_ROOT}/cloud/ec2:${M_ROOT}/helpers:${PATH}
 source "${rpath}/../conf/deployment.conf"
-source "${ROLES_ROOT}/${cluster}/role.conf"
+source "${ROLES_ROOT}/${role}/role.conf"
 [ "X$IFCFG" != "X" ] && localip=`$IFCFG | sed '/inet\ /!d;s/.*r://;s/\ .*//' | grep -v '127.0.0.1'` || localip="ifconfig_not_found"
 install -d /tmp/m_script/deployment/
 IFS1=$IFS
@@ -89,8 +89,8 @@ IFS='
 '
 if [ "X$command" != "X" ] ; then
   from=${command%% *}
-  [ -f "${ROLES_ROOT}/${cluster}/${flavor}/files/$from" ] || (echo "${ROLES_ROOT}/${cluster}/${flavor}/files/$from is not a file or file not found" && exit 1)
-  fullfrom="${ROLES_ROOT}/${cluster}/${flavor}/files/${from}"
+  [ -f "${ROLES_ROOT}/${role}/${flavor}/files/$from" ] || (echo "${ROLES_ROOT}/${role}/${flavor}/files/$from is not a file or file not found" && exit 1)
+  fullfrom="${ROLES_ROOT}/${role}/${flavor}/files/${from}"
   tmpfile=/tmp/m_script/deployment/`echo $fullfrom | sed 's|/|_|g'`
   rm -f "$tmpfile" 2>/dev/null
   for LINE in `cat "$fullfrom"` ; do
