multiple clusters support for deploy_file

diff --git a/deployment/deploy_file b/deployment/deploy_file
--- a/deployment/deploy_file
+++ b/deployment/deploy_file
@@ -130,32 +130,34 @@ if [ "X$command" != "X" ] ; then
   if [ -n "$test" -o -n "$dry" ] ; then
     cat "${tmpfile}"
   else
-    for server in `cat "${rpath}/../servers.list" | grep -v ^$ | grep -v  ^#|grep -v ^[[:space:]]*#` ; do
-      IP=${server%%|*}
-      if [ -n "$ip" ] ; then
-        [ "X$ip" == "X$IP" ] || continue
-      fi
-      KEY=`echo $server | cut -d'|' -f2`
-      if [ -n "$region" ] ; then
-        REGION=`echo $server | cut -d'|' -f3`
-        [ "X$REGION" == "X$region" ] || continue
-      fi
-      if [ -n "$cluster" ] ; then
-        CLUSTER=`echo $server | cut -d'|' -f5`
-        [ "X$CLUSTER" == "X$cluster" ] || continue
-      fi
-      if [ "X$verbose" == "Xyes" ] ; then
-        echo
-        echo "### Server: $server"
-        echo
-      fi
-      if [ `echo $IP | grep -c "$localip"` -ne 0 ] ; then
-        cp -up $tmpfile $to
-      else
-        [ -f "${rpath}/../keys/$KEY" ] || KEY="${KEY}.pem"
-        [ -f "${rpath}/../keys/$KEY" ] || (echo "Key not found for IP $IP" && continue)
-        cloudsync --ip=$IP "$tmpfile" "${to}"
-      fi
+    for cl in `echo $cluster | tr ',' ' '` ; do
+      for server in `cat "${rpath}/../servers.list" | grep -v ^$ | grep -v  ^#|grep -v ^[[:space:]]*#` ; do
+        IP=${server%%|*}
+        if [ -n "$ip" ] ; then
+          [ "X$ip" == "X$IP" ] || continue
+        fi
+        KEY=`echo $server | cut -d'|' -f2`
+        if [ -n "$region" ] ; then
+          REGION=`echo $server | cut -d'|' -f3`
+          [ "X$REGION" == "X$region" ] || continue
+        fi
+        if [ -n "$cl" ] ; then
+          CLUSTER=`echo $server | cut -d'|' -f5`
+          [ "X$CLUSTER" == "X$cl" ] || continue
+        fi
+        if [ "X$verbose" == "Xyes" ] ; then
+          echo
+          echo "### Server: $server"
+          echo
+        fi
+        if [ `echo $IP | grep -c "$localip"` -ne 0 ] ; then
+          cp -up $tmpfile $to
+        else
+          [ -f "${rpath}/../keys/$KEY" ] || KEY="${KEY}.pem"
+          [ -f "${rpath}/../keys/$KEY" ] || (echo "Key not found for IP $IP" && continue)
+          cloudsync --ip=$IP "$tmpfile" "${to}"
+        fi
+      done
     done
   fi
   rm -f "$tmpfile"*
