deploy_file, one more try

diff --git a/deployment/deploy_file b/deployment/deploy_file
--- a/deployment/deploy_file
+++ b/deployment/deploy_file
@@ -23,7 +23,7 @@ rpath=${0%/*}
 SSH=`which ssh 2>/dev/null`
 [ -z "$SSH" ] && echo "SSH utility not found, exiting" && exit 1
 RSYNC=`which rsync 2>/dev/null`
-possible_options="cluster help region verbose flavor role ip"
+possible_options="cluster help region verbose flavor role ip test dry"
 commflag=0
 for s_option in "${@}"
 do
@@ -100,42 +100,51 @@ if [ "X$command" != "X" ] ; then
   fi
   tmpfile=/tmp/m_script/deployment/`echo $fullfrom | sed 's|/|_|g'`
   rm -f "$tmpfile" 2>/dev/null
-  for LINE in `cat "$fullfrom | sed 's|$| |g'"` ; do
-    echo $LINE | sed "s|\%\(.*\)\%|\`echo \$\1\`|" >> "${tmpfile}.orig"
-  done
-  for LINE in `cat "${tmpfile}.orig"` ; do ELINE=$(echo "$LINE" | sed 's|"|\\\"|g' | sed "s|'|\\\'|g" | sed 's_|_\\\|_g' | sed 's|`|\\\`|g') ; a=`eval "echo $ELINE"` ; [ $? -eq 0 ] && [ -n "$a" ] && echo "$a" >> "${tmpfile}" || echo "$LINE" >> "${tmpfile}" ; done
+
+  cat "$fullfrom" | sed "s|\$|\\\$|g;s|\%\(.*\)\%|$\1|g" | \
+  sed 's|"|\\\"|g;s|&|\\\&|g;s|<|\\\<|g;s|>|\\\>|g;s|(|\\\(|g;s|)|\\\)|g' | \
+  sed "s|'|\\\'|g" | \
+  sed 's_|_\\\|_g' | \
+  sed 's|`|\\\`|g;s|\;|\\\;|g' >> "${tmpfile}.orig"
+
+  for LINE in `cat "${tmpfile}.orig"` ; do a=`eval "echo $LINE"` ; [ $? -eq 0 ] && [ -n "$a" ] && echo "$a" >> "${tmpfile}" || echo "$LINE" >> "${tmpfile}" ; done
   to=${command#* }
   if [ -d "$to" ] ; then
     to=${to%/}/${from##*/}
   fi
   [ -n "$verbose" ] && echo "### Deploying file $from to $to"
-  for server in `cat "${rpath}/../servers.list" | grep -v ^$ | grep -v  ^#|grep -v ^[[:space:]]*#` ; do
-    IP=${server%%|*}
-    if [ -n "$ip" ] ; then
-      [ "X$ip" == "X$IP" ] || continue
-    fi
-    KEY=`echo $server | cut -d'|' -f2`
-    if [ -n "$region" ] ; then
-      REGION=`echo $server | cut -d'|' -f3`
-      [ "X$REGION" == "X$region" ] || continue
-    fi
-    if [ -n "$cluster" ] ; then
-      CLUSTER=`echo $server | cut -d'|' -f5`
-      [ "X$CLUSTER" == "X$cluster" ] || continue
-    fi
-    if [ "X$verbose" == "Xyes" ] ; then
-      echo
-      echo "### Server: $server"
-      echo
-    fi
-    if [ `echo $IP | grep -c "$localip"` -ne 0 ] ; then
-      cp -up $tmpfile $to
-    else
-      [ -f "${rpath}/../keys/$KEY" ] || KEY="${KEY}.pem"
-      [ -f "${rpath}/../keys/$KEY" ] || (echo "Key not found for IP $IP" && continue)
-      cloudsync --ip=$IP "$tmpfile" "${to}"
-    fi
-  done
+  if [ -n "$test" -o -n "$dry" ] ; then
+    cat "${tmpfile}"
+  else
+    for server in `cat "${rpath}/../servers.list" | grep -v ^$ | grep -v  ^#|grep -v ^[[:space:]]*#` ; do
+      IP=${server%%|*}
+      if [ -n "$ip" ] ; then
+        [ "X$ip" == "X$IP" ] || continue
+      fi
+      KEY=`echo $server | cut -d'|' -f2`
+      if [ -n "$region" ] ; then
+        REGION=`echo $server | cut -d'|' -f3`
+        [ "X$REGION" == "X$region" ] || continue
+      fi
+      if [ -n "$cluster" ] ; then
+        CLUSTER=`echo $server | cut -d'|' -f5`
+        [ "X$CLUSTER" == "X$cluster" ] || continue
+      fi
+      if [ "X$verbose" == "Xyes" ] ; then
+        echo
+        echo "### Server: $server"
+        echo
+      fi
+      if [ `echo $IP | grep -c "$localip"` -ne 0 ] ; then
+        cp -up $tmpfile $to
+      else
+        [ -f "${rpath}/../keys/$KEY" ] || KEY="${KEY}.pem"
+        [ -f "${rpath}/../keys/$KEY" ] || (echo "Key not found for IP $IP" && continue)
+        cloudsync --ip=$IP "$tmpfile" "${to}"
+      fi
+    done
+  fi
+  rm -f "$tmpfile" "${tmpfile}.orig"
 fi
 IFS=$IFS1
 
