File name fix

diff --git a/deployment/deploy_file b/deployment/deploy_file
--- a/deployment/deploy_file
+++ b/deployment/deploy_file
@@ -22,7 +22,7 @@ rpath=${0%/*}
 [ -f "/sbin/ifconfig" ] && IFCFG=/sbin/ifconfig || IFCFG=`which ifconfig 2>/dev/null`
 SSH=`which ssh 2>/dev/null`
 [ -z "$SSH" ] && echo "SSH utility not found, exiting" && exit 1
-possible_options="cluster help region verbose"
+possible_options="cluster help region verbose flavor"
 commflag=0
 for s_option in "${@}"
 do
@@ -85,13 +85,17 @@ IFS='
 '
 if [ "X$command" != "X" ] ; then
   from=${command%% *}
-  from="${ROLES_ROOT}/${cluster}/${flavor}/files/${from}"
-  tmpfile=/tmp/m_script/deployment/`echo $from | sed 's|/|_|g'`
+  [ -f "$from" ] || (echo "$from is not a file or file not found" && exit 1)
+  fullfrom="${ROLES_ROOT}/${cluster}/${flavor}/files/${from}"
+  tmpfile=/tmp/m_script/deployment/`echo $fullfrom | sed 's|/|_|g'`
   rm -f "$tmpfile"
   for LINE in `cat "$from"` ; do
     echo "${LINE}" >> "$tmpfile"
   done
   to=${command#* }
+  if [ -d "$to" ] ; then
+    to=${to}/${from##*/}
+  fi
   [ -n "$verbose" ] && echo "### Deploying $from to $to"
   for server in `cat "${rpath}/../servers.list" | grep -v ^$ | grep -v  ^#|grep -v ^[[:space:]]*#` ; do
     IP=${server%%|*}
