better meta test

diff --git a/deployment/metaexec b/deployment/metaexec
--- a/deployment/metaexec
+++ b/deployment/metaexec
@@ -153,11 +153,11 @@ if [ -z "$cloud" -a -z "$ip" -a -z "$cluster" ] ; then
 fi
 if [ -z "$role" ] ; then
   role=`grep ^$cluster\| "${rpath}/../conf/clusters.conf" | cut -d'|' -f10`
-  [ -z "$role" ] && echo "Unable to find the role for this cluster/server" && exit 1
+  [ -z "$role" ] && echo "Unable to find the role of this cluster/server" && exit 1
 fi
 if [ -z "$flavor" ] ; then
   flavor=`grep ^$cluster\| "${rpath}/../conf/clusters.conf" | cut -d'|' -f11`
-  [ -z "$flavor" ] && echo "Unable to find the flavor for this cluster/server OS" && exit 1
+  [ -z "$flavor" ] && echo "Unable to find the flavor of this cluster/server OS" && exit 1
 fi
 [ -n "$repeat" ] && timestamp=repeat
 # Default output is console, colored if colors are supported
diff --git a/deployment/test_meta b/deployment/test_meta
--- a/deployment/test_meta
+++ b/deployment/test_meta
@@ -20,8 +20,8 @@ rpath=${0%/*}
 SSH=`which ssh 2>/dev/null`
 SCP=`which scp 2>/dev/null`
 [ -f "/sbin/ifconfig" ] && IFCFG=/sbin/ifconfig || IFCFG=`which ifconfig 2>/dev/null`
-possible_options="help verbose flavor cluster task role"
-necessary_options="role task"
+possible_options="help verbose flavor cluster task role ip"
+necessary_options="task"
 [ "X$*" == "X" ] && echo "Can't run without options. Possible options are: ${possible_options}" && exit 1
 for s_option in "${@}"
 do
@@ -63,8 +63,18 @@ source "${rpath}/../conf/deployment.conf"
 M_ROOT=$(cd "${rpath}/../" && pwd)
 export PATH=${M_ROOT}/deployment:${M_ROOT}/cloud:${M_ROOT}/cloud/ec2:${M_ROOT}/helpers:${PATH}
 source "${ROLES_ROOT}/${role}/role.conf"
+[ -z "$cluster" -a -z "$ip" ] && echo "One of --cluster or --ip options is necessary (ip should be present in servers.list if cluster is not defined)" && exit 1
+[ -z "$cluster" -a -n "$ip" ] && cluster=`grep ^$ip\| "${rpath}/../servers.list" | cut -d'|' -f5`
+[ -n "$cluster" -a -z "$ip" ] && ip="127.0.0.1"
 RETVAL=0
-[ -n "$flavor" ] || flavor="common"
+if [ -z "$role" ] ; then
+  role=`grep ^$cluster\| "${rpath}/../conf/clusters.conf" | cut -d'|' -f10`
+  [ -z "$role" ] && echo "Unable to find the role of this cluster/server. Define one of role, cluster, ip or check if you have a default role defined for this cluster in conf/clusters.conf" && exit 1
+fi
+if [ -z "$flavor" ] ; then
+  flavor=`grep ^$cluster\| "${rpath}/../conf/clusters.conf" | cut -d'|' -f11`
+  [ -z "$flavor" ] && echo "Unable to find the flavor of this cluster/server OS. Define it or check if this cluster has a default role set in conf/cluster.conf" && exit 1
+fi
 IFS1=$IFS
 IFS='
 '
