multiple tries to create a new server

diff --git a/deployment/metaexec b/deployment/metaexec
--- a/deployment/metaexec
+++ b/deployment/metaexec
@@ -102,6 +102,12 @@ run_meta() {
   fi
 }
 
+startserver() {
+  ip=`"${rpath}"/../cloud/${cloud}/start_server --cluster=${cluster} --noupdate --return=ip "$V" 2>>"${rpath}"/../logs/cloud.log | tail -1`
+  res=$?
+  echo "metaexec: start_server returned this IP: $ip">>"${rpath}"/../logs/cloud.log
+}
+
 SSH=`which ssh 2>/dev/null`
 SCP=`which scp 2>/dev/null`
 [ -f "/sbin/ifconfig" ] && IFCFG=/sbin/ifconfig || IFCFG=`which ifconfig 2>/dev/null`
@@ -234,17 +240,16 @@ if [ -n "$newserver" ]; then
   [ -z "$cloud" ] && echo "Cloud is not defined" && exit 1
   echo "*** Bringing up a new server in the cloud $cloud"
   "${rpath}"/../cloud/${cloud}/update_servers_list
-  ip=`"${rpath}"/../cloud/${cloud}/start_server --cluster=${cluster} --return=ip "$V" 2>>"${rpath}"/../logs/cloud.log | tail -1`
-  res=$?
-  echo "metaexec: start_server returned this IP: $ip">>"${rpath}"/../logs/cloud.log
-  # update_servers_list isn't required here, successful start_server updates it
-  [ $res -eq 5 ] && echo "Maximum servers number for cluster $cluster has been reached, unable to add another server" && exit 1
-  [ $res -eq 6 ] && echo "Failed to generate a name for the new server" && exit 1
-  [ $res -eq 7 ] && echo "Failed to find out what image to use to create the new server, define it in clusters.conf, please" && exit 1
-  [ $res -eq 8 ] && echo "Failed to find out what flavor (server size) to use, define it in clusters.conf, please" && exit 1
-  [ $res -eq 1 ] && echo "Something went wrong, unable to add a server to the cluster $cluster" && exit 1
-  [[ $ip =~ [^[0-9.]]* ]] && echo "Something's wrong with IP: $ip" && exit 1
-  [ -z "$ip" ] && echo "Was unable either to start a cloud server in the cloud $cloud or to get its IP address." && exit 1
+  for ((i=0; i<$NEW_SERVER_START_TRIES; i++)); do
+    # update_servers_list isn't required here, successful start_server updates it
+    [ $res -eq 5 ] && echo "Maximum servers number for cluster $cluster has been reached, unable to add another server" && sleep $WAIT_BETWEEN_TRIES && startserver
+    [ $res -eq 6 ] && echo "Failed to generate a name for the new server" && sleep $WAIT_BETWEEN_TRIES && exit 1
+    [ $res -eq 7 ] && echo "Failed to find out what image to use to create the new server, define it in clusters.conf, please" && sleep $WAIT_BETWEEN_TRIES && startserver
+    [ $res -eq 8 ] && echo "Failed to find out what flavor (server size) to use, define it in clusters.conf, please" && sleep $WAIT_BETWEEN_TRIES && startserver
+    [ $res -eq 1 ] && echo "Something went wrong, unable to add a server to the cluster $cluster" && sleep $WAIT_BETWEEN_TRIES && startserver
+    [[ $ip =~ [^[0-9.]]* ]] && echo "Something's wrong with IP: $ip" && sleep $WAIT_BETWEEN_TRIES && startserver
+    [ -z "$ip" ] && echo "Was unable either to start a cloud server in the cloud $cloud or to get its IP address." && sleep $WAIT_BETWEEN_TRIES && startserver
+  done
 fi
 
 if [ -z "$flavor" ] ; then
