finalizing RS lib

diff --git a/deployment/metaexec b/deployment/metaexec
--- a/deployment/metaexec
+++ b/deployment/metaexec
@@ -159,10 +159,9 @@ fi
 if [ -z "$ip" ] && [ -n "$cloud" ] && [ -n "$newserver" ]; then
   echo "*** Bringing up a new server in the cloud $cloud"
   ip=`${rpath}/../cloud/${cloud}/start_server --cluster=${cluster} --return=ip | tail -1`
-  if [[ $ip =~ [^[0-9.]]* ]] ; then
-    echo "Something's wrong with IP: $ip"
-    exit 1
-  fi
+  [ $? -eq 5 ] && echo "Maximum servers number for cluster $cluster has been reached, unable to add another server" && exit 1
+  [ $? -eq 1 ] && echo "Something went wrong, unable to add a server to cluster $cluster" && exit 1
+  [[ $ip =~ [^[0-9.]]* ]] && echo "Something's wrong with IP: $ip" && exit 1
   [ -z "$ip" ] && echo "Was unable either to start a cloud server in the cloud $cloud or to get its IP address." && exit 1
   ${rpath}/../cloud/${cloud}/update_servers_list
 fi
