bits

diff --git a/deployment/metaexec b/deployment/metaexec
--- a/deployment/metaexec
+++ b/deployment/metaexec
@@ -188,11 +188,16 @@ export PATH=${M_ROOT}/deployment:${M_ROOT}/cloud/${cloud}:${M_ROOT}/helpers:${PA
 if [ -n "$timestamp" ] ; then
   [ -n "$newserver" ] && echo "Repeating existing sequence is disabled for new server. If you want to repeat a meta that has brought brought up a server, it's safe to run $rcommand --repeat or $rcommand --timestamp=<timestamp> without other arguments. It will pick up IP address of that server and all relevant arguments." && exit 1
   if [ "X$timestamp" == "Xrepeat" ]; then
-    timestampact=`ls -1tr "${WORK_DIR}" | tail -1` && timestampact=${timestampact##*.} && echo "Restoring the process with timestamp $timestampact"
+    timestampact=`ls -1tr "${WORK_DIR}" | tail -1` && timestampact=${timestampact##*.} && echo "Restoring process with timestamp $timestampact"
     if [ -n "$timestampact" ]; then
       argfile=`find "${WORK_DIR}"/*.${timestampact}/ -maxdepth 1 -name ARGV`
-      [ -f "$argfile" ] && sed -i "/^newserver/d;/^test/d;/^verbose/d;/^debug/d" "$argfile"
-      source "$argfile"
+      if [ -f "$argfile" ]; then
+        sed -i "/^newserver/d;/^test/d;/^verbose/d;/^debug/d" "$argfile"
+        source "$argfile"
+      else
+        echo "Process with timestamp $timestampact cannot be repeated, no arguments file found"
+        exit 1
+      fi
     fi
   else
     timestampact="$timestamp"
