bugfix

diff --git a/deployment/metaexec b/deployment/metaexec
--- a/deployment/metaexec
+++ b/deployment/metaexec
@@ -87,7 +87,6 @@ if [ -z "$cloud" -a -z "$ip" -a -z "$cluster" ] ; then
   exit 1
 fi
 
-
 source "${rpath}/../conf/deployment.conf"
 M_ROOT=$(cd "${rpath}/../" && pwd)
 export PATH=${M_ROOT}/deployment:${M_ROOT}/cloud:${M_ROOT}/cloud/ec2:${M_ROOT}/helpers:${PATH}
@@ -141,15 +140,27 @@ if [ `echo $ip | grep -c "$localip"` -eq 0 ] ; then
     IFS='
 '
     for meta in `cat "${ROLES_ROOT}/${role}/meta.${task}" | grep -v ^# | grep -v ^$ | grep -v ^[[:space:]]*#` ; do
-      [ `grep -c "^${meta}$" "${WORK_DIR}/${role}.${task}.${timestamp}/log"` -ne 0 ] && echo "Skipping: $meta" >> "${rpath}/../deploy.log" && continue
-      echo "*** META: $meta"
-      metatype=`echo $meta | awk '{print $1}'`
-      metascript=`echo $meta | awk '{print $2}'`
-      metascript=`eval "echo $metascript"`
-      printf "== type: $metatype  script: $metascript  ..  "
-      if [ -n "$metatype" ] && [ -n "$metascript" ] ; then
-        deploy.run --type=$metatype --file=$metascript --ip=$ip --key="$KEY" --cluster="$cluster" --role="$role" --flavor="$flavor" --timestamp=$timestamp --task="$task"
-        [ $? -eq 0 ] && echo "OK" && echo "$meta" >> "${WORK_DIR}/${role}.${task}.${timestamp}/log" || echo "ERROR"
+      if [ -n "$test" -o -n "$dry" ] ; then
+        echo "*** META: $meta"
+        metatype=`echo $meta | awk '{print $1}'`
+        metascript=`echo $meta | awk '{print $2}'`
+        metascript=`eval "echo $metascript"`
+        printf "== type: $metatype  script: $metascript  ..  "
+        if [ -n "$metatype" ] && [ -n "$metascript" ] ; then
+          deploy.run --type=$metatype --file=$metascript --ip=$ip --key="$KEY" --cluster="$cluster" --role="$role" --flavor="$flavor" --timestamp=$timestamp --task="$task" --dry
+          [ $? -eq 0 ] && echo "OK" || echo "ERROR"
+        fi
+      else
+        [ `grep -c "^${meta}$" "${WORK_DIR}/${role}.${task}.${timestamp}/log"` -ne 0 ] && echo "Skipping: $meta" >> "${rpath}/../deploy.log" && continue
+        echo "*** META: $meta"
+        metatype=`echo $meta | awk '{print $1}'`
+        metascript=`echo $meta | awk '{print $2}'`
+        metascript=`eval "echo $metascript"`
+        printf "== type: $metatype  script: $metascript  ..  "
+        if [ -n "$metatype" ] && [ -n "$metascript" ] ; then
+          deploy.run --type=$metatype --file=$metascript --ip=$ip --key="$KEY" --cluster="$cluster" --role="$role" --flavor="$flavor" --timestamp=$timestamp --task="$task"
+          [ $? -eq 0 ] && echo "OK" && echo "$meta" >> "${WORK_DIR}/${role}.${task}.${timestamp}/log" || echo "ERROR"
+        fi
       fi
     done
     IFS=$IFS1
