mssh wrapper

diff --git a/deployment/metaexec b/deployment/metaexec
--- a/deployment/metaexec
+++ b/deployment/metaexec
@@ -17,6 +17,8 @@
 rcommand=${0##*/}
 rpath=${0%/*}
 #*/
+M_ROOT=$(cd "${rpath}/../" && pwd)
+LOG="$M_ROOT/logs/deploy.log"
 
 run_meta() {
   [ `grep -c "^${1}$" "${WORK_DIR}/${role}.${task}.${timestampact}/log"` -ne 0 ] && echo "Skipping: $1" | tee -a "$LOG" && return 0
@@ -116,7 +118,7 @@ run_meta() {
 startserver() {
   ip=`"${rpath}"/../cloud/${cloud}/start_server --cluster=${cluster} --return=ip "$V" "$T" 2>>"${rpath}"/../logs/cloud.log | tail -1`
   res=$?
-  echo "`date +"%m.%d %H:%M"` metaexec: start_server exited with status $res and returned this IP: $ip">>"${rpath}"/../logs/cloud.log
+  log "start_server exited with status $res and returned this IP: $ip">>"${rpath}"/../logs/cloud.log
 }
 
 SSH=`which ssh 2>/dev/null`
@@ -166,8 +168,7 @@ do
 done
 IFS=$IFS1
 
-M_ROOT=$(cd "${rpath}/../" && pwd)
-LOG="$M_ROOT/logs/deploy.log"
+
 
 [ -n "$debug" ] && verbose="yes" && debug=true
 export verbose debug
@@ -186,6 +187,8 @@ source "${rpath}/../lib/functions.sh"
 
 export PATH=${M_ROOT}/deployment:${M_ROOT}/cloud/${cloud}:${M_ROOT}/helpers:${PATH}
 [ -n "$task" ] || task=notask
+
+log "Starting metaexec with arguments $@"
 
 [ "X$IFCFG" != "X" ] && localip=`$IFCFG | sed '/inet\ /!d;s/.*r://;s/\ .*//' | grep -v '127.0.0.1'` || localip="ifconfig_not_found"
 
@@ -256,33 +259,36 @@ export role cluster
 install $V -d "${WORK_DIR}/${role}.${task}.${timestampact}"
 touch "${WORK_DIR}/${role}.${task}.${timestampact}/log"
 
+if [ -z "$flavor" ] ; then
+  flavor=`grep ^$cluster\| "${rpath}/../conf/clusters.conf" | cut -d'|' -f11`
+  echo "Using flavor ${flavor}, default for cluster ${cluster}"
+  [ -z "$flavor" ] && echo "Unable to find the flavor of this cluster/server OS" && exit 1
+fi
+
 if [ -n "$newserver" ]; then
   [ -z "$cloud" ] && echo "Cloud is not defined" && exit 1
   [ -z "$NEW_SERVER_START_TRIES" ] && NEW_SERVER_START_TRIES=3
   [ -z "$WAIT_BETWEEN_TRIES" ] && WAIT_BETWEEN_TRIES=30
   echo "*** Bringing up a new server in cloud $cloud"
+  log "bringing up a new server in cloud $cloud"
   if [ -z "$test" ]; then
+    log "updating servers list"
     "${rpath}"/../cloud/${cloud}/update_servers_list
   else
     echo "*** This is a test"
   fi
+  log "initiating start server sequence"
   startserver $T
   for ((i=0; i<$NEW_SERVER_START_TRIES; i++)); do
     # update_servers_list isn't required here, successful start_server updates it
-    [ $res -eq 5 ] && echo "Maximum servers number for cluster $cluster has been reached, unable to add another server" && sleep $WAIT_BETWEEN_TRIES && startserver $T
-    [ $res -eq 6 ] && echo "Failed to generate a name for the new server" && exit 1
-    [ $res -eq 7 ] && echo "Failed to find out what image to use to create the new server, define it in clusters.conf, please" && sleep $WAIT_BETWEEN_TRIES && startserver $T
-    [ $res -eq 8 ] && echo "Failed to find out what flavor (server size) to use, define it in clusters.conf, please" && sleep $WAIT_BETWEEN_TRIES && startserver $T
-    [ $res -eq 1 ] && echo "Something went wrong, unable to add a server to the cluster $cluster" && sleep $WAIT_BETWEEN_TRIES && startserver $T
-    [[ $ip =~ [^[0-9.]]* ]] && echo "Something's wrong with IP: $ip" && sleep $WAIT_BETWEEN_TRIES && startserver $T
-    [ -z "$ip" ] && echo "Was unable either to start a cloud server in the cloud $cloud or to get its IP address." && sleep $WAIT_BETWEEN_TRIES && startserver $T
+    [ $res -eq 5 ] && log "Maximum servers number for cluster $cluster has been reached, unable to add another server" && sleep $WAIT_BETWEEN_TRIES && startserver $T
+    [ $res -eq 6 ] && log "Failed to generate a name for the new server" && exit 1
+    [ $res -eq 7 ] && log "Failed to find out what image to use to create the new server, define it in clusters.conf, please" && sleep $WAIT_BETWEEN_TRIES && startserver $T
+    [ $res -eq 8 ] && log "Failed to find out what flavor (server size) to use, define it in clusters.conf, please" && sleep $WAIT_BETWEEN_TRIES && startserver $T
+    [ $res -eq 1 ] && log "Something went wrong, unable to add a server to the cluster $cluster" && sleep $WAIT_BETWEEN_TRIES && startserver $T
+    [[ $ip =~ [^[0-9.]]* ]] && log "Something's wrong with IP: $ip" && sleep $WAIT_BETWEEN_TRIES && startserver $T
+    [ -z "$ip" ] && log "Was unable either to start a cloud server in the cloud $cloud or to get its IP address." && sleep $WAIT_BETWEEN_TRIES && startserver $T
   done
-fi
-
-if [ -z "$flavor" ] ; then
-  flavor=`grep ^$cluster\| "${rpath}/../conf/clusters.conf" | cut -d'|' -f11`
-  echo "Using flavor ${flavor}, default for cluster ${cluster}"
-  [ -z "$flavor" ] && echo "Unable to find the flavor of this cluster/server OS" && exit 1
 fi
 
 # Default output is console, colored if colors are supported
