just a forgotten part of colorification

diff --git a/deployment/metaexec b/deployment/metaexec
--- a/deployment/metaexec
+++ b/deployment/metaexec
@@ -62,11 +62,19 @@ run_meta() {
       deploy.run --type=$metatype --file=$metascript --ip=$ip --key="$KEY" --cluster="$cluster" --role="$role" --flavor="$flavor" --timestamp=$timestamp --task="$task" $V
       res=$?
       if [ -n "$verbose" ] ; then
-        [ $res -eq 0 ] && echo "Success" && echo "$meta" >> "${WORK_DIR}/${role}.${task}.${timestamp}/log" || echo "ERROR"
+        if [ -n "$use_color" ] ; then
+          [ $res -eq 0 ] && printf "\033[01;32mSuccess\033[00;39m\n" || printf "\033[01;31mError\033[00;39m\n"
+        else
+          [ $res -eq 0 ] && echo "Success" || echo "ERROR"
+        fi
       else
-        [ $res -eq 0 ] && echo "  ..  Success" && echo "$meta" >> "${WORK_DIR}/${role}.${task}.${timestamp}/log" || echo "  ..  ERROR"
+        if [ -n "$use_color" ] ; then
+          [ $res -eq 0 ] && printf "  ..  \033[01;32mSuccess\033[00;39m\n" || printf "  ..  \033[01;31mError\033[00;39m\n"
+        else
+          [ $res -eq 0 ] && echo "  ..  Success" || echo "  ..  ERROR"
+        fi
       fi
-      echo
+      [ -n "$verbose" ] && echo
     else
       echo "Error parsing the meta: $meta"
     fi
