env - environment vars sourcing

diff --git a/deployment/metaexec b/deployment/metaexec
--- a/deployment/metaexec
+++ b/deployment/metaexec
@@ -168,7 +168,7 @@ if [ -z "$ip" ] && [ -n "$cloud" ] && [ -n "$newserver" ]; then
   [ $? -eq 6 ] && echo "Failed to generate a name for the new server" && exit 1
   [ $? -eq 7 ] && echo "Failed to find out what image to use to create the new server, define it in clusters.conf, please" && exit 1
   [ $? -eq 8 ] && echo "Failed to find out what flavor (server size) to use, define it in clusters.conf, please" && exit 1
-  [ $? -eq 1 ] && echo "Something went wrong, unable to add a server to cluster $cluster" && exit 1
+  [ $? -eq 1 ] && echo "Something went wrong, unable to add a server to the cluster $cluster" && exit 1
   [[ $ip =~ [^[0-9.]]* ]] && echo "Something's wrong with IP: $ip" && exit 1
   [ -z "$ip" ] && echo "Was unable either to start a cloud server in the cloud $cloud or to get its IP address." && exit 1
 fi
