bugs fixed

diff --git a/deployment/metaexec b/deployment/metaexec
--- a/deployment/metaexec
+++ b/deployment/metaexec
@@ -464,9 +464,9 @@ fi
 
 if [ `echo $ip | grep -c "^$localip$"` -eq 0 ] ; then
   #KEY=`grep "^${cluster}|" "${rpath}/../conf/clusters.conf" | cut -d'|' -f2`
-  KEY=`find_key cluster "$cluster"` || KEY=`find_key server "$ip"` || proper_exit 1 450
-  [ -z "$KEY" ] && echo "Access key not found!" && proper_exit 1 451
-  [ -z "$SSH" ] && echo "SSH client not found!" && proper_exit 1 452
+  KEY=`find_key cluster "$cluster"` || KEY=`find_key server "$ip"` || proper_exit 1 467
+  [ -z "$KEY" ] && echo "Access key not found!" && proper_exit 1 468
+  [ -z "$SSH" ] && echo "SSH client not found!" && proper_exit 1 469
   if [ -z "$list" ] ; then
     #SSH="$SSH -i \"${rpath}/../keys/${KEY}\" -o StrictHostKeyChecking=no"
     $debug && log "ensuring the target server $ip is accessible"
@@ -485,7 +485,7 @@ if [ `echo $ip | grep -c "^$localip$"` -eq 0 ] ; then
       if ! $loggedin && [ -n "$newserver" ]; then
         # stop useless server and tell the parent process that something's wrong
         "$M_ROOT"/cloud/$CLOUD_PROVIDER/stop_server --ip=$ip
-        proper_exit 13 473
+        proper_exit 13 488
       fi
     fi
     #[ -z "$SCP" ] && echo "SCP not found!" && exit 1
@@ -556,7 +556,7 @@ if [ `echo $ip | grep -c "^$localip$"` -eq 0 ] ; then
 
         if ! $skipthis ; then
           (IFS=$IFSORIG ; run_meta $meta)
-          [ $? -ne 0 ] && echo -e "Timestamp: $timestampact\nWork directory: $WORK_DIR/${role}.${task}.$timestampact\n" && proper_exit 1 544
+          [ $? -ne 0 ] && echo -e "Timestamp: $timestampact\nWork directory: $WORK_DIR/${role}.${task}.$timestampact\n" && proper_exit 1 559
         fi
       fi
       metan+=1
@@ -574,7 +574,7 @@ if [ -z "$list" ] ; then
 fi
 echo
 if [ -n "$newserver" ]; then
-  proper_exit 0 562
+  proper_exit 0 577
 fi
 #echo "Preparing the keys"
 #if [ -f /root/.ssh/id_rsa.pub ] ; then
diff --git a/helpers/find_key b/helpers/find_key
--- a/helpers/find_key
+++ b/helpers/find_key
@@ -80,7 +80,11 @@ case $where in
           cluster=`IAMACHILD=1 "$M_ROOT"/cloud/common/find_server --cloud=$CLOUD --name=$1 | grep "\"metadata\"/\"$CLUSTER_TAG\"|" | cut -d'|' -f2`
           [ -z "$cluster" ] && cluster=`IAMACHILD=1 "$M_ROOT"/cloud/common/find_server --cloud=$CLOUD --ip=$1 | grep "\"metadata\"/\"$CLUSTER_TAG\"|" | cut -d'|' -f2`
         fi
-        [ -z "$cluster" ] && echo "Cluster not found for server $1" >&2 | tee -a "$LOG"
+        if [ -z "$cluster" ]; then
+          echo "Cluster not found for server $1" >&2 | tee -a "$LOG"
+        else
+          find_cluster_key "$cluster" && echo "$M_ROOT/keys/$KEY" && exit 0
+        fi
       fi
       if [ ! -f "$M_ROOT/keys/$KEY" ]; then
         #log "trying ${USER}'s keys"
