bits

diff --git a/deployment/metaexec b/deployment/metaexec
--- a/deployment/metaexec
+++ b/deployment/metaexec
@@ -125,48 +125,37 @@ SSH=`which ssh 2>/dev/null`
 SCP=`which scp 2>/dev/null`
 [ -f "/sbin/ifconfig" ] && IFCFG=/sbin/ifconfig || IFCFG=`which ifconfig 2>/dev/null`
 possible_options="help verbose debug flavor ip cloud run cluster task role timestamp test dry command output repeat newserver list skip"
-[ "X$*" == "X" ] && echo "Can't run without options. Possible options are: ${possible_options}" && exit 1
+[ "X$*" == "X" ] && echo "Can't work without options. Possible options are: ${possible_options}" && exit 1
+
 IFS1=$IFS
-IFS='--'
-for s_option in "${@}"
+IFS='-'
+for s_option in "$@"
 do
-  found=0
-  case ${s_option} in
-  --*=*)
-    s_optname=`expr "X$s_option" : 'X[^-]*-*\([^=]*\)'`  
-    s_optarg=`expr "X$s_option" : 'X[^=]*=\(.*\)'` 
-    ;;
-  --*)
-    s_optname=`expr "X$s_option" : 'X[^-]*-*\([^=]*\)'`    
-    s_optarg='yes' 
-    ;;
-  *=*)
-    echo "Wrong syntax: options must start with a double dash"
-    exit 1
-    ;;
-  *)
-    s_param=${s_option}
-    s_optname=''
-    s_optarg=''
-    ;;
-  esac
-  for option in `echo $possible_options | sed 's/ /--/g'`; do
-    if [ "X$s_optname" == "X$option" ]; then
-      if [ -n "$s_optarg" ]; then
-        eval "$s_optname=\"$s_optarg\""
-      else
-        [ -z "$(eval echo \$$option)" ] && eval "$option="
-      fi
-      found=1
-    fi
+  found=false
+  s_option=${s_option/--/}
+  s_optname=${s_option%%=*}
+  s_optarg=${s_option##*=}
+  [ "X$s_optarg" == "X$s_optname" ] && s_optarg="yes"
+
+  for option in ${possible_options// /-} ; do
+    [ "X$s_optname" == "X$option" ] && eval "$s_optname=\"$s_optarg\"" && found=true && break
   done
-  [ "X$s_option" == "X$s_param" ] && found=1
-  if [[ $found -ne 1 ]]; then 
+  
+  if ! $found ; then 
     echo "Unknown option: $s_optname"
     exit 1
   fi
 done
 IFS=$IFS1
+
+found=false
+for option in $necessary_options ; do
+  [ -z "$(eval echo \$$option)" ] && missing_options="${missing_options} --${option}," && found=true
+done
+if $found ; then
+  echo "Necessary options: ${missing_options/%,/} not found"
+  exit 1
+fi
 
 [ -n "$debug" ] && verbose="yes" && debug=true
 export verbose debug
