meta doubling issue

diff --git a/deployment/metaexec b/deployment/metaexec
--- a/deployment/metaexec
+++ b/deployment/metaexec
@@ -443,11 +443,11 @@ if [ -n "$newserver" ]; then
         res=$ip
       fi
       [[ $res -eq 2 ]] && log "Timeout waiting for the server ready" && break
-      [[ $res -eq 5 ]] && log "Maximum servers number for cluster $cluster has been reached, unable to add another server" && proper_exit 5 438
+      [[ $res -eq 5 ]] && log "Maximum servers number for cluster $cluster has been reached, unable to add another server" && proper_exit 5 446
       # various weird errors below, exit 1 
-      [[ $res -eq 6 ]] && log "Failed to generate a name for the new server" && proper_exit 1 440
-      [[ $res -eq 7 ]] && log "Failed to find out what image to use to create the new server, define it in clusters.conf, please" && proper_exit 1 441
-      [[ $res -eq 8 ]] && log "Failed to find out what flavor (server size) to use, define it in clusters.conf, please" && proper_exit 1 442
+      [[ $res -eq 6 ]] && log "Failed to generate a name for the new server" && proper_exit 1 448
+      [[ $res -eq 7 ]] && log "Failed to find out what image to use to create the new server, define it in clusters.conf, please" && proper_exit 1 449
+      [[ $res -eq 8 ]] && log "Failed to find out what flavor (server size) to use, define it in clusters.conf, please" && proper_exit 1 450
       [[ $res -eq 1 ]] && log "Something went wrong, unable to add a server to the cluster $cluster"
       if [ -z "$ip" ]; then
         log "Was unable either to start a cloud server in the cloud $CLOUD or to get its IP address." && sleep $WAIT_BETWEEN_TRIES && continue
@@ -455,7 +455,7 @@ if [ -n "$newserver" ]; then
       [[ `expr $ip : [0-9.]*$` -eq 0 ]] && log "Something's wrong with IP: $ip"
       echo "Something went wrong, check $LOG and fix the problem, next try is in $WAIT_BETWEEN_TRIES seconds"
     done
-    [ $i -eq $NEW_SERVER_START_TRIES ] && log "Maximal number of tries reached, exiting" && proper_exit 1 450
+    [ $i -eq $NEW_SERVER_START_TRIES ] && log "Maximal number of tries reached, exiting" && proper_exit 1 458
   else
     echo "*** This is a test"
   fi
@@ -483,8 +483,8 @@ fi
 if [ `echo $ip | grep -c "^$localip$"` -eq 0 ] ; then
   #KEY=`grep "^${cluster}|" "${rpath}/../conf/clusters.conf" | cut -d'|' -f2`
   KEY=`"$M_ROOT"/helpers/find_key cluster "$cluster"` || KEY=`"$M_ROOT"/helpers/find_key server "$ip"` || proper_exit 1 467
-  [ -z "$KEY" ] && echo "Access key not found!" && proper_exit 1 478
-  [ -z "$SSH" ] && echo "SSH client not found!" && proper_exit 1 479
+  [ -z "$KEY" ] && echo "Access key not found!" && proper_exit 1 486
+  [ -z "$SSH" ] && echo "SSH client not found!" && proper_exit 1 487
   # it's here because startserver function cause re-reading cloud config
   [ -n "$SSHPORT" ] || SSHPORT=22
   if [ -z "$list" ] ; then
@@ -505,7 +505,7 @@ if [ `echo $ip | grep -c "^$localip$"` -eq 0 ] ; then
       if ! $loggedin && [ -n "$newserver" ]; then
         # stop useless server and tell the parent process that something's wrong
         "$M_ROOT"/cloud/$CLOUD_PROVIDER/stop_server --ip=$ip
-        proper_exit 13 500
+        proper_exit 13 508
       fi
     fi
     #[ -z "$SCP" ] && echo "SCP not found!" && exit 1
@@ -525,7 +525,7 @@ if [ `echo $ip | grep -c "^$localip$"` -eq 0 ] ; then
         echo "ip=\"$ip\"" >> "$CURRTASKDIR/ARGV"
       fi
     else
-      rm -f "$CURRTASKDIR"/meta
+      rm "$CURRTASKDIR"/meta 2>/dev/null
     fi
     ##
   fi
@@ -534,6 +534,7 @@ if [ `echo $ip | grep -c "^$localip$"` -eq 0 ] ; then
     meta="$command"
     run_meta $meta
   else
+    rm "$CURRTASKDIR"/meta 2>/dev/null
     IFS='
 '
     cat "$ROLES_ROOT/$role/meta.$task" | grep -v ^# | grep -v ^$ | grep -v ^[[:space:]]*# | while read metaline ; do (IFS=$IFSORIG ; genline $metaline >> "$CURRTASKDIR"/meta) ; done
@@ -576,7 +577,7 @@ if [ `echo $ip | grep -c "^$localip$"` -eq 0 ] ; then
 
         if ! $skipthis ; then
           (IFS=$IFSORIG ; run_meta $meta)
-          [ $? -ne 0 ] && echo -e "Timestamp: $timestampact\nWork directory: $CURRTASKDIR\n" && proper_exit 1 571
+          [ $? -ne 0 ] && echo -e "Timestamp: $timestampact\nWork directory: $CURRTASKDIR\n" && proper_exit 1 579
         fi
       fi
       metan+=1
@@ -594,7 +595,7 @@ if [ -z "$list" ] ; then
 fi
 echo
 if [ -n "$newserver" ]; then
-  proper_exit 0 589
+  proper_exit 0 597
 fi
 #echo "Preparing the keys"
 #if [ -f /root/.ssh/id_rsa.pub ] ; then
