fix

diff --git a/deployment/metaexec b/deployment/metaexec
--- a/deployment/metaexec
+++ b/deployment/metaexec
@@ -25,139 +25,102 @@ run_meta() {
   res=0
   [ `grep -c "^${1}$" "$WORK_DIR/${role}.${task}.$timestampact/log"` -ne 0 ] && echo "Skipping: $1" | tee -a "$LOG" && return 0
   [ -n "$use_color" ] && printf "\033[01;36mMETA: \033[00;36m$1\033[0m" || printf "META: $1"
-  if [ -n "$test" -o -n "$dry" ] ; then
-    metatype=`echo $1 | awk '{print $1}'`
-    metascript=`echo $1 | awk '{print $2}'`
-    [ -z "$metascript" ] && metascript="$metatype" && unset metatype
-    metascript=`eval "echo $metascript"`
-    if [ -z "$metatype" ] ; then
-      # finding out from shebang
-      ipr=`head -1 "$1" | grep ^#! | cut -b 3- | awk '{print $1}'`
-      if [ -n "$ipr" ] ; then
-        [ "$ipr" == "runlocal" ] && metatype="local"
-        [ "$ipr" == "runremote" ] && metatype="remote"
-      fi
+  [ -n "$test" -o -n "$dry" ] && dry="--dry"
+  
+  metatype=`echo $1 | awk '{print $1}'`
+  metascript=`echo $1 | awk '{print $2}'`
+  [ -z "$metascript" ] && metascript="$metatype" && unset metatype
+  metascript=`eval "echo $metascript"`
+  if [ -z "$metatype" ] ; then
+    # finding out from shebang
+    ipr=`head -1 "$1" | grep ^#! | cut -b 3- | awk '{print $1}'`
+    if [ -n "$ipr" ] ; then
+      [ "$ipr" == "runlocal" ] && metatype="local"
+      [ "$ipr" == "runremote" ] && metatype="remote"
     fi
-    [ -z "$metatype" ] && echo "Meta type is not defined. Don't know how to run it." && exit 1
-    if [ -n "$verbose" ] ; then
-      printf "\n  type: $metatype  script: $metascript \n"
-      V='--verbose'
-    fi
-    if [ -n "$debug" ] ; then
-      D='--debug'
-    fi
-    if [ -n "$ignoreemptycluster" ] ; then
-      I="--ignoreemptycluster"
-    fi
-    if [ -n "$metatype" ] && [ -n "$metascript" ] ; then
-      if [ ! -e "$ROLES_ROOT/$metascript" ] ; then
-        thescript=${metascript##*/}
-        therest=${metascript%/*}
-        therest=`expr "$therest" : "\.*/\(.*\)"`
-        if [ -z "$therest" ]; then
-          if [ -e "$ROLES_ROOT/$role/$flavor/$thescript" ]; then
-            metascript="$ROLES_ROOT/$role/$flavor/$thescript"
-          else
-            metascript=`find "$ROLES_ROOT" -name "$thescript"`
-            if [ -z "$metascript" ]; then
-              echo "$ROLES_ROOT/$metascript not found"
-              res=1
-            else
-              if [ `echo "$metascript" | wc -l` -gt 1 ]; then
-                echo "Found more than one scripts with the name ${thescript}:"
-                echo "$metascript"
-                echo "Please narrow the search conditions"
-                res=1
-              fi
-            fi
-          fi
+  fi
+  [ -z "$metatype" ] && echo "Meta type is not defined. Don't know how to run it." && exit 1
+  if [ -n "$verbose" ] ; then
+    printf "\n  type: $metatype  script: $metascript \n"
+    V='--verbose'
+  fi
+  if [ -n "$debug" ] ; then
+    D='--debug'
+  fi
+  if [ -n "$ignoreemptycluster" ] ; then
+    I="--ignoreemptycluster"
+  fi
+  if [ -n "$metatype" ] && [ -n "$metascript" ] ; then
+    if [ ! -e "$ROLES_ROOT/$metascript" ] ; then
+      thescript=${metascript##*/}
+      therest=${metascript%/*}
+      therest=`expr "$therest" : "\.*/\(.*\)"`
+      if [ -z "$therest" ]; then
+        if [ -e "$ROLES_ROOT/$role/$flavor/$thescript" ]; then
+          metascript="$ROLES_ROOT/$role/$flavor/$thescript"
         else
-          therole=`echo "$therest" | cut -d'/' -s -f1`
-          theflavor=`echo "$therest" | cut -d'/' -s -f2`
-          [ -z "$therole" -a -z "$theflavor" ] && theflavor="$therest"
-          if [ -n "$therole" ]; then
-            msfoundinrole=`find "$ROLES_ROOT/$therole" -name "$thescript"`
-            msfoundinflavor=`find "$ROLES_ROOT"/*/"$theflavor" -name "$thescript"`
-            echo "Script $metascript not found"
-            [ -n "$msfoundinrole" ] && echo "  Found: $msfoundinrole"
-            [ -n "$msfoundinflavor" ] && echo "  Found: $msfoundinflavor"
+          metascript=`find "$ROLES_ROOT" -name "$thescript"`
+          if [ -z "$metascript" ]; then
+            echo "$ROLES_ROOT/$metascript not found"
             res=1
           else
-            if [ -e "$ROLES_ROOT/$role/$theflavor/$thescript" ]; then
-              metascript="$ROLES_ROOT/$role/$theflavor/$thescript"
-            else
-              msfoundinflavor=`find "$ROLES_ROOT"/*/"$theflavor" -name "$thescript"`
-              echo "Script $metascript not found"
-              [ -n "$msfoundinflavor" ] && echo "  Found: $msfoundinflavor"
+            if [ `echo "$metascript" | wc -l` -gt 1 ]; then
+              echo "Found more than one scripts with the name ${thescript}:"
+              echo "$metascript"
+              echo "Please narrow the search conditions"
               res=1
             fi
           fi
         fi
-      fi
-      if [ $res -eq 0 ]; then
-        [ -e "$WORK_DIR/${role}.${task}.$timestampact/$metascript" ] && rm -f "$WORK_DIR/${role}.${task}.$timestampact/$metascript"
-        [ -e "$WORK_DIR/${role}.${task}.$timestampact/$metascript.var" ] && rm -f "$WORK_DIR/${role}.${task}.$timestampact/${metascript}.var"
-        deploy.run --type=$metatype --file=$metascript --ip=$ip --key="$KEY" --cluster="$cluster" --role="$role" --flavor="$flavor" --timestamp=$timestampact --task="$task" --dry $V $D $I
-        res=$?
-      fi
-      if [ -n "$verbose" ] ; then
-        if [ -n "$use_color" ] ; then
-          [ $res -eq 0 ] && printf "\033[01;32mSuccess\033[0m\n" || printf "\033[01;31mError\033[0m\n"
-        else
-          [ $res -eq 0 ] && echo "Success" || echo "ERROR"
-        fi
       else
-        if [ -n "$use_color" ] ; then
-          [ $res -eq 0 ] && printf " ..  \033[01;32mSuccess\033[0m\n" || printf " ..  \033[01;31mError\033[0m\n"
+        therole=`echo "$therest" | cut -d'/' -s -f1`
+        theflavor=`echo "$therest" | cut -d'/' -s -f2`
+        [ -z "$therole" -a -z "$theflavor" ] && theflavor="$therest"
+        if [ -n "$therole" ]; then
+          msfoundinrole=`find "$ROLES_ROOT/$therole" -name "$thescript"`
+          msfoundinflavor=`find "$ROLES_ROOT"/*/"$theflavor" -name "$thescript"`
+          echo "Script $metascript not found"
+          [ -n "$msfoundinrole" ] && echo "  Found: $msfoundinrole"
+          [ -n "$msfoundinflavor" ] && echo "  Found: $msfoundinflavor"
+          res=1
         else
-          [ $res -eq 0 ] && echo " ..  Success" || echo " ..  ERROR"
+          if [ -e "$ROLES_ROOT/$role/$theflavor/$thescript" ]; then
+            metascript="$ROLES_ROOT/$role/$theflavor/$thescript"
+          else
+            msfoundinflavor=`find "$ROLES_ROOT"/*/"$theflavor" -name "$thescript"`
+            echo "Script $metascript not found"
+            [ -n "$msfoundinflavor" ] && echo "  Found: $msfoundinflavor"
+            res=1
+          fi
         fi
       fi
-      [ -n "$verbose" ] && echo
-      return $res
-    else
-      [ -n "$use_color" ] && printf "\033[01;31m"
-      echo "Error parsing the meta: $meta"
-      [ -n "$use_color" ] && printf "\033[0m"
     fi
-  else
-    metatype=`echo $1 | awk '{print $1}'`
-    metascript=`echo $1 | awk '{print $2}'`
-    metascript=`eval "echo $metascript"`
+    if [ $res -eq 0 ]; then
+      [ -e "$WORK_DIR/${role}.${task}.$timestampact/$metascript" ] && rm -f "$WORK_DIR/${role}.${task}.$timestampact/$metascript"
+      [ -e "$WORK_DIR/${role}.${task}.$timestampact/$metascript.var" ] && rm -f "$WORK_DIR/${role}.${task}.$timestampact/${metascript}.var"
+      deploy.run --type=$metatype --file=$metascript --ip=$ip --key="$KEY" --cluster="$cluster" --role="$role" --flavor="$flavor" --timestamp=$timestampact --task="$task" $dry $V $D $I
+      res=$?
+    fi
     if [ -n "$verbose" ] ; then
-      printf "\n  type: $metatype  script: $metascript \n"
-      V='--verbose'
-    fi
-    if [ -n "$metatype" ] && [ -n "$metascript" ] ; then
-      if [ -e "$ROLES_ROOT/$metascript" ] ; then
-        [ -e "$WORK_DIR/${role}.${task}.$timestampact/$metascript" ] && rm -f "$WORK_DIR/${role}.${task}.$timestampact/$metascript"
-        [ -e "$WORK_DIR/${role}.${task}.$timestampact/${metascript}.var" ] && rm -f "$WORK_DIR/${role}.${task}.$timestampact/${metascript}.var"
-        deploy.run --type=$metatype --file=$metascript --ip=$ip --key="$KEY" --cluster="$cluster" --role="$role" --flavor="$flavor" --timestamp=$timestampact --task="$task" $V
-        res=$?
+      if [ -n "$use_color" ] ; then
+        [ $res -eq 0 ] && printf "\033[01;32mSuccess\033[0m\n" || printf "\033[01;31mError\033[0m\n"
       else
-        echo "$ROLES_ROOT/$metascript not found"
-        res=1
+        [ $res -eq 0 ] && echo "Success" || echo "ERROR"
       fi
-      if [ -n "$verbose" ] ; then
-        if [ -n "$use_color" ] ; then
-          [ $res -eq 0 ] && printf "\033[01;32mSuccess\033[0m\n" || printf "\033[01;31mError\033[0m\n"
-        else
-          [ $res -eq 0 ] && echo "Success" || echo "ERROR"
-        fi
-      else
-        if [ -n "$use_color" ] ; then
-          [ $res -eq 0 ] && printf " ..  \033[01;32mSuccess\033[0m\n" || printf " ..  \033[01;31mError\033[0m\n"
-        else
-          [ $res -eq 0 ] && echo " ..  Success" || echo " ..  ERROR"
-        fi
-      fi
-      [ -n "$verbose" ] && echo
-      [ $res -eq 0 ] && echo "$meta" >> "$WORK_DIR/${role}.${task}.$timestampact/log"
-      return $res
     else
-      echo "Error parsing the meta: $meta"
-      proper_exit 1 113
+      if [ -n "$use_color" ] ; then
+        [ $res -eq 0 ] && printf " ..  \033[01;32mSuccess\033[0m\n" || printf " ..  \033[01;31mError\033[0m\n"
+      else
+        [ $res -eq 0 ] && echo " ..  Success" || echo " ..  ERROR"
+      fi
     fi
+    [ -n "$verbose" ] && echo
+    return $res
+  else
+    [ -n "$use_color" ] && printf "\033[01;31m"
+    echo "Error parsing the meta: $meta"
+    [ -n "$use_color" ] && printf "\033[0m"
+    [ -z "$dry" ] && proper_exit 1 124
   fi
 }
 
