bits

diff --git a/deployment/metaexec b/deployment/metaexec
--- a/deployment/metaexec
+++ b/deployment/metaexec
@@ -19,7 +19,7 @@ rpath=${0%/*}
 #*/
 
 run_meta() {
-  [ `grep -c "^${1}$" "${WORK_DIR}/${role}.${task}.${timestampact}/log"` -ne 0 ] && echo "Skipping: $1" | tee -a "${rpath}/../deploy.log" && return 0
+  [ `grep -c "^${1}$" "${WORK_DIR}/${role}.${task}.${timestampact}/log"` -ne 0 ] && echo "Skipping: $1" | tee -a "$LOG" && return 0
   [ -n "$use_color" ] && printf "\033[01;36mMETA: \033[00;36m$1\033[0m" || printf "META: $1"
   if [ -n "$test" -o -n "$dry" ] ; then
     metatype=`echo $1 | awk '{print $1}'`
@@ -166,7 +166,8 @@ do
 done
 IFS=$IFS1
 
-[ -n "$debug" ] && verbose="yes"
+LOG="$M_ROOT/logs/deploy.log"
+[ -n "$debug" ] && verbose="yes" && debug=true
 export verbose debug
 [ -n "$repeat" ] && timestamp=repeat
 
@@ -301,11 +302,18 @@ if [ `echo $ip | grep -c "^$localip$"` -eq 0 ] ; then
   [ -f "${rpath}/../keys/${KEY}" ] || KEY=${KEY}.pem
   [ ! -f "${rpath}/../keys/${KEY}" ] && echo "Key $KEY not found" && exit 1
   #SSH="$SSH -i \"${rpath}/../keys/${KEY}\" -o StrictHostKeyChecking=no"
+  $debug && log "ensuring the target server $ip is accessible"
   if [ -z "$test" -a -z "$list" -a -n "$ip" ] ; then
     for ((k=0; k<3; k++)); do
       $SSH -i "${rpath}/../keys/${KEY}" -o StrictHostKeyChecking=no $ip echo >/dev/null
-      [ $? -ne 0 ] && echo "Unable to login to the server $ip using the key ${rpath}/../keys/${KEY}, trying again...">>"${rpath}"/../logs/cloud.log && loggedin=false || loggedin=true
-      sleep 30
+      if [ $? -ne 0 ]; then
+        echo "Unable to login to the server $ip using the key ${rpath}/../keys/${KEY}, trying again...">>"$LOG"
+        loggedin=false
+        sleep 30
+      else
+        loggedin=true
+        break
+      fi
     done
     $loggedin || exit 1
   fi
@@ -317,6 +325,7 @@ if [ `echo $ip | grep -c "^$localip$"` -eq 0 ] ; then
     
     if [ -z "$timestamp" ];then
     ## Saving arguments to make re-run simpler
+      $debug && log "saving command-line arguments for possible repeat of the sequence"
       IFS2=$IFS ; IFS=$' \t\n'
       for option in `echo $possible_options | sed 's/,/ /g'`; do
         echo "${option}=`eval "echo \\$${option}"`" >> "${WORK_DIR}/${role}.${task}.${timestampact}/ARGV"
