bits

diff --git a/deployment/metaexec b/deployment/metaexec
--- a/deployment/metaexec
+++ b/deployment/metaexec
@@ -299,10 +299,10 @@ if [ `echo $ip | grep -c "^$localip$"` -eq 0 ] ; then
   if [ -z "$test" -a -z "$list" -a -n "$ip" ] ; then
     for ((k=0; k<3; k++)); do
       $SSH -i "${rpath}/../keys/${KEY}" -o StrictHostKeyChecking=no $ip echo >/dev/null
-      [ $? -ne 0 ] && echo "Unable to login to the server $ip using the key ${rpath}/../keys/${KEY}, trying again...">>"${rpath}"/../logs/cloud.log
-      sleep 5
+      [ $? -ne 0 ] && echo "Unable to login to the server $ip using the key ${rpath}/../keys/${KEY}, trying again...">>"${rpath}"/../logs/cloud.log && loggedin=false || loggedin=true
+      sleep 30
     done
-    [ $? -ne 0 ] && exit 1
+    $loggedin || exit 1
   fi
   #[ -z "$SCP" ] && echo "SCP not found!" && exit 1
 
