metaexec and start_server to work together

diff --git a/deployment/metaexec b/deployment/metaexec
--- a/deployment/metaexec
+++ b/deployment/metaexec
@@ -157,10 +157,11 @@ if [ -n "$ip" ] ; then
   fi
 fi
 if [ -z "$ip" ] && [ -n "$cloud" ] ; then
-  ip=`"${rpath}/cloud/${cloud}/start_server --cluster=${cluster} --return=ip"`
+  ip=`${rpath}/../cloud/${cloud}/start_server --cluster=${cluster} --return=ip`
+  [ -z "$ip" ] && echo "Was unable either to start a cloud server in the cloud $cloud or to get its IP address." && exit 1
 fi
-if [ -z "$cloud" -a -z "$ip" -a -z "$cluster" ] ; then
-  echo "One of ip, cloud or cluster must be defined"
+if [ -z "$cloud" -a -z "$ip" ] ; then
+  echo "One of ip or cloud must be defined"
   exit 1
 fi
 if [ -z "$role" ] ; then
diff --git a/deployment/test_meta b/deployment/test_meta
--- a/deployment/test_meta
+++ b/deployment/test_meta
@@ -91,7 +91,7 @@ if [ -z "$role" ] ; then
 fi
 if [ -z "$flavor" ] ; then
   flavor=`grep ^$cluster\| "${rpath}/../conf/clusters.conf" | cut -d'|' -f11`
-  [ -z "$flavor" ] && echo "Unable to find the flavor of this cluster/server OS. Define it or check if this cluster has a default flavor set in conf/cluster.conf" && exit 1
+  [ -z "$flavor" ] && echo "Unable to find the flavor of this cluster/server OS. Define it as a command-line option or check if this cluster has a default flavor set in conf/cluster.conf" && exit 1
 fi
 source "${ROLES_ROOT}/${role}/role.conf"
 IFS1=$IFS
@@ -99,6 +99,7 @@ IFS='
 '
 declare -i n
 n=0
+[ -e "${ROLES_ROOT}/${role}/meta.${task}" ] || RETVAL=255
 for meta in `cat "${ROLES_ROOT}/${role}/meta.${task}"` ; do # | grep -v ^# | grep -v ^$ | grep -v ^[[:space:]]*#`
   n+=1
   ([[ $meta =~ ^# ]] || [[ $meta =~ ^$ ]] || [[ $meta =~ ^[[:space:]]*# ]]) && continue
