graphs for all sorts of mongo

diff --git a/deployment/test_meta b/deployment/test_meta
--- a/deployment/test_meta
+++ b/deployment/test_meta
@@ -77,7 +77,9 @@ source "${rpath}/../conf/deployment.conf"
 M_ROOT=$(cd "${rpath}/../" && pwd)
 export PATH=${M_ROOT}/deployment:${M_ROOT}/cloud:${M_ROOT}/cloud/ec2:${M_ROOT}/helpers:${PATH}
 
-[ -z "$cluster" -a -z "$ip" ] && echo "One of --cluster or --ip options is necessary (ip should be present in servers.list if cluster is not defined)" && exit 1
+if [ -z "$role" -o -z "$flavor" ] ; then
+  [ -z "$cluster" -a -z "$ip" ] && echo "Either role or flavor is not defined. In this case either ip or cluster is necessary." && exit 1
+fi
 [ -z "$cluster" -a -n "$ip" ] && cluster=`grep ^$ip\| "${rpath}/../servers.list" | cut -d'|' -f5`
 [ -n "$cluster" -a -z "$ip" ] && ip="127.0.0.1"
 declare -i RETVAL
@@ -89,7 +91,7 @@ if [ -z "$role" ] ; then
 fi
 if [ -z "$flavor" ] ; then
   flavor=`grep ^$cluster\| "${rpath}/../conf/clusters.conf" | cut -d'|' -f11`
-  [ -z "$flavor" ] && echo "Unable to find the flavor of this cluster/server OS. Define it or check if this cluster has a default role set in conf/cluster.conf" && exit 1
+  [ -z "$flavor" ] && echo "Unable to find the flavor of this cluster/server OS. Define it or check if this cluster has a default flavor set in conf/cluster.conf" && exit 1
 fi
 source "${ROLES_ROOT}/${role}/role.conf"
 IFS1=$IFS
@@ -153,12 +155,19 @@ done
 echo
 IFS=$IFS1
 if [ $RETVAL -gt 0 ] ; then
+  [ $RETVAL -eq 1 ] && errors="error" || errors="errors"
   if [ -n "$use_color" ] ; then
     printf "\033[01;31mFound $RETVAL errors\033[00;39m\n"
   else
-    echo "Found $RETVAL errors"
+    echo "Found $RETVAL $errors"
   fi
   echo
+else
+  if [ -n "$use_color" ] ; then
+    printf "\033[01;32mTest passed\033[00;39m\n"
+  else
+    echo "Test passed"
+  fi
 fi
 exit $RETVAL
 
