rax v2 show_images

diff --git a/cloud/rackspaceV2/show_regions b/cloud/rackspaceV2/show_regions
--- a/cloud/rackspaceV2/show_regions
+++ b/cloud/rackspaceV2/show_regions
@@ -22,12 +22,7 @@ rpath=${0%/*}
 CURL=`which curl 2>/dev/null`
 [ -z "$CURL" ] && echo "Curl not found" && exit 1
 
-#debug=1
-
-[ -n "$debug" ] && debug=true || debug=false
-$debug && LOG="$M_ROOT/logs/show_images.log"
-
-possible_options="noupdate cloud"
+possible_options="cloud"
 necessary_options=""
 
 ARGV=`echo ${@} | sed 's/^--//;s/ --/|/g'`
@@ -78,16 +73,22 @@ authresp=`cat "$M_TEMP/auth.resp" 2>/dev/null`
 [ -z "$authresp" ] && try_auth
 
 name=`echo "$authresp" | grep '"name"|"cloudServersOpenStack"'`
-[ -z "$n" ] && echo "Error reading authentication response: name \"cloudServersOpenStack\" not found there" && proper_exit 81
+[ -z "$name" ] && echo "Error reading authentication response: name \"cloudServersOpenStack\" not found there" >&2 && proper_exit 81
 
 n=`echo "$name" | cut -s -d '/' -f4`
-[ `expr "$n" : ".*[^0-9]"` -ne 0 ] && echo "Error reading authentication response: cloudServersOpenStack service index is supposed to be a number, but it is $n" && proper_exit 84
+[ `expr "$n" : ".*[^0-9]"` -ne 0 ] && echo "Error reading authentication response: cloudServersOpenStack service index is supposed to be a number, but it is $n" >&2 && proper_exit 84
 
 regions=`echo "$authresp" | cut -sd'/' -f4- | grep "^$n/" | cut -sd'/' -f3- | grep -E '"region"|"publicURL"' | sort -n`
 
+rm "$M_TEMP/show_regions.resp"
+
 for ind in `echo "$regions" | cut -sd'/' -f1 | uniq` ; do
   region=`echo "$regions" | grep "^$ind/"`
-  echo "${n}: `echo "$region" | grep '"region"' | cut -sd'|' -f2 | tr -d '"'` `echo "$region" | grep '"publicURL"' | cut -sd'|' -f2 | tr -d '"'`"
+  name=`echo "$region" | grep '"region"' | cut -sd'|' -f2 | tr -d '"'`
+  url=`echo "$region" | grep '"publicURL"' | cut -sd'|' -f2 | tr -d '"'`
+  echo "${ind}:   $name   $url"
+  echo "$name|$url" >> "$M_TEMP/show_regions.resp"
+  unset name url
 done
 
 
