adjustments to changes in instance info output

diff --git a/cloud/ganeti/cd2vm b/cloud/ganeti/cd2vm
--- a/cloud/ganeti/cd2vm
+++ b/cloud/ganeti/cd2vm
@@ -42,7 +42,9 @@ disksize="`echo "$vmini" | cut -d'|' -f3`"
 # now when we know that disk does exist, we can use a heavier tool to find its
 # file or device
 
-disk=`"$M_ROOT/cloud/$CLOUD"/get_server_details --name="$vm" | grep '^State/Disks/disk/0/on primary' | cut -d'|' -f2 | tail -1`
+disk=`"$M_ROOT/cloud/$CLOUD"/get_server_details --name="$vm" | grep '^Disks/disk/0/on primary' | cut -d'|' -f2 | tail -1`
+[ -z "$disk" ] && disk=`"$M_ROOT/cloud/$CLOUD"/get_server_details --name="$vm" | grep '^State/Disks/disk/0/on primary' | cut -d'|' -f2 | tail -1`
+[ -z "$disk" ] && log "unable to get disk details" && exit 1
 disk=`expr "$disk" : "\(.*\) ("`
 
 if [ ! -b "$disk" ]; then
