bits & fixes

diff --git a/cloud/ganeti/create_node b/cloud/ganeti/create_node
--- a/cloud/ganeti/create_node
+++ b/cloud/ganeti/create_node
@@ -164,7 +164,7 @@ request() {
   if [ -z "$hvparams" ]; then
     # if no -H provided at all, adding it with the default hypervisor
     hvname=$hvdef
-    [ -n "$vnc" ] && hvparams="${VNC}"
+    [ -n "$vnc" ] && hvparams="$VNC"
   else
     hvparams1=`echo "$hvparams" | cut -sd':' -f2 | tr -d ' '`
     # is there anything after colon?
@@ -268,17 +268,18 @@ res=`check_cluster_limit $cluster`
 [ -z "$ip" ] && ip=`find_ip` && log "IP that will be used: $ip"
 [ -z "$ip" ] && proper_exit 4 186
 
-thekey=`"$M_ROOT"/helpers/find_key cluster $cluster`
-[ $? -ne 0 ] && echo "Key for cluster $cluster not found" && proper_exit 1 189
-[ -f "${thekey}.pub" ] && PUBLIC_KEY="${thekey}.pub"
-[ -z "$PUBLIC_KEY" ] && [ -f "${thekey}.pem.pub" ] && PUBLIC_KEY="${thekey}.pem.pub"
-[ -z "$PUBLIC_KEY" ] && [ -f "$HOME/.ssh/id_dsa.pub" ] && PUBLIC_KEY="$HOME/.ssh/id_dsa.pub"
-[ -z "$PUBLIC_KEY" ] && [ -f "$HOME/.ssh/id_rsa.pub" ] && PUBLIC_KEY="$HOME/.ssh/id_rsa.pub"
-[ -z "$PUBLIC_KEY" ] && [ -f "$HOME_ORIG/.ssh/id_dsa.pub" ] && PUBLIC_KEY="$HOME_ORIG/.ssh/id_dsa.pub"
-[ -z "$PUBLIC_KEY" ] && [ -f "$HOME_ORIG/.ssh/id_rsa.pub" ] && PUBLIC_KEY="$HOME_ORIG/.ssh/id_rsa.pub"
-[ -z "$PUBLIC_KEY" ] && log "No public key found. Tried $M_ROOT/keys/${thekey}.\*, public keys from $HOME/.ssh and $HOME_ORIG/.ssh" && exit 1
-log "SSH public key $PUBLIC_KEY is going to be injected"
-
+if [ -z "$cdrom" ]; then
+  thekey=`"$M_ROOT"/helpers/find_key cluster $cluster`
+  [ $? -ne 0 ] && echo "Key for cluster $cluster not found" && proper_exit 1 189
+  [ -f "${thekey}.pub" ] && PUBLIC_KEY="${thekey}.pub"
+  [ -z "$PUBLIC_KEY" ] && [ -f "${thekey}.pem.pub" ] && PUBLIC_KEY="${thekey}.pem.pub"
+  [ -z "$PUBLIC_KEY" ] && [ -f "$HOME/.ssh/id_dsa.pub" ] && PUBLIC_KEY="$HOME/.ssh/id_dsa.pub"
+  [ -z "$PUBLIC_KEY" ] && [ -f "$HOME/.ssh/id_rsa.pub" ] && PUBLIC_KEY="$HOME/.ssh/id_rsa.pub"
+  [ -z "$PUBLIC_KEY" ] && [ -f "$HOME_ORIG/.ssh/id_dsa.pub" ] && PUBLIC_KEY="$HOME_ORIG/.ssh/id_dsa.pub"
+  [ -z "$PUBLIC_KEY" ] && [ -f "$HOME_ORIG/.ssh/id_rsa.pub" ] && PUBLIC_KEY="$HOME_ORIG/.ssh/id_rsa.pub"
+  [ -z "$PUBLIC_KEY" ] && log "No public key found. Tried $M_ROOT/keys/${thekey}.\*, public keys from $HOME/.ssh and $HOME_ORIG/.ssh" && exit 1
+  log "SSH public key $PUBLIC_KEY is going to be injected"
+fi
 # Ganeti cluster must be running, and this script can run on master node only
 $GNTC master-ping
 [ $? -ne 0 ] && echo "Error pinging Ganeti cluster. Is it running?" && proper_exit 1 283
@@ -295,78 +296,91 @@ log "using OSPATH $OSPATH"
 OSNAME=`cat "$M_ROOT/conf/clusters.conf" | grep ^${cluster}\| | cut -d'|' -f5 | cut -d'+' -f1`
 [ -z "$OSNAME" ] && log "Unable to find OS in clusters.conf for cluster $cluster" && proper_exit 1 295
 
-if [ -d "$OSPATH/$OSNAME" ]; then
-  cp -ru "$M_ROOT/cloud/ganeti/os-skeleton/"* "$OSPATH/$OSNAME/"
-else
-  cp -r "$M_ROOT/cloud/ganeti/os-skeleton" "$OSPATH/$OSNAME"
+if [ -z "$cdrom" ]; then
+  if [ -d "$OSPATH/$OSNAME" ]; then
+    cp -ru "$M_ROOT/cloud/ganeti/os-skeleton/"* "$OSPATH/$OSNAME/"
+  else
+    cp -r "$M_ROOT/cloud/ganeti/os-skeleton" "$OSPATH/$OSNAME"
+  fi
+  log "OS building scripts placed in $OSPATH/$OSNAME"
+  prepare_file "$M_ROOT/cloud/ganeti/os-skeleton/common.sh" "$OSPATH/$OSNAME/common.sh"
+
+  OS_DEFAULT_CONF=`cat "$OSPATH/$OSNAME/common.sh" | grep 'DEFAULT_FILE=' | cut -d'=' -f2 | cut -d'"' -f2`
+
+  [ -f "$OS_DEFAULT_CONF" ] && source "$OS_DEFAULT_CONF" && log "OS default configuration $OS_DEFAULT_CONF sourced" || log "OS default configuration $OS_DEFAULT_CONF not found"
+
+  CUSTOMIZE_DIR="$GANETI_CONF_FOLDER/instance-$OSNAME/hooks"
+  VARIANTS_DIR="$GANETI_CONF_FOLDER/instance-$OSNAME/variants"
+
+  IMAGE_DIR="$M_ROOT/cloud/ganeti/os-images"
+  IMAGE_FILE="$IMAGE_DIR/${OSNAME}.img"
+
+  echo -e "CUSTOMIZE_DIR=$CUSTOMIZE_DIR\nVARIANTS_DIR=$VARIANTS_DIR\nCDINSTALL=no\nIMAGE_FILE=$IMAGE_FILE" > "$M_TEMP/vars"
+
+  [ -d "$CUSTOMIZE_DIR" ] || install -d "$CUSTOMIZE_DIR"
+  [ -d "$VARIANTS_DIR" ] || install -d "$VARIANTS_DIR"
+  [ -d "$IMAGE_DIR" ] || install -d "$IMAGE_DIR"
+
+  [ -z "$HOOKS_DIR" ] && HOOKS_DIR="$CUSTOMIZE_DIR"
+  [ -z "$HOOKS_DIR" ] && HOOKS_DIR="$M_TEMP/hooks"
+  [ -d "$HOOKS_DIR" ] || install -d "$HOOKS_DIR"
+  log "HOOKS_DIR: $HOOKS_DIR"
+
+  [ ! -f "$IMAGE_FILE" ] && [ -z "$makedisk" ] && log "Image file does not exist!" && proper_exit 1 243
+  export CUSTOMIZE_DIR VARIANTS_DIR IMAGE_DIR HOOKS_DIR IMAGE_FILE
+
+
+  [ -z "$GANETI_GATEWAY" ] && GANETI_GATEWAY=`find_gateway`
+
+  broadcast=`find_broadcast`
+  log "gateway: $GANETI_GATEWAY  broadcast: $broadcast"
+
+  flavor=`grep ^$cluster\| "$M_ROOT/conf/clusters.conf" | cut -d'|' -f11 | tail -1`
+  flfound=false
+
+  if $GUESS_OS ; then
+    for flvar in gentoo debian redhat centos fedora suse mint ubuntu lfs ; do
+      [ `echo "$flavor" | grep -c -i "$flvar"` -ne 0 ] && flfound=true && break
+    done
+  fi
+  $flfound || flvar=`grep ^$cluster\| "$M_ROOT/conf/clusters.conf" | cut -d'|' -f5 | cut -d'+' -f1 | tail -1`
+
+  case $flvar in
+    debian*|ubuntu*|mint*)
+      export OPERATING_SYSTEM=debian
+      prepare_file "$rpath/network_if.debian.tmpl" "$M_TEMP/interfaces"
+      [ $? -eq 0 ] && log "$M_TEMP/interfaces prepared" || log "error preparing $M_TEMP/interfaces"
+      prepare_file "$rpath/network_if.debian" "$M_TEMP/network"
+      [ $? -eq 0 ] && log "$M_TEMP/network created based on template for Debian" || log "error preparing $M_TEMP/network"
+      ;;
+    redhat*|centos*|fedora*)
+      export OPERATING_SYSTEM=redhat
+      prepare_file "$rpath/network_if.redhat.tmpl" "$M_TEMP/interfaces"
+      [ $? -eq 0 ] && log "$M_TEMP/interfaces prepared" || log "error preparing $M_TEMP/interfaces"
+      prepare_file "$rpath/network_if.redhat" "$M_TEMP/network"
+      [ $? -eq 0 ] && log "$M_TEMP/network created based on template for Redhat" || log "error preparing $M_TEMP/network"
+      ;;
+    gentoo*)
+      export OPERATING_SYSTEM=gentoo
+      prepare_file "$rpath/network_if.gentoo.tmpl" "$M_TEMP/interfaces"
+      [ $? -eq 0 ] && log "$M_TEMP/interfaces prepared" || log "error preparing $M_TEMP/interfaces"
+      prepare_file "$rpath/network_if.gentoo" "$M_TEMP/network"
+      [ $? -eq 0 ] && log "$M_TEMP/network created based on template for Gentoo" || log "error preparing $M_TEMP/network"
+      ;;
+    *)
+      export OPERATING_SYSTEM=unknown
+      prepare_file "$rpath/network_if.${flvar}.tmpl" "$M_TEMP/interfaces"
+      [ $? -eq 0 ] && log "$M_TEMP/interfaces prepared" || log "error preparing $M_TEMP/interfaces"
+      prepare_file "$rpath/network_if.${flvar}" "$M_TEMP/network"
+      [ $? -eq 0 ] && log "$M_TEMP/network created based on template for $flvar" || log "error preparing $M_TEMP/network"
+      ;;
+  esac
+
+  # installing software via chroot proved to be unreliable
+
+  cp "$M_TEMP/network" "$HOOKS_DIR/"
+  chmod 755 "$HOOKS_DIR/network"
 fi
-log "OS building scripts placed in $OSPATH/$OSNAME"
-prepare_file "$M_ROOT/cloud/ganeti/os-skeleton/common.sh" "$OSPATH/$OSNAME/common.sh"
-
-OS_DEFAULT_CONF=`cat "$OSPATH/$OSNAME/common.sh" | grep 'DEFAULT_FILE=' | cut -d'=' -f2 | cut -d'"' -f2`
-
-[ -f "$OS_DEFAULT_CONF" ] && source "$OS_DEFAULT_CONF" && log "OS default configuration $OS_DEFAULT_CONF sourced" || log "OS default configuration $OS_DEFAULT_CONF not found"
-
-CUSTOMIZE_DIR="$GANETI_CONF_FOLDER/instance-$OSNAME/hooks"
-VARIANTS_DIR="$GANETI_CONF_FOLDER/instance-$OSNAME/variants"
-
-IMAGE_DIR="$M_ROOT/cloud/ganeti/os-images"
-IMAGE_FILE="$IMAGE_DIR/${OSNAME}.img"
-
-echo -e "CUSTOMIZE_DIR=$CUSTOMIZE_DIR\nVARIANTS_DIR=$VARIANTS_DIR\nCDINSTALL=no\nIMAGE_FILE=$IMAGE_FILE" > "$M_TEMP/vars"
-
-[ -d "$CUSTOMIZE_DIR" ] || install -d "$CUSTOMIZE_DIR"
-[ -d "$VARIANTS_DIR" ] || install -d "$VARIANTS_DIR"
-[ -d "$IMAGE_DIR" ] || install -d "$IMAGE_DIR"
-
-[ -z "$HOOKS_DIR" ] && HOOKS_DIR="$CUSTOMIZE_DIR"
-[ -z "$HOOKS_DIR" ] && HOOKS_DIR="$M_TEMP/hooks"
-[ -d "$HOOKS_DIR" ] || install -d "$HOOKS_DIR"
-log "HOOKS_DIR: $HOOKS_DIR"
-
-[ ! -f "$IMAGE_FILE" ] && [ -z "$makedisk" ] && log "Image file does not exist!" && proper_exit 1 243
-export CUSTOMIZE_DIR VARIANTS_DIR IMAGE_DIR HOOKS_DIR IMAGE_FILE
-[ -z "$GANETI_GATEWAY" ] && GANETI_GATEWAY=`find_gateway`
-
-broadcast=`find_broadcast`
-log "gateway: $GANETI_GATEWAY  broadcast: $broadcast"
-
-flavor=`grep ^$cluster\| "$M_ROOT/conf/clusters.conf" | cut -d'|' -f11 | tail -1`
-flfound=false
-
-if $GUESS_OS ; then
-  for flvar in gentoo debian redhat centos fedora suse mint ubuntu lfs ; do
-    [ `echo "$flavor" | grep -c -i "$flvar"` -ne 0 ] && flfound=true && break
-  done
-fi
-$flfound || flvar=`grep ^$cluster\| "$M_ROOT/conf/clusters.conf" | cut -d'|' -f5 | cut -d'+' -f2 | tail -1`
-
-case $flvar in
-  debian|ubuntu|mint)
-    prepare_file "$rpath/network_if.debian.tmpl" "$M_TEMP/interfaces"
-    [ $? -eq 0 ] && log "$M_TEMP/interfaces prepared" || log "error preparing $M_TEMP/interfaces"
-    prepare_file "$rpath/network_if.debian" "$M_TEMP/network"
-    [ $? -eq 0 ] && log "$M_TEMP/network created based on template for Debian" || log "error preparing $M_TEMP/network"
-    ;;
-  redhat|centos|fedora)
-    prepare_file "$rpath/network_if.redhat.tmpl" "$M_TEMP/interfaces"
-    [ $? -eq 0 ] && log "$M_TEMP/interfaces prepared" || log "error preparing $M_TEMP/interfaces"
-    prepare_file "$rpath/network_if.redhat" "$M_TEMP/network"
-    [ $? -eq 0 ] && log "$M_TEMP/network created based on template for Redhat" || log "error preparing $M_TEMP/network"
-    ;;
-  *)
-    prepare_file "$rpath/network_if.${flvar}.tmpl" "$M_TEMP/interfaces"
-    [ $? -eq 0 ] && log "$M_TEMP/interfaces prepared" || log "error preparing $M_TEMP/interfaces"
-    prepare_file "$rpath/network_if.${flvar}" "$M_TEMP/network"
-    [ $? -eq 0 ] && log "$M_TEMP/network created based on template for $flvar" || log "error preparing $M_TEMP/network"
-    ;;
-esac
-export OPERATING_SYSTEM=$flvar
-
-# installing software via chroot proved to be unreliable
-
-cp "$M_TEMP/network" "$HOOKS_DIR/"
-chmod 755 "$HOOKS_DIR/network"
 
 if [ -z "$test" ]; then
   request $verbose
@@ -389,7 +403,7 @@ if [ -z "$test" ]; then
       proper_exit 1 388
     fi
   else
-    log "Timeout while waiting for the node is up"
+    log "Timeout while waiting for the node"
     proper_exit 1 392
   fi
 
@@ -409,7 +423,7 @@ fi
 
 $SSHK -q -R "$ip" >/dev/null
 
-# if VM booted up from cdrom, no ssh node there
+# if VM booted up from cdrom, no ssh there
 if [ -z "$cdrom" ]; then
   if [ -f "$thekey" ]; then
     $SSH -i "$thekey" -o StrictHostKeyChecking=no $ip echo 2>/dev/null
@@ -465,5 +479,5 @@ fi
 
 "$M_ROOT"/cloud/common/update_hosts_file && log "/etc/hosts updated" || log "error updating /etc/hosts"
 
-proper_exit $exit_status 467
+proper_exit $exit_status 468
 
