stop_server to remove host from balancing

diff --git a/cloud/ganeti/start_server b/cloud/ganeti/start_server
--- a/cloud/ganeti/start_server
+++ b/cloud/ganeti/start_server
@@ -277,6 +277,15 @@ $SSHK -q -R "$ip" >/dev/null
 [ ! -f "$thekey" ] && thekey="$HOME/.ssh/id_dsa.pub"
 [ -f "$thekey" ] && $SSH -i $thekey -o StrictHostKeyChecking=no $ip echo 2>/dev/null &&
 $SSH -i $thekey -o StrictHostKeyChecking=no $name echo 2>/dev/null
+if [ $? -ne 0 ]; then
+  echo "Unable to login to the server $ip using the key ${rpath}/../keys/${KEY}, trying again...">>"${rpath}"/../logs/cloud.log
+  for ((k=0; k<3; k++)); do
+    $SSH -i "${rpath}/../keys/${KEY}" -o StrictHostKeyChecking=no $ip echo >/dev/null
+    [ $? -eq 0 ] && $SSH -i "${rpath}/../keys/${KEY}" -o StrictHostKeyChecking=no $name echo >/dev/null && break
+    sleep 5
+  done
+fi
+[ $? -ne 0 ] && exit 1
 
 if [ -n "$return" ]; then
   echo
