bits

diff --git a/cloud/ganeti/start_server b/cloud/ganeti/start_server
--- a/cloud/ganeti/start_server
+++ b/cloud/ganeti/start_server
@@ -17,7 +17,7 @@
 rcommand=${0##*/}
 rpath=${0%/*}
 #*/
-
+[ -z "$M_ROOT" ] && M_ROOT=$(readlink -f "$rpath/../../")
 GNTI=`which gnt-instance 2>/dev/null`
 GNTC=`which gnt-cluster 2>/dev/null`
 ROUTE=`which route 2>/dev/null`
@@ -28,7 +28,7 @@ IPR2=`which ip 2>/dev/null`
 possible_options="region flavor cluster image name return verbose test"
 necessary_options="cluster"
 
-LOG="${rpath}"/../../logs/cloud.log
+LOG="$M_ROOT/logs/cloud.log"
 SSHK=`which ssh-keygen 2>/dev/null`
 SSH=`which ssh 2>/dev/null`
 ARGV=`echo ${@} | sed 's/^--//' | sed 's/ --/|/g'`
@@ -60,11 +60,11 @@ if [[ found -eq 1 ]]; then
   exit 1
 fi
 
-source "${rpath}/../../conf/mon.conf"
-source "${rpath}/../../conf/cloud.conf"
+source "$M_ROOT/conf/mon.conf"
+source "$M_ROOT/conf/cloud.conf"
 [ -z "$GANETI_NETWORK" ] && echo "Define GANETI_NETWORK in conf/cloud.conf, please" && exit 1
-source "${rpath}/../../lib/functions.sh"
-source "${rpath}/../../lib/cloud_functions.sh"
+source "$M_ROOT/lib/functions.sh"
+source "$M_ROOT/lib/cloud_functions.sh"
 
 M_TEMP="$M_TEMP/cloud/ganeti"
 install -d "$M_TEMP"
@@ -74,7 +74,7 @@ install -d "$M_TEMP"
 find_ip() {
   class=${GANETI_NETWORK%.*}
   [ -z "$class" ] && class="10.1.1"
-  maxip=`cat "${rpath}/../../servers.list" | cut -d'|' -f1 | grep ^$class | sort | uniq | tail -1`
+  maxip=`cat "$M_ROOT/servers.list" | cut -d'|' -f1 | grep ^$class | sort | uniq | tail -1`
   maxip=${maxip##*.}
   if [ -n "$maxip" ]; then
     [ "$maxip" == "254" ] && echo "No more IPs available!" && exit 1
@@ -99,7 +99,7 @@ find_broadcast() {
 save_details() {
   [ -n "$1" ] && echo "Saving details..."
   echo -e "\n`date`\n\nCluster|$cluster\nName|$name\nIP|$ip\n" >> "${rpath}/../ganeti.log"
-  echo "${ip}|${thekey}||${name}|${cluster}" >> "${rpath}/../../servers.list"
+  echo "${ip}|${thekey}||${name}|${cluster}" >> "$M_ROOT/servers.list"
   return 0
 }
 
@@ -121,9 +121,9 @@ wait_ready() {
 }
 
 request() {
-  node=`cat "${rpath}/../../conf/clusters.conf" | grep ^${cluster}\| | cut -d'|' -f3`
-  ios=`cat "${rpath}/../../conf/clusters.conf" | grep ^${cluster}\| | cut -d'|' -f5`
-  iparams=`cat "${rpath}/../../conf/clusters.conf" | grep ^${cluster}\| | cut -d'|' -f6`
+  node=`cat "$M_ROOT/conf/clusters.conf" | grep ^${cluster}\| | cut -d'|' -f3`
+  ios=`cat "$M_ROOT/conf/clusters.conf" | grep ^${cluster}\| | cut -d'|' -f5`
+  iparams=`cat "$M_ROOT/conf/clusters.conf" | grep ^${cluster}\| | cut -d'|' -f6`
   sed -i "/^${ip}/d" /etc/hosts
   echo "$ip $name" >> /etc/hosts
   #echo "$GNTI add -n $node -o $iparams $name"
@@ -181,14 +181,14 @@ res=`check_cluster_limit $verbose`
 [ -z "$ip" ] && ip=`find_ip` && log "IP that will be used: $ip"
 [ -z "$ip" ] && exit 4
 
-thekey=`cat "${rpath}/../../conf/clusters.conf" | grep ^$cluster\| | cut -d'|' -f2`
-[ -f "${rpath}/../../keys/${thekey}.pub" ] && PUBLIC_KEY="${rpath}/../../keys/${thekey}.pub"
-[ -z "$PUBLIC_KEY" ] && [ -f "${rpath}/../../keys/${thekey}.pem.pub" ] && PUBLIC_KEY="${rpath}/../../keys/${thekey}.pem.pub"
+thekey=`cat "$M_ROOT/conf/clusters.conf" | grep ^$cluster\| | cut -d'|' -f2`
+[ -f "$M_ROOT/keys/${thekey}.pub" ] && PUBLIC_KEY="$M_ROOT/keys/${thekey}.pub"
+[ -z "$PUBLIC_KEY" ] && [ -f "$M_ROOT/keys/${thekey}.pem.pub" ] && PUBLIC_KEY="$M_ROOT/keys/${thekey}.pem.pub"
 [ -z "$PUBLIC_KEY" ] && [ -f ${HOME}/.ssh/id_dsa.pub ] && PUBLIC_KEY=${HOME}/.ssh/id_dsa.pub
 [ -z "$PUBLIC_KEY" ] && [ -f ${HOME}/.ssh/id_rsa.pub ] && PUBLIC_KEY=${HOME}/.ssh/id_rsa.pub
 [ -z "$PUBLIC_KEY" ] && [ -f ${HOME_ORIG}/.ssh/id_dsa.pub ] && PUBLIC_KEY=${HOME_ORIG}/.ssh/id_dsa.pub
 [ -z "$PUBLIC_KEY" ] && [ -f ${HOME_ORIG}/.ssh/id_rsa.pub ] && PUBLIC_KEY=${HOME_ORIG}/.ssh/id_rsa.pub
-[ -z "$PUBLIC_KEY" ] && log "No public key found. Tried ${rpath}/../../keys/${thekey}.\*, public keys from ${HOME}/.ssh and ${HOME_ORIG}/.ssh" && exit 1
+[ -z "$PUBLIC_KEY" ] && log "No public key found. Tried $M_ROOT/keys/${thekey}.\*, public keys from ${HOME}/.ssh and ${HOME_ORIG}/.ssh" && exit 1
 
 # Ganeti cluster must be running, and this script can run on master node only
 $GNTC master-ping
@@ -198,12 +198,12 @@ OSPATH=`$GNTC info | grep 'OS search path'`
 OSPATH="${OSPATH##*: }"
 [ -z "$OSPATH" ] && OSPATH="$GANETI_FOLDERS_ROOT/os"
 # OS required for the new server
-OSNAME=`cat "${rpath}/../../conf/clusters.conf" | grep ^${cluster}\| | cut -d'|' -f5 | cut -d'+' -f1`
+OSNAME=`cat "$M_ROOT/conf/clusters.conf" | grep ^${cluster}\| | cut -d'|' -f5 | cut -d'+' -f1`
 [ -z "$OSNAME" ] && log "Unable to find OS for cluster $cluster" && exit 1
 # for the default bootstrap OS
 OS_DEFAULT_CONF=`cat "$OSPATH/$OSNAME/common.sh" | grep 'DEFAULT_FILE=' | cut -d'=' -f2 | cut -d'"' -f2`
 
-[ -f "$OS_DEFAULT_CONF" ] && source "$OS_DEFAULT_CONF" && log "$OS_DEFAULT_CONF sourced" || log "$OS_DEFAULT_CONF not found"
+[ -f "$OS_DEFAULT_CONF" ] && source "$OS_DEFAULT_CONF" && log "OS default configuration $OS_DEFAULT_CONF sourced" || log "OS default configuration $OS_DEFAULT_CONF not found"
 
 CUSTOMIZE_DIR="$GANETI_CONF_FOLDER/instance-$OSNAME/hooks"
 VARIANTS_DIR="$GANETI_CONF_FOLDER/instance-$OSNAME/variants"
@@ -232,7 +232,7 @@ prepare_file "$rpath/network_if.debian.tmpl" "$M_TEMP/interfaces"
 prepare_file "$rpath/network_if.debian" "$M_TEMP/network"
 [ $? -eq 0 ] && log "$M_TEMP/network prepared" || log "error preparing $M_TEMP/network"
 # installing software via chroot has proven to be unreliable
-cp "$rpath/setup.sh.debian" "$M_TEMP/setup.sh"
+
 cp "$M_TEMP/network" "$HOOKS_DIR/"
 chmod 755 "$HOOKS_DIR/network"
 
@@ -276,21 +276,30 @@ else
 fi
 
 $SSHK -q -R "$ip" >/dev/null
-[ ! -f "${rpath}/../../keys/$thekey" ] && thekey="${thekey}.pem"
-[ ! -f "${rpath}/../../keys/$thekey" ] && thekey="$HOME/.ssh/id_rsa.pub"
-[ ! -f "$thekey" ] && thekey="$HOME/.ssh/id_dsa.pub"
-[ -f "$thekey" ] && $SSH -i "$thekey" -o StrictHostKeyChecking=no $ip echo 2>/dev/null
-
-if [ $? -ne 0 ]; then
-  log "($CLOUD) Unable to login to the server $ip using the key $thekey, trying again..."
-  for ((k=0; k<3; k++)); do
-    $SSH -i "$thekey" -o StrictHostKeyChecking=no $ip echo >/dev/null
-    [ $? -eq 0 ] && $SSH -i "$thekey" -o StrictHostKeyChecking=no $name echo >/dev/null && break
-    sleep 5
-  done
+[ ! -f "$M_ROOT/keys/$thekey" ] && thekey="${thekey}.pem"
+if [ ! -f "$M_ROOT/keys/$thekey" ]; then
+  if [ -n "$HOME_ORIG" ]; then
+    thekey1="$HOME_ORIG/.ssh/id_rsa.pub"
+    [ ! -f "$thekey1" ] && thekey1="$HOME_ORIG/.ssh/id_dsa.pub"
+  fi
+  thekey2="$HOME/.ssh/id_rsa.pub"
+  [ ! -f "$thekey2" ] && thekey2="$HOME/.ssh/id_rsa.pub"
+  [ -f "$thekey1" ] && thekey=$thekey1 || thekey=$thekey2
 fi
-[ $? -ne 0 ] && exit 1
-
+if [ -f "$thekey" ]; then
+  $SSH -i "$thekey" -o StrictHostKeyChecking=no $ip echo 2>/dev/null
+  if [ $? -ne 0 ]; then
+    log "($CLOUD) Unable to login to the server $ip using the key $thekey, trying again..."
+    for ((k=0; k<3; k++)); do
+      $SSH -i "$thekey" -o StrictHostKeyChecking=no $ip echo >/dev/null
+      [ $? -eq 0 ] && $SSH -i "$thekey" -o StrictHostKeyChecking=no $name echo >/dev/null && break
+      sleep 5
+    done
+  fi
+  [ $? -ne 0 ] && exit 1
+else
+  log "($CLOUD) WARNING: key not found, unable to test login!"
+fi
 if [ -n "$return" ]; then
   echo
   for ret in `echo $return | tr ',' ' '`; do
