ganeti bits

diff --git a/cloud/ganeti/start_server b/cloud/ganeti/start_server
--- a/cloud/ganeti/start_server
+++ b/cloud/ganeti/start_server
@@ -75,8 +75,13 @@ source "$M_ROOT/lib/cloud_functions.sh"
 if [ -n "$cdrom" ]; then
   [ "$cdrom" == "yes" ] && echo -e "\nOption --cdrom assumes path to ISO image:\n  --cdrom=/path/to/image" && exit 1
   makedisk="yes"
-  [ `echo "$cdrom" | cut -b1` != "/" ] && log "restoring absolute path required by Ganeti: $cdrom --> $PWD/$cdrom" && cdrom="$PWD/$cdrom"
-  [ ! -e "$cdrom" ] && log "\nFile $cdrom does not exist" && exit 1
+  [ `echo "$cdrom" | cut -b1` != "/" ] && log "restoring absolute path required by Ganeti:"
+  if [ -f "$PWD/$cdrom" ]; then
+    cdrom="$PWD/$cdrom" && log "  $PWD/$cdrom"
+  elif [ -f "$M_ROOT/cloud/ganeti/os-images/$cdrom" ]; then
+    cdrom="$M_ROOT/cloud/ganeti/os-images/$cdrom" && log "  $M_ROOT/cloud/ganeti/os-images/$cdrom"
+  fi
+  [ ! -f "$cdrom" ] && log "\nFile $cdrom does not exist" && exit 1
 fi
 if [ -n "$vnc" ]; then
   if [ "$vnc" == "yes" ]; then
@@ -173,8 +178,8 @@ request() {
     res+=$?
     if [ -n "$cdrom" ]; then
       if [ $res -eq 0 ]; then
-        [[ "$hvparams" == "-H" ]] && hvparams="-H " || hvparams="${hvparams},"
-        hvparams="${hvparams}boot_order=cdrom,cdrom_image_path=\"$cdrom\""
+        #[[ "$hvparams" == "-H" ]] && hvparams="-H " || hvparams="${hvparams},"
+        hvparams="-H boot_order=cdrom,cdrom_image_path=\"$cdrom\""
         log "sending request with command: $GNTI startup $hvparams $name"
         $GNTI startup $hvparams $name >>"$LOG" 2>&1
         res+=$?
diff --git a/cloud/ganeti/stop_server b/cloud/ganeti/stop_server
--- a/cloud/ganeti/stop_server
+++ b/cloud/ganeti/stop_server
@@ -74,7 +74,7 @@ tscluster=$(cat "$M_ROOT/servers.list" | grep -v ^# | grep -v ^$ | cut -d'|' -f4
 thekey=`"$M_ROOT"/helpers/find_key cluster $tscluster`
 
 request() {
-  ssh -i "$thekey" -o StrictHostKeyChecking=no root@$name \(swapoff -a \&\& poweroff\) >>"$LOG" 2>&1 </dev/null &
+  ssh -i "$thekey" -o StrictHostKeyChecking=no -o ConnectTimeout=$CONNECT_TIMEOUT root@$name \(swapoff -a \&\& poweroff\) >>"$LOG" 2>&1 </dev/null &
   sleep 10
   $GNTI shutdown $name >/dev/null 2>&1
   $GNTI remove -f $name >/dev/null 2>&1
@@ -94,7 +94,7 @@ if [[ $reqres -eq 0 ]] ; then
   log "server name ${name}, id ${id}, IP ${ip} terminated succesfully" | tee -a "$rpath"/../ganeti.log
   SSHK=`which ssh-keygen 2>/dev/null`
   [ -n "$name" ] && $SSHK -q -R "$name" >/dev/null 2>&1 && log "$name removed from known_hosts"
-  for ipa in ${IPS} ; do
+  for ipa in $IPS ; do
     if [ -n "$ipa" ] ; then
       $SSHK -q -R "$ipa" >/dev/null 2>&1 && log "$ipa removed from known_hosts"
       sed -i "/^$ipa|/d" "$M_ROOT/servers.list" && log "$ipa removed from servers.list"
@@ -114,6 +114,8 @@ if [[ $reqres -eq 0 ]] ; then
       esac
     fi
   fi
+else
+  echo "Error stopping server" >&2
 fi
 
 proper_exit 0 119
