option --vnc

diff --git a/cloud/ganeti/start_server b/cloud/ganeti/start_server
--- a/cloud/ganeti/start_server
+++ b/cloud/ganeti/start_server
@@ -26,7 +26,7 @@ IPR2=`which ip 2>/dev/null`
 [ -z "$GNTI" ] && echo "gnt-instance utility not found" && exit 1
 [ -z "$ROUTE" ] && echo "route utility not found" && exit 1
 [ -z "$IPR2" ] && echo "ip utility not found" && exit 1
-possible_options="cloud region flavor cluster image name return verbose test cdrom"
+possible_options="cloud region flavor cluster image name return verbose test cdrom vnc"
 necessary_options="cluster"
 
 LOG="$M_ROOT/logs/cloud.log"
@@ -64,7 +64,13 @@ fi
 [ -n "$verbose" ] && debug=1
 if [ -n "$cdrom" ]; then
   [ "$cdrom" == "yes" ] && echo -e "\nOption --cdrom assumes path to ISO image:\n  --cdrom=/path/to/image" && exit 1
+  [ `echo "$cdrom" | cut -b1` != "/" ] && log "restoring absolute path required by Ganeti: $cdrom --> $PWD/$cdrom" && cdrom="$PWD/$cdrom"
   [ ! -e "$cdrom" ] && echo -e "\nFile $cdrom does not exist" && exit 1
+fi
+if [ -n "$vnc" ]; then
+  [ "$vnc" == "yes" ] && echo -e "\nWARNING: setting vnc_bind_address to 0.0.0.0.\nUse firewall to restrict access.\nYou may also want to use specific IP, e.g.:\n  --vnc=10.10.10.10\n" && vnc="0.0.0.0"
+  [ `expr "$vnc" : ".*[^[0-9.:]]*"` -ne 0 ] && echo -e "\nArgument for --vnc must be a valid IPv4 or IPv6 address\n" && exit 1
+  VNC="-H serial_console=false -H vnc_bind_address=$vnc"
 fi
 source "$M_ROOT/conf/mon.conf"
 source "$M_ROOT/conf/clouds/${CLOUD}.conf"
@@ -135,13 +141,13 @@ request() {
   echo "$ip $name" >> /etc/hosts
   if [ -z "$cdrom" ]; then
     log "sending request with command: $GNTI add -n $node -o $ios $iparams $name"
-    $GNTI add -n $node -o $ios $iparams $name >>"$LOG" 2>&1
+    $GNTI add -n $node -o $ios $iparams $VNC $name >>"$LOG" 2>&1
   else
-    log "sending request with command: $GNTI add -n $node --no-start --no-install -o $ios $iparams $name"
+    log "sending request with command: $GNTI add -n $node --no-start -o $ios $iparams $name"
     $GNTI add -n $node --no-start --no-install -o $ios $iparams $name >>"$LOG" 2>&1
     if [ $? -eq 0 ]; then
-      log "sending request with command: $GNTI add -n $node --no-start --no-install -o $ios $iparams $name"
-      $GNTI start -H boot_order=cdrom,cdrom_image_path="$cdrom" $name >>"$LOG" 2>&1
+      log "sending request with command: $GNTI start -H boot_order=cdrom,cdrom_image_path="$cdrom" $name"
+      $GNTI startup -H boot_order=cdrom,cdrom_image_path="$cdrom" $VNC $name >>"$LOG" 2>&1
     fi
   fi
 }
