another fix for start/stop ganeti

diff --git a/cloud/ganeti/start_server b/cloud/ganeti/start_server
--- a/cloud/ganeti/start_server
+++ b/cloud/ganeti/start_server
@@ -247,13 +247,13 @@ $SSHK -q -R "$ip" >/dev/null
 [ ! -f "${rpath}/../../keys/$thekey" ] && thekey="${thekey}.pem"
 [ ! -f "${rpath}/../../keys/$thekey" ] && thekey="$HOME/.ssh/id_rsa.pub"
 [ ! -f "$thekey" ] && thekey="$HOME/.ssh/id_dsa.pub"
-[ -f "$thekey" ] && $SSH -i $thekey -o StrictHostKeyChecking=no $ip echo 2>/dev/null &&
+[ -f "$thekey" ] && $SSH -i "$thekey" -o StrictHostKeyChecking=no $ip echo 2>/dev/null &&
 $SSH -i $thekey -o StrictHostKeyChecking=no $name echo 2>/dev/null
 if [ $? -ne 0 ]; then
-  log "Unable to login to the server $ip using the key ${rpath}/../../keys/${KEY}, trying again..."
+  log "Unable to login to the server $ip using the key $thekey, trying again..."
   for ((k=0; k<3; k++)); do
-    $SSH -i "${rpath}/../../keys/${KEY}" -o StrictHostKeyChecking=no $ip echo >/dev/null
-    [ $? -eq 0 ] && $SSH -i "${rpath}/../../keys/${KEY}" -o StrictHostKeyChecking=no $name echo >/dev/null && break
+    $SSH -i "$thekey" -o StrictHostKeyChecking=no $ip echo >/dev/null
+    [ $? -eq 0 ] && $SSH -i "$thekey" -o StrictHostKeyChecking=no $name echo >/dev/null && break
     sleep 5
   done
 fi
