proper exit

diff --git a/cloud/rackspace/get_server_details b/cloud/rackspace/get_server_details
--- a/cloud/rackspace/get_server_details
+++ b/cloud/rackspace/get_server_details
@@ -73,11 +73,18 @@ source "${rpath}/../../conf/cloud.conf"
 M_TEMP="$M_TEMP/cloud/$CLOUD"
 lock_cloudops || exit 10
 
+
+proper_exit() {
+  log "exit status: $1"
+  unlock_cloudops
+  exit $1
+}
+
 if [ -z "$id" ] ; then
   if [ -z "$ip" ] ; then
     if [ -z "$name" ] ; then
       echo "One of id, ip or name is required to identify the server"
-      exit 1
+      proper_exit 1
     else
       ip=`cat "${rpath}/../../servers.list" | cut -d'|' -f1,4 | grep \|$name$ | cut -d'|' -f1`
       if [ -n "$ip" ] ; then
@@ -90,7 +97,7 @@ if [ -z "$id" ] ; then
     find_by_ip $ip
   fi
 fi
-[ -z "$id" ] && echo "Unable to find ID of this server" && exit 1
+[ -z "$id" ] && echo "Unable to find ID of this server" && proper_exit 1
 
 req="/servers/$id"
 
diff --git a/cloud/rackspace/resize_server b/cloud/rackspace/resize_server
--- a/cloud/rackspace/resize_server
+++ b/cloud/rackspace/resize_server
@@ -66,6 +66,13 @@ source "$M_ROOT/lib/cloud_functions.sh"
 lock_cloudops || exit 10
 [ -z "$cluster" ] && cluster="$M_CLUSTER"
 
+
+proper_exit() {
+  log "exit status: $1"
+  unlock_cloudops
+  exit $1
+}
+
 find_by_ip() {
   if [ -f "${M_TEMP}/show_servers.resp" ] ; then
     sn=`grep addresses "${M_TEMP}/show_servers.resp" | grep "${1}$" | cut -d'/' -f3`
@@ -80,10 +87,10 @@ if [ -z "$id" ] ; then
   if [ -z "$ip" ] ; then
     if [ -z "$name" ] ; then
       echo "One of id, ip or name is required to identify the server"
-      exit 1
+      proper_exit 1
     else
       ip=`cat "${rpath}/../../servers.list" | cut -d'|' -f1,4 | grep \|$name$ | cut -d'|' -f1`
-      [ `echo $ip | wc -w` -gt 1 ] && echo "Found more than 1 IP for this name! Exiting." && exit 1
+      [ `echo $ip | wc -w` -gt 1 ] && echo "Found more than 1 IP for this name! Exiting." && proper_exit 1
       if [ -n "$ip" ] ; then
         find_by_ip $ip
       else
@@ -107,7 +114,7 @@ else
     ipint=`echo "$nameips" | cut -d'|' -f3`
   fi
 fi
-[ -z "$id" ] && echo "Unable to find ID of this server" && exit 1
+[ -z "$id" ] && echo "Unable to find ID of this server" && proper_exit 1
 req="/servers/$id/resize"
 
 request() {
@@ -145,7 +152,7 @@ try_auth() {
   local -i i
   i=0
   while [ ! -e "${M_TEMP}/auth.resp" -o `cat "${M_TEMP}/auth.resp" 2>/dev/null | wc -l` -eq 0 ] ; do
-    [ $i -gt 10 ] && log "Problem getting authorization from the Rackspace Cloud API" && exit 1
+    [ $i -gt 10 ] && log "Problem getting authorization from the Rackspace Cloud API" && proper_exit 1
     ${rpath}/auth
     i+=1
     sleep 10
@@ -163,7 +170,7 @@ request && log "Request sent"
 declare -i n
 n=0
 while [ `grep -c ^0\/unauthorized\/code\|401$ "${M_TEMP}/${rcommand}.resp"` -eq 1 ] ; do
-  [ $n -gt 10 ] && log "Problem getting authorization renewal from the Rackspace Cloud API" && exit 1
+  [ $n -gt 10 ] && log "Problem getting authorization renewal from the Rackspace Cloud API" && proper_exit 1
   [ $n -gt 1 ] && sleep 30
   rm -f "${M_TEMP}/auth.resp"
   try_auth
diff --git a/cloud/rackspace/stop_server b/cloud/rackspace/stop_server
--- a/cloud/rackspace/stop_server
+++ b/cloud/rackspace/stop_server
@@ -65,7 +65,13 @@ if [ -n "$last" -o -n "$first" ]; then
   [ -n "$last" ] && name=`"$M_ROOT"/cloud/common/get_ips --cluster=$cluster --names | sort -n | tail -1`
   [ -n "$first" ] && name=`"$M_ROOT"/cloud/common/get_ips --cluster=$cluster --names | sort -n | head -1`
 fi
-  
+
+proper_exit() {
+  log "exit status: $1"
+  unlock_cloudops
+  exit $1
+}
+
 find_by_ip() {
   if [ -f "${M_TEMP}/show_servers.resp" ] ; then
     sn=`grep addresses "${M_TEMP}/show_servers.resp" | grep "|\"${1}\"$" | cut -d'/' -f3`
@@ -101,10 +107,10 @@ if [ -z "$id" ] ; then
   if [ -z "$ip" ] ; then
     if [ -z "$name" ] ; then
       echo "One of id, ip or name is required to identify the server"
-      exit 1
+      proper_exit 1
     else
       ip=`cat "${rpath}/../../servers.list" | cut -d'|' -f1,4 | grep \|$name$ | cut -d'|' -f1`
-      [ `echo $ip | wc -w` -gt 1 ] && echo "Found more than 1 IP for this name! Use IP or ID to identify the server. Exiting." && exit 1
+      [ `echo $ip | wc -w` -gt 1 ] && echo "Found more than 1 IP for this name! Use IP or ID to identify the server. Exiting." && proper_exit 1
       if [ -n "$ip" ] ; then
         find_by_ip $ip
       else
@@ -135,7 +141,7 @@ if [ -n "$id" ] ; then
   fi
   [ -z "$cluster" ] && log "unable to find the cluster for this server, not checking the minimal number of servers in the cluster"
 else
-  echo "Unable to find ID of this server" && exit 1
+  echo "Unable to find ID of this server" && proper_exit 1
 fi
 req="/servers/$id"
 
@@ -161,14 +167,14 @@ try_auth() {
 
 exit_status=0 # TODO
 
-check_cluster_minimum "$cluster" || exit 5
+check_cluster_minimum "$cluster" || proper_exit 5
 try_auth
 reqres=`request`
 [ $reqres -gt 0 ] && log "Curl request returned status $reqres"
 declare -i n
 n=0
 while [ `grep -c ^0\/unauthorized\/code\|401$ "${M_TEMP}/${rcommand}.resp"` -eq 1 ] ; do
-  [ $n -gt 10 ] && log "Problem getting authorization renewal from the Rackspace Cloud API" && exit 1
+  [ $n -gt 10 ] && log "Problem getting authorization renewal from the Rackspace Cloud API" && proper_exit 1
   [ $n -gt 1 ] && sleep 30
   rm -f "${M_TEMP}/auth.resp"
   try_auth
