stop server by name or ip

diff --git a/cloud/rackspace/get_server_details b/cloud/rackspace/get_server_details
--- a/cloud/rackspace/get_server_details
+++ b/cloud/rackspace/get_server_details
@@ -30,7 +30,7 @@ possible_options="id name ip return verbose"
 necessary_options=""
 
 ARGV=`echo ${@} | sed 's/^--//' | sed 's/ --/|/g'`
-[ -z "$ARGV" ] && echo "Stop server? Which one?" && exit 1
+[ -z "$ARGV" ] && echo "Show server? Which one?" && exit 1
 IFS1=$IFS
 IFS='|'
 for s_option in $ARGV
@@ -47,6 +47,16 @@ do
   fi
 done
 IFS=$IFS1
+
+find_by_ip() {
+  if [ -f "${TMPDIR}/show_servers.resp" ] ; then
+    sn=`grep addresses "${TMPDIR}/show_servers.resp" | grep "${1}$" | cut -d'/' -f3`
+    id=`grep \/$sn\/id\| "${TMPDIR}/show_servers.resp" | cut -d'|' -f2`
+  fi
+  if [ -z "$id" ] ; then
+    id=`${rpath}/show_servers --forceupdate --view=table | grep \|${1}\| | cut -d'|' -f1`
+  fi
+}
 
 found=0
 for option in `echo $necessary_options | sed 's/,//g'`; do
@@ -70,24 +80,18 @@ if [ -z "$id" ] ; then
     else
       ip=`cat "${rpath}/../../servers.list" | cut -d'|' -f1,4 | grep \|$name$ | cut -d'|' -f1`
       if [ -n "$ip" ] ; then
-        if [ -f "${TMPDIR}/show_servers.resp" ] ; then
-          sn=`grep addresses "${TMPDIR}/show_servers.resp" | grep "${ip}$"
-        else
-        
-        fi
+        find_by_ip $ip
       else
-      
+        id=`${rpath}/show_servers --forceupdate --view=table | cut -d'|' -f1,2 | grep \|${name}$ | cut -d'|' -f1`
       fi
     fi
   else
-  
+    find_by_ip $ip
   fi
-
 fi
+[ -z "$id" ] && echo "Unable to find ID of this server" && exit 1
 
 req="/servers/$id"
-
-
 
 request() {
   URL=`grep ^1\/auth\/serviceCatalog\/cloudServers\/0\/publicURL "${TMPDIR}/auth.resp" | cut -d'|' -f2`
diff --git a/cloud/rackspace/stop_server b/cloud/rackspace/stop_server
--- a/cloud/rackspace/stop_server
+++ b/cloud/rackspace/stop_server
@@ -31,14 +31,75 @@ source "${rpath}/../../conf/mon.conf"
 source "${rpath}/../../conf/cloud.conf"
 TMPDIR="${TMPDIR}/cloud/${CLOUD}"
 
+possible_options="id name ip verbose"
+necessary_options=""
+
+ARGV=`echo ${@} | sed 's/^--//' | sed 's/ --/|/g'`
+[ -z "$ARGV" ] && echo "Stop server? Which one?" && exit 1
+IFS1=$IFS
+IFS='|'
+for s_option in $ARGV
+do
+  s_optname=${s_option%%=*}
+  s_optarg=${s_option##*=}
+  [ "X$s_optarg" == "X$s_optname" ] && s_optarg="yes"
+  for option in `echo $possible_options | sed 's/ /|/g'`; do 
+    [ "X$s_optname" == "X$option" ] && eval "$s_optname=\"$s_optarg\"" && found=1
+  done
+   if [[ $found -ne 1 ]]; then 
+    echo "Unknown option: $s_optname"
+    exit 1
+  fi
+done
+IFS=$IFS1
+
+find_by_ip() {
+  if [ -f "${TMPDIR}/show_servers.resp" ] ; then
+    sn=`grep addresses "${TMPDIR}/show_servers.resp" | grep "${1}$" | cut -d'/' -f3`
+    id=`grep \/$sn\/id\| "${TMPDIR}/show_servers.resp" | cut -d'|' -f2`
+  fi
+  if [ -z "$id" ] ; then
+    id=`${rpath}/show_servers --forceupdate --view=table | grep \|${1}\| | cut -d'|' -f1`
+  fi
+}
+
+if [ -z "$id" ] ; then
+  if [ -z "$ip" ] ; then
+    if [ -z "$name" ] ; then
+      echo "One of id, ip or name is required to identify the server"
+      exit 1
+    else
+      ip=`cat "${rpath}/../../servers.list" | cut -d'|' -f1,4 | grep \|$name$ | cut -d'|' -f1`
+      if [ -n "$ip" ] ; then
+        find_by_ip $ip
+      else
+        id=`${rpath}/show_servers --forceupdate --view=table | cut -d'|' -f1,2 | grep \|${name}$ | cut -d'|' -f1`
+      fi
+    fi
+  else
+    find_by_ip $ip
+  fi
+else
+  if [ -f "${TMPDIR}/show_servers.resp" ] ; then
+    sn=`grep \/id\| "${TMPDIR}/show_servers.resp" | grep "${id}$" | cut -d'/' -f3`
+    name=`grep \/$sn\/name\| "${TMPDIR}/show_servers.resp" | cut -d'|' -f2`
+    ipint=`grep \/$sn\/addresses\/private "${TMPDIR}/show_servers.resp" | cut -d'|' -f2`
+    ipext=`grep \/$sn\/addresses\/public "${TMPDIR}/show_servers.resp" | cut -d'|' -f2`
+  fi
+  if [ -z "$name" ] ; then
+    nameips=`${rpath}/show_servers --forceupdate --view=table | grep ^${id}\| | cut -d'|' -f2,5,4`
+    name=`echo "$nameips" | cut -d'|' -f1`
+    ipint=`echo "$nameips" | cut -d'|' -f2`
+    ipext=`echo "$nameips" | cut -d'|' -f3`
+  fi
+fi
+[ -z "$id" ] && echo "Unable to find ID of this server" && exit 1
+
 request() {
   URL=`grep ^1\/auth\/serviceCatalog\/cloudServers\/0\/publicURL "${TMPDIR}/auth.resp" | cut -d'|' -f2`
   TOKEN=`grep ^1\/auth\/token\/id "${TMPDIR}/auth.resp" | cut -d'|' -f2`
   $CURL -X DELETE -H "Content-Type: application/json; charset=UTF-8" -H "Accept: application/json" -H "X-Auth-Token: $TOKEN" "${URL}${req}" | "${rpath}/../../lib/json2txt" > "${TMPDIR}/${rcommand}.resp"
 }
-
-# Cleaning first
-
 
 [ -f "${TMPDIR}/auth.resp" ] || ${rpath}/auth
 request
@@ -46,9 +107,10 @@ if [ `grep -c ^1\/unauthorized\/code\|401$ "${TMPDIR}/${rcommand}.resp"` -eq 1 ]
   ${rpath}/auth
   request
 fi
-sleep 5
-cat "${TMPDIR}/${rcommand}.resp"
+SSHK=`which ssh-keygen 2>/dev/null`
+[ -n "$name" ] && $SSHK -R "$name"
+[ -n "$ipint" ] && $SSHK -R "$ipint"
+[ -n "$ipext" ] && $SSHK -R "$ipext"
 
-#ssh-keygen -f "/root/.ssh/known_hosts" -R 10.179.35.32
 
 
