log helpers

diff --git a/cloud/rackspace/get_server_details b/cloud/rackspace/get_server_details
--- a/cloud/rackspace/get_server_details
+++ b/cloud/rackspace/get_server_details
@@ -52,17 +52,42 @@ found=0
 for option in `echo $necessary_options | sed 's/,//g'`; do
   [ "X$(eval echo \$$option)" == "X" ] && missing_options="${missing_options}, --${option}" && found=1
 done
-if [[ found -eq 1 ]]; then
+if [[ $found -eq 1 ]]; then
   missing_options=${missing_options#*,}
   echo "Necessary options: ${missing_options} not found"
   exit 1
 fi
 
-
-req="/servers/$1"
 source "${rpath}/../../conf/mon.conf"
 source "${rpath}/../../conf/cloud.conf"
 TMPDIR="$TMPDIR/cloud/$CLOUD"
+
+if [ -z "$id" ] ; then
+  if [ -z "$ip" ] ; then
+    if [ -z "$name" ] ; then
+      echo "One of id, ip or name is required to identify the server"
+      exit 1
+    else
+      ip=`cat "${rpath}/../../servers.list" | cut -d'|' -f1,4 | grep \|$name$ | cut -d'|' -f1`
+      if [ -n "$ip" ] ; then
+        if [ -f "${TMPDIR}/show_servers.resp" ] ; then
+          sn=`grep addresses "${TMPDIR}/show_servers.resp" | grep "${ip}$"
+        else
+        
+        fi
+      else
+      
+      fi
+    fi
+  else
+  
+  fi
+
+fi
+
+req="/servers/$id"
+
+
 
 request() {
   URL=`grep ^1\/auth\/serviceCatalog\/cloudServers\/0\/publicURL "${TMPDIR}/auth.resp" | cut -d'|' -f2`
