server identification

diff --git a/cloud/rackspace/resize_server b/cloud/rackspace/resize_server
--- a/cloud/rackspace/resize_server
+++ b/cloud/rackspace/resize_server
@@ -66,11 +66,55 @@ source "$M_ROOT/lib/cloud_functions.sh"
 
 [ -z "$cluster" ] && cluster="$M_CLUSTER"
 
+find_by_ip() {
+  if [ -f "${M_TEMP}/show_servers.resp" ] ; then
+    sn=`grep addresses "${M_TEMP}/show_servers.resp" | grep "${1}$" | cut -d'/' -f3`
+    id=`grep \/$sn\/id\| "${M_TEMP}/show_servers.resp" | cut -d'|' -f2`
+  fi
+  if [ -z "$id" ] ; then
+    id=`${rpath}/show_servers --forceupdate --view=table | grep \|${1}\| | cut -d'|' -f1`
+  fi
+}
+
+if [ -z "$id" ] ; then
+  if [ -z "$ip" ] ; then
+    if [ -z "$name" ] ; then
+      echo "One of id, ip or name is required to identify the server"
+      exit 1
+    else
+      ip=`cat "${rpath}/../../servers.list" | cut -d'|' -f1,4 | grep \|$name$ | cut -d'|' -f1`
+      [ `echo $ip | wc -w` -gt 1 ] && echo "Found more than 1 IP for this name! Exiting." && exit 1
+      if [ -n "$ip" ] ; then
+        find_by_ip $ip
+      else
+        id=`${rpath}/show_servers --forceupdate --view=table | cut -d'|' -f1,2 | grep \|${name}$ | cut -d'|' -f1`
+      fi
+    fi
+  else
+    find_by_ip $ip
+  fi
+else
+  if [ -f "${M_TEMP}/show_servers.resp" ] ; then
+    sn=`grep \/id\| "${M_TEMP}/show_servers.resp" | grep "${id}$" | cut -d'/' -f3`
+    name=`grep \/$sn\/name\| "${M_TEMP}/show_servers.resp" | cut -d'|' -f2`
+    ipint=`grep \/$sn\/addresses\/private "${M_TEMP}/show_servers.resp" | cut -d'|' -f2`
+    ipext=`grep \/$sn\/addresses\/public "${M_TEMP}/show_servers.resp" | cut -d'|' -f2`
+  fi
+  if [ -z "$name" ] ; then
+    nameips=`${rpath}/show_servers --forceupdate --view=table | grep ^${id}\| | cut -d'|' -f2,4,5`
+    name=`echo "$nameips" | cut -d'|' -f1`
+    ipext=`echo "$nameips" | cut -d'|' -f2`
+    ipint=`echo "$nameips" | cut -d'|' -f3`
+  fi
+fi
+[ -z "$id" ] && echo "Unable to find ID of this server" && exit 1
+req="/servers/$id/resize"
+
 request() {
-  log "Sending request..."
   URL=`grep ^0\/auth\/serviceCatalog\/cloudServers\/0\/publicURL "${M_TEMP}/auth.resp" | cut -d'|' -f2`
+  log "Sending request to ${URL}${req}"
   TOKEN=`grep ^0\/auth\/token\/id "${M_TEMP}/auth.resp" | cut -d'|' -f2`
-  $CURL -X POST -T "$M_TEMP/${rcommand}.req" -H "Content-Type: application/json" -H "Accept: application/json" -H "X-Auth-Token: $TOKEN" "${URL}/servers" | "${rpath}/../../lib/json2txt" > "${M_TEMP}/${rcommand}.resp"
+  $CURL -X POST -T "$M_TEMP/${rcommand}.req" -H "Content-Type: application/json" -H "Accept: application/json" -H "X-Auth-Token: $TOKEN" "${URL}${req}" | "${rpath}/../../lib/json2txt" > "${M_TEMP}/${rcommand}.resp"
 }
 
 wait_ready() {
