bits

diff --git a/cloud/rackspace/start_server b/cloud/rackspace/start_server
--- a/cloud/rackspace/start_server
+++ b/cloud/rackspace/start_server
@@ -93,9 +93,9 @@ save_details() {
   echo -e "\n`date`\n\nCluster|$cluster\nName|$name\n`grep -E "\/id\||\/imageId\||\/flavorId\||\/adminPass\||\/addresses\/public|\/addresses\/private" "${M_TEMP}/${rcommand}.resp"`\n" >> "${rpath}/../rackspace.log"
   chmod 600 "${rpath}/../rackspace.log"
   if [ "X$NETWORK" == "Xexternal" ] ; then
-    slip=`grep \/addresses\/public "${M_TEMP}/${rcommand}.resp" | cut -d'|' -f2`
+    slip=`grep \/addresses\/public "${M_TEMP}/${rcommand}.resp" | cut -d'|' -f2 | tr -d '"'`
   else
-    slip=`grep \/addresses\/private "${M_TEMP}/${rcommand}.resp" | cut -d'|' -f2`
+    slip=`grep \/addresses\/private "${M_TEMP}/${rcommand}.resp" | cut -d'|' -f2 | tr -d '"'`
   fi
   echo "${slip}|${thekey}|${region}|${name}|${cluster}" >> "${rpath}/../../servers.list"
   return 0
@@ -113,7 +113,7 @@ wait_ready() {
     if [ -n "$1" ] ; then
       printf "Progress: `grep \/progress\| "${M_TEMP}/get_server_details.resp" | cut -d'|' -f2`     \r"
     fi
-    if [ "X`grep \/status\| "${M_TEMP}/get_server_details.resp" | cut -d'|' -f2`" == "XACTIVE" ] ; then
+    if [ "X`grep \/status\| "${M_TEMP}/get_server_details.resp" | cut -d'|' -f2`" == "X\"ACTIVE\"" ] ; then
       echo
       return 0
     fi
@@ -195,6 +195,7 @@ try_auth() {
 }
 
 source "${rpath}/../../conf/cloud.conf"
+exit_status=0
 
 if [ -z "$noupdate" ] ; then
   try_auth
@@ -219,12 +220,14 @@ newid=`grep \/id\| "${M_TEMP}/${rcommand}.resp" | cut -d'|' -f2`
 if [ -n "$newid" ] ; then
   save_details $verbose || true
   wait_ready $verbose
+  wait_res=$?
   [ -n "$return" ] && printreturn $return
+  [ $wait_res -eq 1 ] && exit_status=2
 else
   exit 1
 fi
 
-${rpath}/update_hosts_file && log "/etc/hosts updated"
+${rpath}/update_hosts_file && log "/etc/hosts updated" || log "error updating /etc/hosts"
 
-exit 0
+exit $exit_status
 
diff --git a/deployment/metaexec b/deployment/metaexec
--- a/deployment/metaexec
+++ b/deployment/metaexec
@@ -38,7 +38,7 @@ run_meta() {
     fi
     [ -z "$metatype" ] && echo "Meta type is not defined. Don't know how to run it." && exit 1
     if [ -n "$verbose" ] ; then
-      printf "\n  type: $metatype  script: $metascript\n"
+      printf "\n  type: $metatype  script: $metascript \n"
       V='--verbose'
     fi
     if [ -n "$debug" ] ; then
@@ -62,9 +62,9 @@ run_meta() {
         fi
       else
         if [ -n "$use_color" ] ; then
-          [ $res -eq 0 ] && printf "  ..  \033[01;32mSuccess\033[0m\n" || printf "  ..  \033[01;31mError\033[0m\n"
+          [ $res -eq 0 ] && printf " ..  \033[01;32mSuccess\033[0m\n" || printf " ..  \033[01;31mError\033[0m\n"
         else
-          [ $res -eq 0 ] && echo "  ..  Success" || echo "  ..  ERROR"
+          [ $res -eq 0 ] && echo " ..  Success" || echo " ..  ERROR"
         fi
       fi
       [ -n "$verbose" ] && echo
@@ -79,7 +79,7 @@ run_meta() {
     metascript=`echo $1 | awk '{print $2}'`
     metascript=`eval "echo $metascript"`
     if [ -n "$verbose" ] ; then
-      printf "\n  type: $metatype  script: $metascript\n"
+      printf "\n  type: $metatype  script: $metascript \n"
       V='--verbose'
     fi
     if [ -n "$metatype" ] && [ -n "$metascript" ] ; then
@@ -100,9 +100,9 @@ run_meta() {
         fi
       else
         if [ -n "$use_color" ] ; then
-          [ $res -eq 0 ] && printf "  ..  \033[01;32mSuccess\033[0m\n" || printf "  ..  \033[01;31mError\033[0m\n"
+          [ $res -eq 0 ] && printf " ..  \033[01;32mSuccess\033[0m\n" || printf " ..  \033[01;31mError\033[0m\n"
         else
-          [ $res -eq 0 ] && echo "  ..  Success" || echo "  ..  ERROR"
+          [ $res -eq 0 ] && echo " ..  Success" || echo " ..  ERROR"
         fi
       fi
       [ -n "$verbose" ] && echo
@@ -280,7 +280,12 @@ if [ -n "$newserver" ]; then
     startserver $T
     [ -z "$ip" ] && log "Was unable either to start a cloud server in the cloud $cloud or to get its IP address." && sleep $WAIT_BETWEEN_TRIES && continue
     [ $res -eq 0 ] && [[ `expr $ip : [0-9.]*$` -ne 0 ]] && break
+    # breaking here (reason not known); will be test later
+    [ $res -eq 2 ] && log "Timeout waiting for the server ready" && break
+    # not breaking here: may be controversial commands, so let it start up if it
+    # gets an empty slot next time
     [ $res -eq 5 ] && log "Maximum servers number for cluster $cluster has been reached, unable to add another server"
+    # various weird errors below, exit 1 
     [ $res -eq 6 ] && log "Failed to generate a name for the new server" && exit 1
     [ $res -eq 7 ] && log "Failed to find out what image to use to create the new server, define it in clusters.conf, please" && exit 1
     [ $res -eq 8 ] && log "Failed to find out what flavor (server size) to use, define it in clusters.conf, please" && exit 1
