bits

diff --git a/lib/genjson b/lib/genjson
--- a/lib/genjson
+++ b/lib/genjson
@@ -14,17 +14,22 @@
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
-
 rcommand=${0##*/}
 rpath=${0%/*}
-#*/ (this is needed to fix vi syntax highlighting)
+#*/
+[ -z "$M_ROOT" ] && M_ROOT=$(readlink -f "$rpath/../")
+
+STAT=`which stat 2>/dev/null`
+LOG="$M_ROOT/logs/dashboard.log"
+[ -z "$STAT" ] && log "Stat utility not found" && exit 1
 
 possible_options="type css folder"
 necessary_options="type"
 [ $# -eq 0 ] && echo "Can't run without options. Possible options are: ${possible_options}" && exit 1
+
 IFS1=$IFS
-IFS='--'
-for s_option in "${@}"
+IFS='-'
+for s_option in "$@"
 do
   found=0
   case ${s_option} in
@@ -43,36 +48,43 @@ do
     ;;
   esac
 
-  for option in `echo $possible_options | sed 's/ /--/g'`; do 
-    [ -n "$s_optname" ] && [ "X$s_optname" == "X$option" ] && eval "$option=\"${s_optarg}\"" && found=1
+  for option in `echo $possible_options | sed 's/ /-/g'`; do 
+    [ -n "$s_optname" ] && [ "_$s_optname" == "_$option" ] && eval "$option=\"${s_optarg}\"" && found=1
   done
-  [ "X$s_option" == "X$s_param" ] && found=1
+  [ "_$s_option" == "_$s_param" ] && found=1
   if [[ $found -ne 1 ]]; then 
     echo "Unknown option: $s_optname"
     exit 1
   fi
 done
-if [ "X$help" == "Xyes" ] ; then
+
+if [ "_$help" == "_yes" ] ; then
   echo "Usage: ${0##*/} <options> <textfile>"
   echo 
   echo "Options:"
   echo
   echo "  --type=<type>            - dash, report, alert"
   echo "                             default is dash."
-  echo "  --css=<CSS class>        - dash slot class (dash only)"
+  echo "  --css=<CSS class>        - dash slot class (dash type only)"
   exit 0
 fi
 
+log() {
+  echo "`date +"%m.%d %H:%M:%S"` ($$) ${0##*/}: ${@}">>"$LOG"
+}
+
 [ -z "$folder" ] && folder="nodes/localhost"
-[ -d "$rpath/../www/$folder" ] || install -d "$rpath/../www/$folder"
-source "$rpath/../conf/dash.conf"
-source "$rpath/../conf/mon.conf"
-[ -z "$freqdef" ] && freqdef=$FREQ
+[ -d "$M_ROOT/www/$folder" ] || install -d "$M_ROOT/www/$folder"
+source "$M_ROOT/conf/dash.conf"
+source "$M_ROOT/conf/mon.conf"
+[ -n "$timeshift" ] || timeshift=`cat "$M_TEMP/timeshift" 2>/dev/null` || timeshift=10
+freqdef=`expr $FREQ + $timeshift`
 
 # to ensure the report file is closed (see gendash function)
 sleep 1
 
-textfile="${s_param}"
+textfile="$s_param"
+
 case $type in
   dash)
     id="`date +"%m.%d_%H:%M:%S"`"
