bits

diff --git a/cloud/ganeti/os-skeleton/create b/cloud/ganeti/os-skeleton/create
--- a/cloud/ganeti/os-skeleton/create
+++ b/cloud/ganeti/os-skeleton/create
@@ -23,58 +23,65 @@ set -e
 
 debug set -x
 
-if [ "$CDINSTALL" = "no" ] ; then
-    # If the target device is not a real block device we'll first losetup it.
-    # This is needed for file disks.
-    if [ ! -b $blockdev ]; then
-      ORIGINAL_BLOCKDEV=$blockdev
-      blockdev=$($LOSETUP -sf $blockdev)
-      CLEANUP+=("$LOSETUP -d $blockdev")
-    fi
+# If the target device is not a real block device we'll first losetup it.
+# This is needed for file disks.
+if [ ! -b $blockdev ]; then
+  ORIGINAL_BLOCKDEV=$blockdev
+  blockdev=$($LOSETUP -sf $blockdev)
+  CLEANUP+=("$LOSETUP -d $blockdev")
+fi
 
-    if [ ! -f "$IMAGE_FILE" ] ; then
-      log_error "Can't find image file: $IMAGE_FILE"
-      exit 1
-    fi
+if [ ! -f "$IMAGE_FILE" ] ; then
+  log_error "Can't find image file: $IMAGE_FILE"
+  exit 1
+fi
 
-    format_disk0 $blockdev
-    
-    # deploying something like a windows image, skip the rest
-    if [ "${NOMOUNT}" = "yes" ] ; then
-      cleanup
-      exit 0
-    fi
+format_disk0 $blockdev
 
-    filesystem_dev=$(map_disk0 $blockdev)
-    CLEANUP+=("unmap_disk0 $blockdev")
+# deploying something like a windows image, skip the rest
+if [ "${NOMOUNT}" = "yes" ] ; then
+  cleanup
+  exit 0
+fi
 
-    mke2fs -Fjq $filesystem_dev
-    root_uuid=$($VOL_ID $filesystem_dev )
+filesystem_dev=$(map_disk0 $blockdev)
+CLEANUP+=("unmap_disk0 $blockdev")
 
-    TARGET=`mktemp -d` || exit 1
-    CLEANUP+=("rmdir $TARGET")
+mke2fs -Fjq $filesystem_dev
+root_uuid=$($VOL_ID $filesystem_dev )
 
-    # mount filesystems
-    mount $filesystem_dev $TARGET
-    CLEANUP+=("umount $TARGET")
-    
-    root_dump="${IMAGE_FILE}"
-    ( cd ${TARGET}; restore -r -y -f ${root_dump} > /dev/null )
+TARGET=`mktemp -d` || exit 1
+CLEANUP+=("rmdir $TARGET")
 
-    if [ "${INSTANCE_HV_serial_console}" = "True" ] ; then
-        setup_console $TARGET
-    fi
+# mount filesystems
+mount $filesystem_dev $TARGET
+CLEANUP+=("umount $TARGET")
 
-    RUN_PARTS=`which run-parts`
+root_dump="${IMAGE_FILE}"
+( cd ${TARGET}; restore -r -y -f ${root_dump} > /dev/null )
 
-    if [ -n "$RUN_PARTS" -a -n "$CUSTOMIZE_DIR" -a -d "$CUSTOMIZE_DIR" ]; then
-      TARGET=$TARGET
-      BLOCKDEV=$blockdev
-      ROOT_DEV=$root_dev
-      FSYSDEV=$filesystem_dev
-      export TARGET SUITE BLOCKDEV ROOT_DEV BOOT_DEV IMAGE_TYPE
-      $RUN_PARTS $CUSTOMIZE_DIR
-    fi
+mv $TMPDIR/etc/fstab $TMPDIR/etc/fstab.orig || true
+cat > $TMPDIR/etc/fstab <<EOF
+# /etc/fstab: static file system information.
+#
+# <file system>   <mount point>   <type>  <options>       <dump>  <pass>
+UUID=$root_uuid   /               ext3    defaults        0       1
+proc              /proc           proc    defaults        0       0
+EOF
+
+if [ "${INSTANCE_HV_serial_console}" = "True" ] ; then
+  setup_console $TARGET
+fi
+
+RUN_PARTS=`which run-parts`
+
+if [ -n "$RUN_PARTS" -a -n "$CUSTOMIZE_DIR" -a -d "$CUSTOMIZE_DIR" ]; then
+  TARGET=$TARGET
+  BLOCKDEV=$blockdev
+  ROOT_DEV=$root_dev
+  FSYSDEV=$filesystem_dev
+  export TARGET SUITE BLOCKDEV ROOT_DEV
+  $RUN_PARTS $CUSTOMIZE_DIR
 fi
 
 # execute cleanups
