image file def fixed

diff --git a/cloud/ganeti/os-skeleton/create b/cloud/ganeti/os-skeleton/create
--- a/cloud/ganeti/os-skeleton/create
+++ b/cloud/ganeti/os-skeleton/create
@@ -23,17 +23,17 @@ set -e
 
 debug set -x
 
+if [ ! -f "$IMAGE_FILE" ] ; then
+  log_error "Can't find image file: $IMAGE_FILE"
+  exit 1
+fi
+
 # If the target device is not a real block device we'll first losetup it.
 # This is needed for file disks.
 if [ ! -b $blockdev ]; then
   ORIGINAL_BLOCKDEV=$blockdev
   blockdev=$($LOSETUP -f --show $blockdev)
   CLEANUP+=("$LOSETUP -d $blockdev")
-fi
-
-if [ ! -f "$IMAGE_FILE" ] ; then
-  log_error "Can't find image file: $IMAGE_FILE"
-  exit 1
 fi
 
 format_disk0 $blockdev
