some enhancements

diff --git a/cloud/ec2/cloudsync b/cloud/ec2/cloudsync
--- a/cloud/ec2/cloudsync
+++ b/cloud/ec2/cloudsync
@@ -99,7 +99,17 @@ declare -i RETVAL
 RETVAL=0
 [ -n "$recursive" ] && r="-r"
 [ "X$IFCFG" != "X" ] && localip=`$IFCFG | sed '/inet\ /!d;s/.*r://;s/\ .*//' | grep -v '127.0.0.1'` || localip="ifconfig_not_found"
-[ -n "$ip" ] && cluster= && region=
+if [ -n "$ip" ] ; then
+  cluster= && region=
+  if [ `grep -c "^$ip\|" "${rpath}/../../servers.list"` -eq 0 ] ; then
+    if [ `cat "${rpath}/../../servers.list" | cut -d'|' -f4 | grep -c "$ip"` -ne 1 ] ; then
+      echo "Unable to find $ip in servers.list"
+      exit 1
+    else
+      ip=`cat "${rpath}/../../servers.list" | cut -d'|' -f1,4 | grep "\|${ip}$" | cut -d'|' -f1`
+    fi
+  fi
+fi
 [ -n "$cluster" ] || cluster=`cat "${rpath}/../../servers.list" | grep -v ^$ | grep -v  ^#|grep -v ^[[:space:]]*# | cut -d'|' -f5 | sort | uniq`
 [ -z "$cluster" ] && echo "No clusters found" && exit 1
 
diff --git a/deployment/metaexec b/deployment/metaexec
--- a/deployment/metaexec
+++ b/deployment/metaexec
@@ -30,8 +30,13 @@ run_meta() {
       V='--verbose'
     fi
     if [ -n "$metatype" ] && [ -n "$metascript" ] ; then
-      deploy.run --type=$metatype --file=$metascript --ip=$ip --key="$KEY" --cluster="$cluster" --role="$role" --flavor="$flavor" --timestamp=$timestamp --task="$task" --dry $V
-      res=$?
+      if [ -e "${ROLES_ROOT}/$metascript" ] ; then
+        deploy.run --type=$metatype --file=$metascript --ip=$ip --key="$KEY" --cluster="$cluster" --role="$role" --flavor="$flavor" --timestamp=$timestamp --task="$task" --dry $V
+        res=$?
+      else
+        echo "${ROLES_ROOT}/$metascript not found"
+        res=1
+      fi
       if [ -n "$verbose" ] ; then
         if [ -n "$use_color" ] ; then
           [ $res -eq 0 ] && printf "\033[01;32mSuccess\033[00;39m\n" || printf "\033[01;31mError\033[00;39m\n"
@@ -62,8 +67,13 @@ run_meta() {
       V='--verbose'
     fi
     if [ -n "$metatype" ] && [ -n "$metascript" ] ; then
-      deploy.run --type=$metatype --file=$metascript --ip=$ip --key="$KEY" --cluster="$cluster" --role="$role" --flavor="$flavor" --timestamp=$timestamp --task="$task" $V
-      res=$?
+      if [ -e "${ROLES_ROOT}/$metascript" ] ; then
+        deploy.run --type=$metatype --file=$metascript --ip=$ip --key="$KEY" --cluster="$cluster" --role="$role" --flavor="$flavor" --timestamp=$timestamp --task="$task" $V
+        res=$?
+      else
+        echo "${ROLES_ROOT}/$metascript not found"
+        res=1
+      fi
       if [ -n "$verbose" ] ; then
         if [ -n "$use_color" ] ; then
           [ $res -eq 0 ] && printf "\033[01;32mSuccess\033[00;39m\n" || printf "\033[01;31mError\033[00;39m\n"
