single server operation for cloudexec (needed for deployment scripts)

diff --git a/cloud/ec2/cloudexec b/cloud/ec2/cloudexec
--- a/cloud/ec2/cloudexec
+++ b/cloud/ec2/cloudexec
@@ -23,7 +23,7 @@ SSH=`which ssh 2>/dev/null`
 [ -z "$SSH" ] && echo "Ssh utility not found, exiting" && exit 1
 [ -n "$SSHPORT" ] || SSHPORT=22
 [ -f "/sbin/ifconfig" ] && IFCFG=/sbin/ifconfig || IFCFG=`which ifconfig 2>/dev/null`
-possible_options="cluster help region verbose limit"
+possible_options="cluster help region verbose limit ip"
 commflag=0
 for s_option in "${@}"
 do
@@ -75,6 +75,12 @@ if [ "X$help" == "Xyes" ] ; then
   echo "                             run on all clusters mentioned in servers.list."
   echo "  --region=region          - the command will be run on all servers from"
   echo "                             this region."
+  echo "  --ip=IP                  - runs the command on a single server. This"
+  echo "                             allows other scripts to include this one the"
+  echo "                             way that makes possible to apply it to a single"
+  echo "                             server or multiple servers depending on which"
+  echo "                             variables are defined. With this option non-"
+  echo "                             empty, cluster and region are ignored."
   echo "  --verbose                - shows each server details before running the"
   echo "                             command."
   echo "  --limit=N                - runs the command on first N servers of each"
@@ -84,6 +90,7 @@ if [ "X$help" == "Xyes" ] ; then
 fi
 
 [ "X$IFCFG" != "X" ] && localip=`$IFCFG | sed '/inet\ /!d;s/.*r://;s/\ .*//' | grep -v '127.0.0.1'` || localip="ifconfig_not_found"
+[ -n "$ip" ] && cluster= && region=
 [ -n "$cluster" ] || cluster=`cat "${rpath}/../../servers.list" | grep -v ^$ | grep -v  ^#|grep -v ^[[:space:]]*# | cut -d'|' -f5 | sort | uniq`
 declare -i n
 IFS1=$IFS
@@ -96,6 +103,9 @@ if [ "X$command" != "X" ] ; then
     for server in `cat "${rpath}/../../servers.list" | grep -v ^$ | grep -v  ^#|grep -v ^[[:space:]]*#` ; do
       [ -n "$limit" ] && [[ $n -ge $limit ]] && break
       IP=${server%%|*}
+      if [ -n "$ip" ] ; then
+        [ "X$ip" == "X$IP" ] || continue
+      fi
       KEY=`echo $server | cut -d'|' -f2`
       if [ -n "$region" ] ; then
         REGION=`echo $server | cut -d'|' -f3`
@@ -107,13 +117,14 @@ if [ "X$command" != "X" ] ; then
       fi
       if [ "X$verbose" == "Xyes" ] ; then
         echo
-        echo "### Server: $server"
-        echo
+        echo "===== Server: $server"
       fi
       if [ `echo $IP | grep -c "$localip"` -ne 0 ] ; then
         eval $command
       else
-        $SSH -i "${rpath}/../../keys/${KEY}.pem" -p $SSHPORT -o StrictHostKeyChecking=no $IP "$command"
+        [ -f "${rpath}/../../keys/$KEY" ] || KEY="${KEY}.pem"
+        [ -f "${rpath}/../../keys/$KEY" ] || (echo "Key not found for IP $IP" && continue)
+        $SSH -i "${rpath}/../../keys/${KEY}" -p $SSHPORT $IP "$command"
       fi
     done
     n+=1
diff --git a/cloud/ec2/cloudsync b/cloud/ec2/cloudsync
--- a/cloud/ec2/cloudsync
+++ b/cloud/ec2/cloudsync
@@ -86,7 +86,8 @@ if [ "X$help" == "Xyes" ] ; then
   echo "  --recursive              - recursive sync of directories, implies --delete"
   echo "  --cluster=clustername    - the command will be run on all servers"
   echo "                             from this cluster."
-  echo "  --ip                     - ip for a single server operation."
+  echo "  --ip=IP                  - ip for a single server operation."
+  echo "                             If ip is defined, cluster and region are ignored."
   echo "  --region=region          - the command will be run on all servers"
   echo "                             from this region."
   echo "  --verbose                - shows each server details before running"
@@ -96,6 +97,8 @@ fi
 
 [ -n "$recursive" ] && r="-r"
 [ "X$IFCFG" != "X" ] && localip=`$IFCFG | sed '/inet\ /!d;s/.*r://;s/\ .*//' | grep -v '127.0.0.1'` || localip="ifconfig_not_found"
+[ -n "$ip" ] && cluster= && region=
+[ -n "$cluster" ] || cluster=`cat "${rpath}/../../servers.list" | grep -v ^$ | grep -v  ^#|grep -v ^[[:space:]]*# | cut -d'|' -f5 | sort | uniq`
 
 IFS1=$IFS
 IFS='
@@ -104,37 +107,38 @@ if [ "X$command" != "X" ] ; then
   from=${command%% *}
   to=${command#* }
   [ -n "$verbose" ] && echo "### Syncing $from to $to"
-  for server in `cat "${rpath}/../../servers.list" | grep -v ^$ | grep -v ^#|grep -v ^[[:space:]]*#` ; do
-    IP=${server%%|*}
-    if [ -n "$ip" ] ; then
-      [ "X$IP" == "X$ip" ] || continue
-    fi
-    KEY=`echo $server | cut -d'|' -f2`
-    if [ -n "$region" ] ; then
-      REGION=`echo $server | cut -d'|' -f3`
-      [ "X$REGION" == "X$region" ] || continue
-    fi
-    if [ -n "$cluster" ] ; then
-      CLUSTER=`echo $server | cut -d'|' -f5`
-      [ "X$CLUSTER" == "X$cluster" ] || continue
-    fi
-    if [ "X$verbose" == "Xyes" ] ; then
-      echo
-      echo "### Server: $server"
-      echo
-    fi
-    [ -f "${rpath}/../../keys/$KEY" ] || KEY="${KEY}.pem"
-    [ -f "${rpath}/../../keys/$KEY" ] || (echo "Key not found for IP $IP" && continue)
-    if [ `echo $IP | grep -c "$localip"` -ne 0 ] ; then
-      cp -up $from $to
-    else
-      if [ -n "$RSYNC" ] ; then
-        $RSYNC ${r} -e "$SSH -i ${rpath}/../../keys/${KEY} -p $SSHPORT" "$from" "${IP}:${to}"
-        [ $? -eq 0 ] || (printf "Rsync failed, trying scp ...  " && $SCP -i "${rpath}/../../keys/${KEY}" -P $SSHPORT ${r} "$from" "${IP}:${to}" && echo "Success" || echo "ERROR: Unable to cloudsync")
-      else
-        $SCP -i "${rpath}/../../keys/${KEY}" -P $SSHPORT ${r} "$from" "${IP}:${to}"  && echo "Success" || echo "ERROR: Unable to cloudsync"
+  for cluster in `printf "${cluster}\n"|sed 's|,|\n|g'` ; do
+    for server in `cat "${rpath}/../../servers.list" | grep -v ^$ | grep -v ^#|grep -v ^[[:space:]]*#` ; do
+      IP=${server%%|*}
+      if [ -n "$ip" ] ; then
+        [ "X$IP" == "X$ip" ] || continue
       fi
-    fi
+      KEY=`echo $server | cut -d'|' -f2`
+      if [ -n "$region" ] ; then
+        REGION=`echo $server | cut -d'|' -f3`
+        [ "X$REGION" == "X$region" ] || continue
+      fi
+      if [ -n "$cluster" ] ; then
+        CLUSTER=`echo $server | cut -d'|' -f5`
+        [ "X$CLUSTER" == "X$cluster" ] || continue
+      fi
+      if [ "X$verbose" == "Xyes" ] ; then
+        echo
+        echo "===== Server: $server"
+      fi
+      if [ `echo $IP | grep -c "$localip"` -ne 0 ] ; then
+        cp -up $from $to
+      else
+        [ -f "${rpath}/../../keys/$KEY" ] || KEY="${KEY}.pem"
+        [ -f "${rpath}/../../keys/$KEY" ] || (echo "Key not found for IP $IP" && continue)
+        if [ -n "$RSYNC" ] ; then
+          $RSYNC ${r} -e "$SSH -i ${rpath}/../../keys/${KEY} -p $SSHPORT" "$from" "${IP}:${to}"
+          [ $? -eq 0 ] || (printf "Rsync failed, trying scp ...  " && $SCP -i "${rpath}/../../keys/${KEY}" -P $SSHPORT ${r} "$from" "${IP}:${to}" && echo "Success" || echo "ERROR: Unable to cloudsync")
+        else
+          $SCP -i "${rpath}/../../keys/${KEY}" -P $SSHPORT ${r} "$from" "${IP}:${to}"  && echo "Success" || echo "ERROR: Unable to cloudsync"
+        fi
+      fi
+    done
   done
 fi
 IFS=$IFS1
