RETVAL for cloudsync

diff --git a/cloud/ec2/cloudsync b/cloud/ec2/cloudsync
--- a/cloud/ec2/cloudsync
+++ b/cloud/ec2/cloudsync
@@ -95,10 +95,13 @@ if [ "X$help" == "Xyes" ] ; then
   exit 0
 fi
 
+declare -i RETVAL
+RETVAL=0
 [ -n "$recursive" ] && r="-r"
 [ "X$IFCFG" != "X" ] && localip=`$IFCFG | sed '/inet\ /!d;s/.*r://;s/\ .*//' | grep -v '127.0.0.1'` || localip="ifconfig_not_found"
 [ -n "$ip" ] && cluster= && region=
 [ -n "$cluster" ] || cluster=`cat "${rpath}/../../servers.list" | grep -v ^$ | grep -v  ^#|grep -v ^[[:space:]]*# | cut -d'|' -f5 | sort | uniq`
+[ -z "$cluster" ] && echo "No clusters found" && exit 1
 
 IFS1=$IFS
 IFS='
@@ -133,13 +136,20 @@ if [ "X$command" != "X" ] ; then
         [ -f "${rpath}/../../keys/$KEY" ] || (echo "Key not found for IP $IP" && continue)
         if [ -n "$RSYNC" ] ; then
           $RSYNC ${r} -e "$SSH -i ${rpath}/../../keys/${KEY} -p $SSHPORT" "$from" "${IP}:${to}"
-          [ $? -eq 0 ] || (printf "Rsync failed, trying scp ...  " && $SCP -i "${rpath}/../../keys/${KEY}" -P $SSHPORT ${r} "$from" "${IP}:${to}" && echo "Success" || echo "ERROR: Unable to cloudsync")
+          [ $? -eq 0 ] && echo "Success" && continue
+        fi
+        printf "Rsync failed or not found, trying scp ...  "
+        $SCP -i "${rpath}/../../keys/${KEY}" -P $SSHPORT ${r} "$from" "${IP}:${to}"
+        if [ $? -eq 0 ] ; then
+          echo "Success"
         else
-          $SCP -i "${rpath}/../../keys/${KEY}" -P $SSHPORT ${r} "$from" "${IP}:${to}"  && echo "Success" || echo "ERROR: Unable to cloudsync"
+          echo "ERROR: Unable to cloudsync"
+          RETVAL+=1
         fi
       fi
     done
   done
 fi
 IFS=$IFS1
+exit $RETVAL
 
