Cloudsync enhancements

diff --git a/cloud/ec2/cloudsync b/cloud/ec2/cloudsync
--- a/cloud/ec2/cloudsync
+++ b/cloud/ec2/cloudsync
@@ -15,17 +15,29 @@
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
 
-rcommand=${0##*/}
-rpath=${0%/*}
+[[ $0 =~ ^\/ ]] && rroot='/'
+for step in `echo ${0} | tr '/' ' '` ; do
+  rlink=`readlink "${rroot}${rpath}${step}"`
+  if [ -n "$rlink" ] ; then
+    [[ $rlink =~ ^\/ ]] && rpath="${rlink}/" || rpath="${rpath}${rlink}/"
+  else
+    rpath="${rpath}${step}/"
+  fi
+done
+rpath=${rpath%/}
+rcommand=${rpath##*/}
+rpath="${rroot}${rpath%/*}"
 #*/ (this is needed to fix vi syntax highlighting)
-
+source "${rpath}/../../conf/cloud.conf"
 RSYNC=`which rsync 2>/dev/null`
-[ -z "$RSYNC" ] && echo "Rsync utility not found, exiting" && exit 1
+[ -z "$RSYNC" ] && echo "Rsync utility not found, trying scp"
+SCP=`which scp 2>/dev/null`
+[ -n "$SCP" ] && echo "Using scp" || (echo "Neither rsync nor scp is found. Exiting" && exit 1)
 [ -f "/sbin/ifconfig" ] && IFCFG=/sbin/ifconfig || IFCFG=`which ifconfig 2>/dev/null`
 SSH=`which ssh 2>/dev/null`
 [ -z "$SSH" ] && echo "SSH utility not found, exiting" && exit 1
 [ -n "$SSHPORT" ] || SSHPORT=22
-possible_options="cluster help region verbose recursive"
+possible_options="cluster help region verbose recursive ip"
 commflag=0
 for s_option in "${@}"
 do
@@ -73,6 +85,7 @@ if [ "X$help" == "Xyes" ] ; then
   echo "  --recursive              - recursive sync of directories, implies --delete"
   echo "  --cluster=clustername    - the command will be run on all servers"
   echo "                             from this cluster."
+  echo "  --ip                     - ip for a single server operation."
   echo "  --region=region          - the command will be run on all servers"
   echo "                             from this region."
   echo "  --verbose                - shows each server details before running"
@@ -90,9 +103,11 @@ if [ "X$command" != "X" ] ; then
   from=${command%% *}
   to=${command#* }
   [ -n "$verbose" ] && echo "### Syncing $from to $to"
-  
-  for server in `cat "${rpath}/../../servers.list" | grep -v ^$ | grep -v  ^#|grep -v ^[[:space:]]*#` ; do
+  for server in `cat "${rpath}/../../servers.list" | grep -v ^$ | grep -v ^#|grep -v ^[[:space:]]*#` ; do
     IP=${server%%|*}
+    if [ -n "$ip" ] ; then
+      [ "X$IP" == "X$ip" ] || continue
+    fi
     KEY=`echo $server | cut -d'|' -f2`
     if [ -n "$region" ] ; then
       REGION=`echo $server | cut -d'|' -f3`
@@ -107,10 +122,16 @@ if [ "X$command" != "X" ] ; then
       echo "### Server: $server"
       echo
     fi
+    [ -f "$KEY" ] || KEY="${KEY}.pem"
+    [ -f "$KEY" ] || (echo "Key not found for IP $IP" && continue)
     if [ `echo $IP | grep -c "$localip"` -ne 0 ] ; then
       cp -up $from $to
     else
-      $RSYNC ${r} -e "$SSH -i ${rpath}/../../keys/${KEY}.pem -o StrictHostKeyChecking=no -p $SSHPORT" $from ${IP}:${to}
+      if [ -n "$RSYNC" ] ; then
+        $RSYNC ${r} -e "$SSH -i ${rpath}/../../keys/${KEY} -p $SSHPORT" "$from" "${IP}:${to}"
+      else
+        $SCP -i "${rpath}/../../keys/${KEY}" -P $SSHPORT ${r} "$from" "${IP}:${to}"
+      fi
     fi
   done
 fi
