cloud folders re-organized + some fixtures

diff --git a/cloud/ec2/ebs_backup b/cloud/ec2/ebs_backup
--- a/cloud/ec2/ebs_backup
+++ b/cloud/ec2/ebs_backup
@@ -21,9 +21,9 @@ rpath=${0%/*}
 #*/ (this is needed to fix vi syntax highlighting)
 MAILX=`which mail 2>/dev/null`
 currtime=`date`
-echo $currtime > ${rpath}/../ebs_backup.report
-echo "------------------------" >> ${rpath}/../ebs_backup.report
-echo >> ${rpath}/../ebs_backup.report
+echo $currtime > ${rpath}/../../ebs_backup.report
+echo "------------------------" >> ${rpath}/../../ebs_backup.report
+echo >> ${rpath}/../../ebs_backup.report
 possible_options="keep cluster ami state filter noupdate help region"
 necessary_options=""
 #[ "X$*" == "X" ] && echo "Can't run without options. Possible options are: ${possible_options}" && exit 1
@@ -97,14 +97,14 @@ if [ -n "$help" ] ; then
   exit 0
 fi
 
-source ${rpath}/../conf/cloud.conf
+source ${rpath}/../../conf/cloud.conf
 for var in EC2_TOOLS_BIN_PATH JAVA_HOME EC2_HOME EC2_PRIVATE_KEY EC2_CERT EC2_REGION EC2_AK ; do
   [ -z "`eval echo \\$\$var`" ] && echo "$var is not defined! Define it in conf/cloud.conf please." && exit 1
 done
 PATH="${EC2_TOOLS_BIN_PATH}:${PATH}"
 export JAVA_HOME EC2_HOME EC2_PRIVATE_KEY EC2_CERT EC2_REGION PATH
 
-TMPDIR=/tmp/m_script/cloud
+TMPDIR=/tmp/m_script/cloud/ec2
 install -d $TMPDIR
 [ -n "$noupdate" ] && noupdate="--noupdate"
 [ -n "$region" ] && region="--region=$region"
@@ -112,7 +112,7 @@ install -d $TMPDIR
 [ -n "$ami" ] && ami="--ami=$ami"
 [ -n "$state" ] && state="--state=$state"
 
-${rpath}/show_servers "$noupdate" "$region" "$cluster" "$ami" "$state" --filter=bID > $TMPDIR/volumes.list
+${rpath}/../show_servers "$noupdate" "$region" "$cluster" "$ami" "$state" --filter=bID > $TMPDIR/volumes.list
 if [ -n "$keep" ] ; then
   outdated=`date -d "$currtime - $keep days" +"%s"`
   ec2-describe-snapshots $region > $TMPDIR/snapshots.list
@@ -122,24 +122,24 @@ if [ -n "$keep" ] ; then
       snaptime=`echo $snap | awk '{print $5}' | sed 's|T| |'`
       snaptime=`date -d "$snaptime" +"%s"`
       if [[ $snaptime -lt $outdated ]] ; then
-        printf "Deleting snapshot $snapID created at $snaptime ... " >> ${rpath}/../ebs_backup.report
-        printf "`ec2-delete-snapshot $snapID >/dev/null` ... " >> ${rpath}/../ebs_backup.report && echo "DONE" >> ${rpath}/../ebs_backup.report || echo "ERROR" >> ${rpath}/../ebs_backup.report
+        printf "Deleting snapshot $snapID created at $snaptime ... " >> ${rpath}/../../ebs_backup.report
+        printf "`ec2-delete-snapshot $snapID >/dev/null` ... " >> ${rpath}/../../ebs_backup.report && echo "DONE" >> ${rpath}/../../ebs_backup.report || echo "ERROR" >> ${rpath}/../../ebs_backup.report
       fi
     done
-    printf "Creating snapshot of volume $ebs ... " >> ${rpath}/../ebs_backup.report
-    printf "`ec2-create-snapshot $ebs >/dev/null` ... " >> ${rpath}/../ebs_backup.report && echo "DONE" >> ${rpath}/../ebs_backup.report || echo "ERROR" >> ${rpath}/../ebs_backup.report
+    printf "Creating snapshot of volume $ebs ... " >> ${rpath}/../../ebs_backup.report
+    printf "`ec2-create-snapshot $ebs >/dev/null` ... " >> ${rpath}/../../ebs_backup.report && echo "DONE" >> ${rpath}/../../ebs_backup.report || echo "ERROR" >> ${rpath}/../../ebs_backup.report
   done
 else
   for ebs in `cat $TMPDIR/volumes.list` ; do
-    printf "Creating snapshot of volume $ebs ... " >> ${rpath}/../ebs_backup.report
-    printf "`ec2-create-snapshot $ebs >/dev/null` ... " >> ${rpath}/../ebs_backup.report && echo "DONE" >> ${rpath}/../ebs_backup.report || echo "ERROR" >> ${rpath}/../ebs_backup.report
+    printf "Creating snapshot of volume $ebs ... " >> ${rpath}/../../ebs_backup.report
+    printf "`ec2-create-snapshot $ebs >/dev/null` ... " >> ${rpath}/../../ebs_backup.report && echo "DONE" >> ${rpath}/../../ebs_backup.report || echo "ERROR" >> ${rpath}/../../ebs_backup.report
   done
 fi
 if [ -n "$MAILX" ] ; then
   while read RLINE
   do
     if [ -n "${RLINE}" ]; then
-      cat ${rpath}/../ebs_backup.report | ${MAILX} -s "Server $(hostname -f) EBS volume backup report" ${RLINE}
+      cat ${rpath}/../../ebs_backup.report | ${MAILX} -s "Server $(hostname -f) EBS volume backup report" ${RLINE}
     fi
-  done < ${rpath}/mail.backup.list
+  done < ${rpath}/../mail.backup.list
 fi
diff --git a/cloud/ec2/fix_clusters b/cloud/ec2/fix_clusters
--- a/cloud/ec2/fix_clusters
+++ b/cloud/ec2/fix_clusters
@@ -19,6 +19,16 @@ rcommand=${0##*/}
 rpath=${0%/*}
 #*/ (this is needed to fix vi syntax highlighting)
 
+# Array of 3rd party services compatibility tags
+declare -i i
+i=2
+for LINE in `cat ${rpath}/../3rdparty.compat | grep -v ^$|grep -v ^#|grep -v ^[[:space:]]*#` ; do
+  ctag=`echo $LINE | cut -d'|' -f2 | cut -d'%' -f$i`
+  [ -n "$ctag" ] || continue
+  i+=1
+  ctags="${ctags} $ctag"
+done
+
 parse_server() {
   if [[ ${1} =~ ^RESERVATION ]] ; then
     printf "SG::`echo ${1} | awk -F'|' '{print $4}'`|"
@@ -61,17 +71,31 @@ fix_server() {
     b=`echo "$s" | awk -F'::' '{print $2}'`
     case $a in
       icluster)
-        cluster="$b"
+        icluster="$b"
+        [ -n "$cluster" ] && [ "X$icluster" != "X$cluster" ] && IFS=$IFS1 && return 0
         ;;
       itag)
         c=${b%=*}
         d=${b#*=}
-        if [ "X$c" == "Xscalr-role-name" ] ; then
-          scalrrole="$d"
-        fi
-        if [ "X$c" == "Xscalr-farm-name" ] ; then
-          scalrfarm="$d"
-        fi
+        for ctag in $ctags ; do
+          if [ "X$c" == "Xctag" ] ; then
+            cleft=`cat ${rpath}/../3rdparty.compat | grep -v ^$|grep -v ^#|grep -v ^[[:space:]]*#|grep "%${ctag}%"|awk -F'|' '{print $1}'`
+            if [ -n "$compat" ] ; then
+              provider=`echo "$compat" | awk -F'::' '{print $1}'`
+              if [ "X$provider" == "X$cleft" ] ; then
+                compatstring=`echo "$compat" | awk -F'::' '{print $2}'|sed "s|%${ctag}%|$d|g"`
+              else
+                echo "Check this server, looks like it has tags from several service providers messed up:" >> "${rpath}/../../fix_clusters.report"
+                echo "${1}" >> "${rpath}/../../fix_clusters.report"
+                echo "Giving up for now" >> "${rpath}/../../fix_clusters.report"
+                break
+              fi
+            else
+              cright=`cat ${rpath}/../3rdparty.compat | grep -v ^$|grep -v ^#|grep -v ^[[:space:]]*#|grep "%${ctag}%"|awk -F'|' '{print $2}'|sed "s|%${ctag}%|$d|g"`
+              compat="${cleft}::${cright}"
+            fi
+          fi
+        done
         ;;
       iID)
         id=$b
@@ -97,31 +121,46 @@ fix_server() {
     esac
   done
   IFS=$IFS1
-  if [ -n "$cluster" ] ; then
-    clusterdetails=`grep "^${cluster}|" "${rpath}/../conf/clusters.conf" | tail -1`
-    ### Cluster name|Key name|Availability zone|Security group|Instance type|AMI|Scalable?
-    keypairconf=`echo $clusterdetails | cut -d'|' -f2`
-    zoneconf=`echo $clusterdetails | cut -d'|' -f3`
-    sgconf=`echo $clusterdetails | cut -d'|' -f4`
-    sizeconf=`echo $clusterdetails | cut -d'|' -f4`
-    amiconf=`echo $clusterdetails | cut -d'|' -f5`
-    scaleconf=`echo $clusterdetails | cut -d'|' -f6`
-    if [ "X$keypair" != "X$keypairconf" ] ; then
-      if [ -f "${rpath}/../keys/${keypairconf}.pem" ] ; then
-        if [ `grep "^${keypair}|" "${rpath}/../conf/keys.compat" 2>/dev/null | grep -c "${keypairconf}"` -eq 0 ] ; then
-          if [ `grep -c "^${keypair}|" "${rpath}/../conf/keys.compat" 2>/dev/null` -ne 0 ] ; then
-            sed -i -e "/${keypair}|/s/$/|${keypairconf}/" "${rpath}/../conf/keys.compat"
-          else
-            echo "${keypair}|${keypairconf}" >> "${rpath}/../conf/keys.compat"
+  if [ -n "$icluster" ] ; then
+    clusterdetails=`grep "^${icluster}|" "${rpath}/../../conf/clusters.conf" | tail -1`
+    ### Cluster name|Key name|Availability zone|Security group|Instance type|AMI|Scalable?|M-Script path|3rd party compatibility
+    if [ -n "$clusterdetails" ] ; then
+      keypairconf=`echo $clusterdetails | cut -d'|' -f2`
+      zoneconf=`echo $clusterdetails | cut -d'|' -f3`
+      sgconf=`echo $clusterdetails | cut -d'|' -f4`
+      sizeconf=`echo $clusterdetails | cut -d'|' -f4`
+      amiconf=`echo $clusterdetails | cut -d'|' -f5`
+      scaleconf=`echo $clusterdetails | cut -d'|' -f6`
+      if [ "X$keypair" != "X$keypairconf" ] ; then
+        if [ -f "${rpath}/../../keys/${keypairconf}.pem" ] ; then
+          if [ `grep "^${keypair}|" "${rpath}/../../conf/keys.compat" 2>/dev/null | grep -c "${keypairconf}"` -eq 0 ] ; then
+            if [ `grep -c "^${keypair}|" "${rpath}/../../conf/keys.compat" 2>/dev/null` -ne 0 ] ; then
+              sed -i -e "/${keypair}|/s/$/|${keypairconf}/" "${rpath}/../../conf/keys.compat"
+            else
+              echo "${keypair}|${keypairconf}" >> "${rpath}/../../conf/keys.compat"
+            fi
           fi
+        else
+          echo "Key file ${rpath}/../../keys/${keypairconf}.pem not found" >> "${rpath}/../../fix_clusters.report"
         fi
-      else
-        echo "Key file ${rpath}/../keys/${keypairconf}.pem not found" >> "${rpath}/../fix_clusters.report"
       fi
     fi
-    
+  else
+    # No cluster server found. Checking if it belongs to 3rd party services 
+    if [ -n "$provider" ] ; then
+      if [ -n "$compatstring" ] ; then
+        if [[ "$compatstring" =~ '%' ]] ; then
+          echo "Failed to generate a cluster name from compatible tags:" >> "${rpath}/../../fix_clusters.report"
+          echo "${provider}::${compatstring}" >> "${rpath}/../../fix_clusters.report"
+          echo "The server was:" >> "${rpath}/../../fix_clusters.report"
+          echo "$1" >> "${rpath}/../../fix_clusters.report"
+          return 0
+        else
+        
+        fi
+      fi
+    fi
   fi
-  
 }
 
 DIFF=`which diff 2>/dev/null`
@@ -131,6 +170,7 @@ SED=`which sed 2>/dev/null`
 SSH=`which ssh 2>/dev/null`
 [ -z "$SSH" ] && echo "Ssh utility not found, exiting" && exit 1
 IFCFG=`which ifconfig 2>/dev/null`
+
 possible_options="cluster help region"
 necessary_options=""
 #[ "X$*" == "X" ] && echo "Can't run without options. Possible options are: ${possible_options}" && exit 1
@@ -178,16 +218,15 @@ if [ "X$help" == "Xyes" ] ; then
   exit 0
 fi
 
-source ${rpath}/../conf/cloud.conf
+source ${rpath}/../../conf/cloud.conf
 
 for var in JAVA_HOME EC2_HOME EC2_PRIVATE_KEY EC2_CERT EC2_REGION EC2_TOOLS_BIN_PATH ; do
   [ -z "`eval echo \\$\$var`" ] && echo "$var is not defined! Define it in conf/cloud.conf please." && exit 1
 done
 PATH="${EC2_TOOLS_BIN_PATH}:${PATH}"
 export JAVA_HOME EC2_HOME EC2_PRIVATE_KEY EC2_CERT EC2_REGION PATH
-TMPDIR=/tmp/m_script/cloud
-install -d $TMPDIR
-
+TMPDIR=/tmp/m_script/cloud/ec2
+[ -f "$TMPDIR/servers.${EC2_REGION}.tmp" ] || (echo "Looks like ${rpath}/../update_servers_list has never run before. Run it first please." && exit 1)
 [ -n "$region" ] && EC2_REGION=$region
 
 while read SERVER
@@ -204,7 +243,7 @@ do
       current_server="$current_server`parse_server $SERVER`"
     fi
   fi
-done<$TMPDIR/ec2.servers.${EC2_REGION}.tmp
+done<$TMPDIR/servers.${EC2_REGION}.tmp
 fix_server "$current_server" && unset current_server
 unset newr current_server
 
diff --git a/cloud/ec2/save_server b/cloud/ec2/save_server
--- a/cloud/ec2/save_server
+++ b/cloud/ec2/save_server
@@ -20,8 +20,8 @@ rcommand=${0##*/}
 rpath=${0%/*}
 #*/ (this is needed to fix vi syntax highlighting)
 
-possible_options="cluster ami number aki region zone"
-necessary_options=""
+possible_options="name aki region"
+necessary_options="name"
 [ "X$*" == "X" ] && echo "Can't run without options. Possible options are: ${possible_options}" && exit 1
 for s_option in "${@}"
 do
@@ -65,31 +65,43 @@ if [[ found -eq 1 ]]; then
   exit 1
 fi
 
-source ${rpath}/../conf/cloud.conf
-for var in AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY EC2_TOOLS_BIN_PATH JAVA_HOME EC2_HOME EC2_PRIVATE_KEY EC2_CERT EC2_REGION EC2_AK ; do
+source ${rpath}/../../conf/cloud.conf
+for var in BUCKETNAME EXCLUDE_PATHS SAVED_FILES_PATH AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY EC2_TOOLS_BIN_PATH JAVA_HOME EC2_HOME EC2_PRIVATE_KEY EC2_CERT EC2_REGION ; do
   [ -z "`eval echo \\$\$var`" ] && echo "$var is not defined! Define it in conf/cloud.conf please." && exit 1
 done
-PATH="${EC2_TOOLS_BIN_PATH}:${PATH}"
+PATH="${EC2_TOOLS_BIN_PATH}:${EC2_AMI_TOOLS_BIN_PATH}:${PATH}"
 export JAVA_HOME EC2_HOME EC2_PRIVATE_KEY EC2_CERT AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY EC2_REGION PATH
-
-TMPDIR=/tmp/m_script/cloud
-install -d $TMPDIR
-
 [ -n "$region" ] && EC2_REGION=$region
-
-[ "X`which ec2-start-instances`" == "X" ] && echo "API Tools needed" && exit 1
-[ "X$aki" == "X" ] || aki="--kernel $aki"
-[ "X$number" == "X" ] || number="-n $number"
-[ "X$zone" == "X" ] || zone="-z $zone"
-if [ "X$ami" == "X" ] ; then
-  amiID=`ec2-describe-images -K "$EC2_PRIVATE_KEY" -C "$EC2_CERT" --region $EC2_REGION | grep ^IMAGE | awk '{print $2" "$3}' | grep "${name}" | head -1 | awk '{print $1}'`
-  [ -n "$amiID" ] && echo "Found AMI: $amiID" || (echo "Unable to find any AMI to use" && exit 1)
+TMPDIR=/tmp/m_script/cloud/ec2
+if [[ $BUCKETNAME =~ ^s3 ]] ; then
+  FULLBUCKETNAME="$BUCKETNAME"
+  BUCKETNAME="${BUCKETNAME#*://}"
 else
-  amiID=$ami
+  FULLBUCKETNAME="s3://$BUCKETNAME"
 fi
-instances=`ec2-run-instances -K "$EC2_PRIVATE_KEY" -C "$EC2_CERT" -k $EC2_AK --region $EC2_REGION $aki $number $amiID | grep ^INSTANCE | awk '{print $2}' | sed 's/\n/ /g'`
-echo $instances
-[ "X$cluster" == "X" ] || ec2tag -K "$EC2_PRIVATE_KEY" -C "$EC2_CERT" --region $EC2_REGION $instances --tag cluster=${cluster}
+install -d $TMPDIR
+install -d $SAVED_FILES_PATH
+for E in $EXCLUDE_PATHS
+do
+  [ -e $E ] || ex=0
+done
+[ "X$ex" != "X0" ] && EXCLUDE="-e $EXCLUDE_PATHS" || EXCLUDE=""
+[ "X$name" == "X" ] && echo "Name needed" && exit 1
+[ "X`which ec2-bundle-vol`" == "X" ] && echo "AMI Tools needed" && exit 1
+[ "X`which ec2-register`" == "X" ] && echo "API Tools needed" && exit 1
 
-
+S3CMD=`which s3cmd 2>/dev/null`
+if [ -n "$S3CMD" ] ; then
+  echo "Removing AMI with the same name, if any"
+  $S3CMD del "${FULLBUCKETNAME}/${name}"*
+else
+  echo "Warning: S3cmd not found, so S3 bucket ${BUCKETNAME} has not been searched for previously saved AMI with the same name. No worries, this search is just a precaution."
+fi
+[ -n "$aki" ] && aki="--kernel $aki"
+rm -rf ${SAVED_FILES_PATH%/}/image* ${SAVED_FILES_PATH%/}/img-mnt* ${SAVED_FILES_PATH%/}/${name} ${SAVED_FILES_PATH%/}/${name}.manifest.xml ${SAVED_FILES_PATH%/}/${name}.part.* 2>/dev/null
+ec2-bundle-vol -r $ARCH --prefix "${name}" -d ${SAVED_FILES_PATH} --user $EC2_USERID $EXCLUDE -k $EC2_PRIVATE_KEY -c $EC2_CERT "$aki"
+ec2-upload-bundle -b "${BUCKETNAME}" -m "${SAVED_FILES_PATH%/}/${name}".manifest.xml -a $AWS_ACCESS_KEY_ID -s $AWS_SECRET_ACCESS_KEY
+amiID=`ec2-describe-images -K "$EC2_PRIVATE_KEY" -C "$EC2_CERT" --region $EC2_REGION | grep ^IMAGE | awk '{print $2" "$3}' | grep "${name}" | head -1 | awk '{print $1}'`
+[ -n "$amiID" ] && echo "The name ${name} is registered. De-registering first" && echo "Deregistered: `ec2-deregister -K $EC2_PRIVATE_KEY -C $EC2_CERT --region $EC2_REGION $amiID | cut -d' ' -f2`" 
+echo "Registered: `ec2-register -K $EC2_PRIVATE_KEY -C $EC2_CERT --region $EC2_REGION ${BUCKETNAME}/${name}.manifest.xml -n ${name} | cut -d' ' -f2`"
 
diff --git a/cloud/ec2/sync_nginx_proxy b/cloud/ec2/sync_nginx_proxy
--- a/cloud/ec2/sync_nginx_proxy
+++ b/cloud/ec2/sync_nginx_proxy
@@ -20,7 +20,7 @@ rpath=${0%/*}
 #*/ (this is needed to fix vi syntax highlighting)
 DIFF=`which diff 2>/dev/null`
 [ -z "$DIFF" ] && echo "Diff utility not found, exiting" && exit 1
-possible_options="cluster help"
+possible_options="cluster help region"
 necessary_options=""
 #[ "X$*" == "X" ] && echo "Can't run without options. Possible options are: ${possible_options}" && exit 1
 for s_option in "${@}"
@@ -77,18 +77,21 @@ if [[ found -eq 1 ]]; then
   exit 1
 fi
 
-source ${rpath}/../conf/cloud.conf
+source ${rpath}/../../conf/cloud.conf
 
-for var in APP_SERVERS NGINX_PROXY_CLUSTER_CONF_DIR NGINX_RC_SCRIPT NGINX_RELOAD_COMMAND ; do
+for var in JAVA_HOME EC2_HOME EC2_PRIVATE_KEY EC2_CERT EC2_REGION EC2_TOOLS_BIN_PATH APP_SERVERS NGINX_PROXY_CLUSTER_CONF_DIR NGINX_RC_SCRIPT NGINX_RELOAD_COMMAND ; do
   [ -z "`eval echo \\$\$var`" ] && echo "$var is not defined! Define it in conf/cloud.conf please." && exit 1
 done
 PATH="${EC2_TOOLS_BIN_PATH}:${PATH}"
-export JAVA_HOME EC2_HOME EC2_PRIVATE_KEY EC2_CERT EC2_REGION PATH
-
-TMPDIR=/tmp/m_script/cloud
+export JAVA_HOME EC2_HOME EC2_PRIVATE_KEY EC2_CERT EC2_REGION
+TMPDIR=/tmp/m_script/cloud/ec2
 install -d $TMPDIR
 install -d $NGINX_PROXY_CLUSTER_CONF_DIR
 
+[ -n "$region" ] && EC2_REGION=$region
+
+`which date` >> ${rpath}/../../cloud.log
+echo "------------------" >> ${rpath}/../../cloud.log
 if [ -z "$cluster" ] ; then
   CLUSTERS=`for CLUSTER in $APP_SERVERS; do names="${names}\n${CLUSTER%:*}"; done; printf "$names" | sort | uniq` ; CLUSTERS=`echo $CLUSTERS`
 else
@@ -102,16 +105,19 @@ for cluster in "$CLUSTERS" ; do
       ports="$ports ${CLUSTER#*:}"
     fi
   done
-  [ -f $TMPDIR/${cluster}.servers.ips ] && mv $TMPDIR/${cluster}.servers.ips $TMPDIR/${cluster}.servers.ips.prev || ${rpath}/update_servers_list
-  for IP in `cat $TMPDIR/ec2.servers.ips | awk -F'|' '{print $1" "$14}' | grep "$cluster" | awk '{print $1}'` ; do
+  [ -f $TMPDIR/${cluster}.servers.ips ] && mv $TMPDIR/${cluster}.servers.ips $TMPDIR/${cluster}.servers.ips.prev
+  [ -x ${EC2_TOOLS_BIN_PATH}/ec2-describe-instances ] || (echo "ec2-describe-instances binary not found! Exiting.." >> ${rpath}/../../cloud.log && exit 1)
+  for IP in `${EC2_TOOLS_BIN_PATH}/ec2-describe-instances -K "$EC2_PRIVATE_KEY" -C "$EC2_CERT" -F "tag:cluster=$cluster" --show-empty-fields --region $EC2_REGION | grep '^INSTANCE' | awk '{print $18}'` ; do
+#    echo "IP: $IP" >> ${rpath}/../../cloud.log
     for PORT in $ports ; do
       PORT=${PORT#* }; PORT=${PORT% *}
+#      echo "port: $PORT" >> ${rpath}/../../cloud.log
       echo "$IP:$PORT" >> $TMPDIR/${cluster}.servers.ips
     done
   done
+  [ -f $TMPDIR/${cluster}.servers.ips ] || (echo "IP list doesn't exist! Exiting.." >> ${rpath}/../../cloud.log && exit 1)
   [ -f $TMPDIR/${cluster}.servers.ips.prev ] && [ -f $TMPDIR/${cluster}.servers.ips ] && [ -z "`$DIFF -q $TMPDIR/${cluster}.servers.ips.prev $TMPDIR/${cluster}.servers.ips`" ] && continue
   if [ `cat $TMPDIR/${cluster}.servers.ips | grep -v ^$ | wc -l` -gt 0 ] ; then
-    changed=1
     echo "upstream $cluster {" > $NGINX_PROXY_CLUSTER_CONF_DIR/${cluster}.conf
     echo "  ip_hash;" >> $NGINX_PROXY_CLUSTER_CONF_DIR/${cluster}.conf
     while read IP; do
@@ -119,7 +125,7 @@ for cluster in "$CLUSTERS" ; do
     done<$TMPDIR/${cluster}.servers.ips
     echo "}">> $NGINX_PROXY_CLUSTER_CONF_DIR/${cluster}.conf
   else
-    echo "IP list is empty! Exiting.." >> ${rpath}/../cloud.log
+    echo "IP list is empty! Exiting.." >> ${rpath}/../../cloud.log
     exit 1
   fi
 done
diff --git a/cloud/ec2/update_servers_list b/cloud/ec2/update_servers_list
--- a/cloud/ec2/update_servers_list
+++ b/cloud/ec2/update_servers_list
@@ -71,45 +71,45 @@ if [ "X$help" == "Xyes" ] ; then
   exit 0
 fi
 
-source ${rpath}/../conf/cloud.conf
+source ${rpath}/../../conf/cloud.conf
 
 for var in JAVA_HOME EC2_HOME EC2_PRIVATE_KEY EC2_CERT EC2_REGION EC2_TOOLS_BIN_PATH ; do
   [ -z "`eval echo \\$\$var`" ] && echo "$var is not defined! Define it in conf/cloud.conf please." && exit 1
 done
 PATH="${EC2_TOOLS_BIN_PATH}:${PATH}"
 export JAVA_HOME EC2_HOME EC2_PRIVATE_KEY EC2_CERT EC2_REGION PATH
-TMPDIR=/tmp/m_script/cloud
+TMPDIR=/tmp/m_script/cloud/ec2
 install -d $TMPDIR
 
 [ -n "$region" ] && EC2_REGION=$region
 
 [ "X$IFCFG" == "X" ] || localip=`$IFCFG | sed '/inet\ /!d;s/.*r://;s/\ .*//' | grep -v '127.0.0.1'`
-`which date` >> ${rpath}/../cloud.log
-echo "------------------" >> ${rpath}/../cloud.log
+`which date` >> ${rpath}/../../cloud.log
+echo "------------------" >> ${rpath}/../../cloud.log
 
 changed=0
-[ -f $TMPDIR/ec2.servers.${EC2_REGION}.ips ] && mv $TMPDIR/ec2.servers.${EC2_REGION}.ips $TMPDIR/ec2.servers.${EC2_REGION}.ips.prev
-[ -x ${EC2_TOOLS_BIN_PATH}/ec2-describe-instances ] || (echo "ec2-describe-instances binary not found! Exiting.." >> ${rpath}/../cloud.log && exit 1)
+[ -f $TMPDIR/servers.${EC2_REGION}.ips ] && mv $TMPDIR/servers.${EC2_REGION}.ips $TMPDIR/servers.${EC2_REGION}.ips.prev
+[ -x ${EC2_TOOLS_BIN_PATH}/ec2-describe-instances ] || (echo "ec2-describe-instances binary not found! Exiting.." >> ${rpath}/../../cloud.log && exit 1)
   
-${EC2_TOOLS_BIN_PATH}/ec2-describe-instances -K "$EC2_PRIVATE_KEY" -C "$EC2_CERT" --region $EC2_REGION | sed 's/\t/|/g' > $TMPDIR/ec2.servers.${EC2_REGION}.tmp
+${EC2_TOOLS_BIN_PATH}/ec2-describe-instances -K "$EC2_PRIVATE_KEY" -C "$EC2_CERT" --region $EC2_REGION | sed 's/\t/|/g' > $TMPDIR/servers.${EC2_REGION}.tmp
 firstline=1
 IFS1=$IFS
 IFS='
 '
-for SERVER in `cat $TMPDIR/ec2.servers.${EC2_REGION}.tmp`
+for SERVER in `cat $TMPDIR/servers.${EC2_REGION}.tmp`
 do
   if [[ $SERVER =~ ^RESERVATION ]] ; then 
     if [[ $firstline -eq 0 ]] ; then
       if [ "X$state" == "Xrunning" ] ; then
-        if [ -f "${rpath}/../keys/${keypair}.pem" ] ; then
+        if [ -f "${rpath}/../../keys/${keypair}.pem" ] ; then
           if [ `echo $inIP | grep -c $localip` -ne 0 ] ; then
             sname=`hostname`
           else
-            sname=`$SSH -i "${rpath}/../keys/${keypair}.pem" -o StrictHostKeyChecking=no $inIP hostname 2>/dev/null`
+            sname=`$SSH -i "${rpath}/../../keys/${keypair}.pem" -o StrictHostKeyChecking=no $inIP hostname 2>/dev/null`
           fi
         fi
-        [ "X$sname" == "X" ] && echo "Unable to retrieve hostname of the server with IP $inIP|$extIP" >> ${rpath}/../cloud.log
-        echo "$inIP|$extIP|$iID|$ami|$state|$keypair|$isize|$secgroup|$started|$zone|$aki|$ari|$sname|$cluster" >> $TMPDIR/ec2.servers.${EC2_REGION}.ips
+        [ "X$sname" == "X" ] && echo "Unable to retrieve hostname of the server with IP $inIP|$extIP" >> ${rpath}/../../cloud.log
+        echo "$inIP|$extIP|$iID|$ami|$state|$keypair|$isize|$secgroup|$started|$zone|$aki|$ari|$sname|$cluster" >> $TMPDIR/servers.${EC2_REGION}.ips
       fi
       unset inIP extIP iID ami state keypair isize secgroup started zone aki ari cluster sname
     else
@@ -137,20 +137,20 @@ do
 done
 
 if [ "X$state" == "Xrunning" ] ; then
-  if [ -f "${rpath}/../keys/${keypair}.pem" ] ; then
+  if [ -f "${rpath}/../../keys/${keypair}.pem" ] ; then
     if [ `echo $inIP | grep -c $localip` -ne 0 ] ; then
       sname=`hostname`
     else
-      sname=`$SSH -i "${rpath}/../keys/${keypair}.pem" -o StrictHostKeyChecking=no $inIP hostname 2>/dev/null`
+      sname=`$SSH -i "${rpath}/../../keys/${keypair}.pem" -o StrictHostKeyChecking=no $inIP hostname 2>/dev/null`
     fi
   fi
-  [ "X$sname" == "X" ] && echo "Unable to retrieve hostname of the server with IP $inIP|$extIP" >> ${rpath}/../cloud.log
-  echo "$inIP|$extIP|$iID|$ami|$state|$keypair|$isize|$secgroup|$started|$zone|$aki|$ari|$sname|$cluster" >> $TMPDIR/ec2.servers.${EC2_REGION}.ips
+  [ "X$sname" == "X" ] && echo "Unable to retrieve hostname of the server with IP $inIP|$extIP" >> ${rpath}/../../cloud.log
+  echo "$inIP|$extIP|$iID|$ami|$state|$keypair|$isize|$secgroup|$started|$zone|$aki|$ari|$sname|$cluster" >> $TMPDIR/servers.${EC2_REGION}.ips
 fi
 
-[ -f $TMPDIR/ec2.servers.${EC2_REGION}.ips.prev ] && [ -f $TMPDIR/ec2.servers.${EC2_REGION}.ips ] && [ -z "`$DIFF -q $TMPDIR/ec2.servers.${EC2_REGION}.ips.prev $TMPDIR/ec2.servers.${EC2_REGION}.ips`" ] && exit 0
+[ -f $TMPDIR/servers.${EC2_REGION}.ips.prev ] && [ -f $TMPDIR/servers.${EC2_REGION}.ips ] && [ -z "`$DIFF -q $TMPDIR/servers.${EC2_REGION}.ips.prev $TMPDIR/servers.${EC2_REGION}.ips`" ] && exit 0
 
-$SED -i -e "/|${EC2_REGION}|.*$/d" ${rpath}/../servers.list
+$SED -i -e "/|${EC2_REGION}|.*$/d" ${rpath}/../../servers.list
 
 while read SERVER
 do
@@ -158,17 +158,17 @@ do
   keypair=`echo $SERVER | awk -F'|' '{print $6}'`
   sname=`echo $SERVER | awk -F'|' '{print $13}'`
   srole=`echo $SERVER | awk -F'|' '{print $14}'`
-  echo "${inIP}|${keypair}|${EC2_REGION}|${sname}|${srole}" >> ${rpath}/../servers.list
-done<$TMPDIR/ec2.servers.${EC2_REGION}.ips
+  echo "${inIP}|${keypair}|${EC2_REGION}|${sname}|${srole}" >> ${rpath}/../../servers.list
+done<$TMPDIR/servers.${EC2_REGION}.ips
 
 unset inIP extIP keypair iID ami state isize secgroup started zone aki ari sname srole
 
 if [ -n "$NGINX_PROXY_CLUSTER_CONF_DIR" ] ; then
-  ${rpath}/update_nginx_proxy
+  ${rpath}/../update_nginx_proxy
 fi
-${rpath}/update_hosts_file
-${rpath}/update_mynetworks
-#${rpath}/update_firewalls
+${rpath}/../update_hosts_file
+${rpath}/../update_mynetworks
+#${rpath}/../update_firewalls
 
 IFS=$IFS1
 
