more output options for get_ips

diff --git a/cloud/ec2/get_ips b/cloud/ec2/get_ips
--- a/cloud/ec2/get_ips
+++ b/cloud/ec2/get_ips
@@ -19,7 +19,8 @@ rcommand=${0##*/}
 rpath=${0%/*}
 #*/ (this is needed to fix vi syntax highlighting)
 
-possible_options="cluster help region delimiter limit"
+SSH=`which ssh 2>/dev/null`
+possible_options="cluster help region delimiter limit names quoted spaces"
 commflag=0
 for s_option in "${@}"
 do
@@ -63,6 +64,12 @@ if [ "X$help" == "Xyes" ] ; then
   exit 0
 fi
 
+function ip_to_name() {
+  rname1=`grep "^${1}[[:space:]]" /etc/hosts | awk '{print $2}'`
+  [ -n "$rname1" ] && rname2=`grep "^${1}[[:space:]]" /etc/hosts | awk '{print $3}'` || rname=${1}
+  [ -n "$rname2" ] && [ ${#rname2} -lt ${#rname1} ] && rname=$rname2 || rname=$rname1
+}
+
 IFS1=$IFS
 IFS='
 '
@@ -70,7 +77,6 @@ declare -i n
 n=1
 for server in `cat "${rpath}/../../servers.list" | grep -v ^$ | grep -v ^# | grep -v ^[[:space:]]*#` ; do
   IP=${server%%|*}
-  KEY=`echo $server | cut -d'|' -f2`
   if [ -n "$region" ] ; then
     REGION=`echo $server | cut -d'|' -f3`
     [ "X$REGION" == "X$region" ] || continue
@@ -79,8 +85,23 @@ for server in `cat "${rpath}/../../servers.list" | grep -v ^$ | grep -v ^# | gre
     CLUSTER=`echo $server | cut -d'|' -f5`
     [ "X$CLUSTER" == "X$cluster" ] || continue
   fi
+  if [ -n "$names" ] ; then
+    ip_to_name $IP
+    if [ -z "$rname" ] ; then
+      KEY=`echo $server | cut -d'|' -f2`
+      [ -f "${rpath}/../../keys/$KEY" ] || KEY="${KEY}.pem"
+      [ -f "${rpath}/../../keys/$KEY" ] || (echo "Key not found for IP $IP" && continue)
+      [ -n "$SSH" ] && rname=`$SSH -i "${rpath}/../../keys/$KEY" $IP hostname`
+      [ -n "$rname" ] && IP=$rname
+    fi
+  fi
   if [ -n "$delimiter" ] ; then
-    ips="${ips}`printf "${IP}${delimiter}"`"
+    [ -n "$spaces" ] && delimiter="$delimiter "
+    if [ -n "$quoted" ] ; then
+      ips="${ips}`printf "\"${IP}\"${delimiter}"`"
+    else
+      ips="${ips}`printf "${IP}${delimiter}"`"
+    fi
   else
     echo $IP
   fi
diff --git a/deployment/deploy_file b/deployment/deploy_file
--- a/deployment/deploy_file
+++ b/deployment/deploy_file
@@ -23,7 +23,7 @@ rpath=${0%/*}
 SSH=`which ssh 2>/dev/null`
 [ -z "$SSH" ] && echo "SSH utility not found, exiting" && exit 1
 RSYNC=`which rsync 2>/dev/null`
-possible_options="cluster help region verbose flavor"
+possible_options="cluster help region verbose flavor ip"
 commflag=0
 for s_option in "${@}"
 do
@@ -103,6 +103,9 @@ if [ "X$command" != "X" ] ; then
   [ -n "$verbose" ] && echo "### Deploying $from to $to"
   for server in `cat "${rpath}/../servers.list" | grep -v ^$ | grep -v  ^#|grep -v ^[[:space:]]*#` ; do
     IP=${server%%|*}
+    if [ -n "$ip" ] ; then
+      [ "X$ip" == "X$IP" ] || continue
+    fi
     KEY=`echo $server | cut -d'|' -f2`
     if [ -n "$region" ] ; then
       REGION=`echo $server | cut -d'|' -f3`
@@ -120,7 +123,9 @@ if [ "X$command" != "X" ] ; then
     if [ `echo $IP | grep -c "$localip"` -ne 0 ] ; then
       cp -up $tmpfile $to
     else
-      $RSYNC -e "$SSH -i ${rpath}/../keys/${KEY}.pem -o StrictHostKeyChecking=no" $tmpfile ${IP}:${to} || `which scp` -i ${rpath}/../keys/${KEY}.pem -o StrictHostKeyChecking=no $tmpfile ${IP}:${to}
+      [ -f "${rpath}/../../keys/$KEY" ] || KEY="${KEY}.pem"
+      [ -f "${rpath}/../../keys/$KEY" ] || (echo "Key not found for IP $IP" && continue)
+      cloudsync --ip=$IP "$tmpfile" "${to}"
     fi
   done
 fi
