Apex zone support for route53 added

diff --git a/cloud/ec2/route53query b/cloud/ec2/route53query
--- a/cloud/ec2/route53query
+++ b/cloud/ec2/route53query
@@ -27,7 +27,7 @@ TMPDIR=/tmp/m_script/cloud/ec2
 install -d $TMPDIR
 CURL="$CURL -s"
 
-possible_options="region action id zone name type value items wholezone noupdate comment"
+possible_options="region action id zone name type value items wholezone noupdate comment hostedzoneid dnsname"
 necessary_options="action"
 [ "X$*" == "X" ] && echo "Can't run without options. Possible options are: ${possible_options}" && exit 1
 for s_option in "${@}"
@@ -88,10 +88,11 @@ case $action in
     $CURL -H "Content-Type: text/xml; charset=UTF-8" -H "Date: $server_date" -H "X-Amzn-Authorization: AWS3-HTTPS AWSAccessKeyId=$AWS_ACCESS_KEY_ID,Algorithm=HmacSHA1,Signature=$signature" https://route53.amazonaws.com/2011-05-05/hostedzone > $TMPDIR/r53.list.xml
     ${rpath}/../../lib/xml2txt $TMPDIR/r53.list.xml > $TMPDIR/r53.list.txt
     grep ^ListHostedZonesResponse_HostedZones_HostedZone_Id $TMPDIR/r53.list.txt | cut -d' ' -f2 | sed 's|/hostedzone/||' > $TMPDIR/r53.list.ids
-    [ `cat $TMPDIR/r53.list.ids | wc -l` -ne 0 ] && rm -f "${rpath}/../../$CLOUD.dnszones.list"
+    [ -z "$noupdate" ] && [ `cat $TMPDIR/r53.list.ids | wc -l` -ne 0 ] && rm -f "${rpath}/../../$CLOUD.dnszones.list"
+    [ -f "${rpath}/../../$CLOUD.dnszones.list" ] || touch "${rpath}/../../$CLOUD.dnszones.list"
     while read zoneid ; do
-    zonename=`grep -A 1 "${zoneid}$" $TMPDIR/r53.list.txt | tail -1 | cut -d' ' -f2`
-    [ -x "$noupdate" ] && [[ `grep -c ^$zoneid|$zonename$ ${rpath}/../../$CLOUD.dnszones.list 2>/dev/null` -eq 0 ]] && echo "$zoneid|$zonename" && echo "$zoneid|$zonename" >> "${rpath}/../../$CLOUD.dnszones.list"
+      zonename=`grep -A 1 "${zoneid}$" $TMPDIR/r53.list.txt | tail -1 | cut -d' ' -f2`
+      [ -z "$noupdate" ] && [[ `grep -c "^$zoneid|$zonename$" "${rpath}/../../$CLOUD.dnszones.list"` -eq 0 ]] && echo "$zoneid|$zonename" >> "${rpath}/../../$CLOUD.dnszones.list"
     done < $TMPDIR/r53.list.ids
     cat "${rpath}/../../$CLOUD.dnszones.list"
     ;;
@@ -194,6 +195,43 @@ case $action in
     echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?><ChangeResourceRecordSetsRequest xmlns=\"https://route53.amazonaws.com/doc/2011-05-05/\"><ChangeBatch><Comment></Comment><Changes><Change><Action>CREATE</Action><ResourceRecordSet><Name>${name}.</Name><Type>$type</Type><TTL>300</TTL><ResourceRecords><ResourceRecord><Value>$value</Value></ResourceRecord></ResourceRecords></ResourceRecordSet></Change></Changes></ChangeBatch></ChangeResourceRecordSetsRequest>" > $request
     requrl="https://route53.amazonaws.com/2011-05-05/hostedzone/$id/rrset"
     ;;
+  addalias)
+    if ([ -z "$hostedzoneid" ] || [ -z "$dnsname" ]) ; then
+      if [ -n "`which elb-describe-lbs`" ] ; then
+        elbzone=`elb-describe-lbs | awk '{print $4" "$5}' | grep $hostedzoneid | grep $dnsname`
+        if [ -n "$elbzone" ] ; then
+          if [ `echo $elbzone | wc -l` -eq 1 ] ; then
+            dnsname=`echo $elbzone | awk '{print $1}'`
+            hostedzoneid=`echo $elbzone | awk '{print $2}'`
+          else
+            echo "Something is wrong: multiple records match:"
+            echo $elbzone
+            exit 1
+          fi
+        else
+          echo "No match found in elb-describe-lbs output, run it manually and define both --dnsname and --hostedzoneid"
+          exit 1
+        fi
+      else
+        echo "No elb-describe-lbs command found, install it or check the PATH variable or define both --dnsname and --hostedzoneid"
+        exit 1
+      fi
+    fi
+    if [ -z "$id" ] ; then
+      if [ -z "$zone" ] ; then
+        echo "Either zone ID or zone name should be defined" && exit 1
+      else
+        zone="${zone%.}."
+        id=`grep "|${zone}$" "${rpath}/../../$CLOUD.dnszones.list" | tail -1| cut -d'|' -f1`
+        if [ -z "$id" ] ; then
+          echo "Unable to find zone ID of this zone. Zones list is outdated? Run ${0##*/} --list to update it." && exit 1
+        fi
+      fi
+    fi
+    postrequest=1
+    echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?><ChangeResourceRecordSetsRequest xmlns=\"https://route53.amazonaws.com/doc/2011-05-05/\"><ChangeBatch><Comment></Comment><Changes><Change><Action>CREATE</Action><ResourceRecordSet><Name>${name}.</Name><Type>A</Type><AliasTarget><HostedZoneId>$hostedzoneid</HostedZoneId><DNSName>${dnsname%.}.</DNSName></AliasTarget></ResourceRecordSet></Change></Changes></ChangeBatch></ChangeResourceRecordSetsRequest>" > $request
+    requrl="https://route53.amazonaws.com/2011-05-05/hostedzone/$id/rrset"
+    ;;
   delrecord|deleterecord)
     [ -z "$type" ] && echo "type not defined" && exit 1
     [ -z "$value" ] && echo "value not defined" && exit 1
@@ -219,7 +257,7 @@ case $action in
   createzone|create)
     [ -z "$zone" ] && echo "zone not defined" && exit 1
     postrequest=1
-    echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?><CreateHostedZoneRequest xmlns=\"https://route53.amazonaws.com/doc/2011-05-05/\"><Name>${zone}.</Name>   <CallerReference>createzone_$zone_`date +"%s"`</CallerReference><HostedZoneConfig><Comment>$comment</Comment></HostedZoneConfig></CreateHostedZoneRequest>" > $request
+    echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?><CreateHostedZoneRequest xmlns=\"https://route53.amazonaws.com/doc/2011-05-05/\"><Name>${zone}.</Name><CallerReference>createzone_${zone}_`date +"%s"`</CallerReference><HostedZoneConfig><Comment>$comment</Comment></HostedZoneConfig></CreateHostedZoneRequest>" > $request
     requrl="https://route53.amazonaws.com/2011-05-05/hostedzone"
     ;;
   deletezone|delete)
