Bugfixes

diff --git a/cloud/ec2/route53query b/cloud/ec2/route53query
--- a/cloud/ec2/route53query
+++ b/cloud/ec2/route53query
@@ -27,7 +27,7 @@ TMPDIR=/tmp/m_script/cloud/ec2
 install -d $TMPDIR
 CURL="$CURL -s"
 
-possible_options="region action id name listzone types"
+possible_options="region action id zone name type items wholezone noupdate"
 necessary_options="action"
 [ "X$*" == "X" ] && echo "Can't run without options. Possible options are: ${possible_options}" && exit 1
 for s_option in "${@}"
@@ -72,11 +72,12 @@ if [[ found -eq 1 ]]; then
   exit 1
 fi
 
-[ -n "$listzone" ] && [ -z "$types" ] && types="A,AAAA,CNAME,MX,NS,PTR,SOA,SPF,SRV,TXT"
-
+[ "X$action" == "Xlistzone" ] && [ -z "$type" ] && type="SOA"
+[ "X$action" == "Xlistzone" ] && [ -z "$name" ] && name=$zone
+[ "X$action" == "Xlistzone" ] && [ -z "$items" ] && items=1
 source ${rpath}/../../conf/cloud.conf
 
-request=/tmp/m_script/cloud/r53query.$$
+request=$TMPDIR/r53query.$$
 
 server_date=`curl -q -s -S -I --max-time 5 --url https://route53.amazonaws.com/date | grep ^Date | awk -F'Date: ' '{print $2}' | sed 's|\r||'`
 
@@ -84,55 +85,75 @@ signature=`printf "$server_date" | $SSLEX dgst -binary -sha1 -hmac $AWS_SECRET_A
 
 case $action in 
   list)
-    $CURL -H "Content-Type: text/xml; charset=UTF-8" -H "Date: $server_date" -H "X-Amzn-Authorization: AWS3-HTTPS AWSAccessKeyId=$AWS_ACCESS_KEY_ID,Algorithm=HmacSHA1,Signature=$signature" https://route53.amazonaws.com/2011-05-05/hostedzone > $request
-    ${rpath}/../../lib/xml2txt $request > ${request}.txt
-    grep ^ListHostedZonesResponse_HostedZones_HostedZone_Id ${request}.txt | cut -d' ' -f2 | sed 's|/hostedzone/||' > ${request}.ids
+    $CURL -H "Content-Type: text/xml; charset=UTF-8" -H "Date: $server_date" -H "X-Amzn-Authorization: AWS3-HTTPS AWSAccessKeyId=$AWS_ACCESS_KEY_ID,Algorithm=HmacSHA1,Signature=$signature" https://route53.amazonaws.com/2011-05-05/hostedzone > $TMPDIR/r53.list.xml
+    ${rpath}/../../lib/xml2txt $TMPDIR/r53.list.xml > $TMPDIR/r53.list.txt
+    grep ^ListHostedZonesResponse_HostedZones_HostedZone_Id $TMPDIR/r53.list.txt | cut -d' ' -f2 | sed 's|/hostedzone/||' > $TMPDIR/r53.list.ids
     while read zoneid ; do
-    zonename=`grep -A 1 "${zoneid}$" ${request}.txt | tail -1 | cut -d' ' -f2`
-    [[ `grep -c ^$zoneid|$zonename$ ${rpath}/../../$CLOUD.dnszones.list 2>/dev/null` -eq 0 ]] && echo "$zoneid|$zonename" && echo "$zoneid|$zonename" >> "${rpath}/../../$CLOUD.dnszones.list"
-    done < ${request}.ids
+    zonename=`grep -A 1 "${zoneid}$" $TMPDIR/r53.list.txt | tail -1 | cut -d' ' -f2`
+    [ -x "$noupdate" ] && [[ `grep -c ^$zoneid|$zonename$ ${rpath}/../../$CLOUD.dnszones.list 2>/dev/null` -eq 0 ]] && echo "$zoneid|$zonename" && echo "$zoneid|$zonename" >> "${rpath}/../../$CLOUD.dnszones.list"
+    done < $TMPDIR/r53.list.ids
     ;;
   show)
     if [ -z "$id" ] ; then
-      if [ -z "$name" ] ; then
+      if [ -z "$zone" ] ; then
         echo "Either zone ID or zone name should be defined" && exit 1
       else
-        name="${name%.}."
-        id=`grep "|${name}$" "${rpath}/../../$CLOUD.dnszones.list" | tail -1| cut -d'|' -f1`
+        zone="${zone%.}."
+        id=`grep "|${zone}$" "${rpath}/../../$CLOUD.dnszones.list" | tail -1| cut -d'|' -f1`
         if [ -z "$id" ] ; then
-          echo "Unable to find zone ID by this name. Zones list is outdated? Run ${0##*/} --list to update it." && exit 1
+          echo "Unable to find zone ID of this zone. Zones list is outdated? Run ${0##*/} --list to update it." && exit 1
         fi
       fi
     fi
-    $CURL -H "Content-Type: text/xml; charset=UTF-8" -H "Date: $server_date" -H "X-Amzn-Authorization: AWS3-HTTPS AWSAccessKeyId=$AWS_ACCESS_KEY_ID,Algorithm=HmacSHA1,Signature=$signature" https://route53.amazonaws.com/2011-05-05/hostedzone/$id > $request
-    printf "Zone name: ${name}\tZone id: ${id}\n"
-    echo "--------------------------------------------------"
-    ${rpath}/../../lib/xml2txt $request | grep ^GetHostedZoneResponse_HostedZone_DelegationSet_NameServers_NameServer | cut -d' ' -f2
+    if [ -z "$noupdate" ] || [ ! -f $TMPDIR/r53.${id}.show ] ; then
+      $CURL -H "Content-Type: text/xml; charset=UTF-8" -H "Date: $server_date" -H "X-Amzn-Authorization: AWS3-HTTPS AWSAccessKeyId=$AWS_ACCESS_KEY_ID,Algorithm=HmacSHA1,Signature=$signature" https://route53.amazonaws.com/2011-05-05/hostedzone/$id > $TMPDIR/r53.${id}.show
+    fi
+    echo "------------------------------------------------------------------------------"
+    printf "Zone name: ${zone}\tZone id: ${id}\n"
+    echo "------------------------------------------------------------------------------"
+    ${rpath}/../../lib/xml2txt $TMPDIR/r53.${id}.show | grep ^GetHostedZoneResponse_HostedZone_DelegationSet_NameServers_NameServer | cut -d' ' -f2
     ;;
   listzone)
     if [ -z "$id" ] ; then
-      if [ -z "$name" ] ; then
+      if [ -z "$zone" ] ; then
         echo "Either zone ID or zone name should be defined" && exit 1
       else
-        name="${name%.}."
-        id=`grep "|${name}$" "${rpath}/../../$CLOUD.dnszones.list" | tail -1| cut -d'|' -f1`
+        zone="${zone%.}."
+        id=`grep "|${zone}$" "${rpath}/../../$CLOUD.dnszones.list" | tail -1| cut -d'|' -f1`
         if [ -z "$id" ] ; then
-          echo "Unable to find zone ID by this name. Zones list is outdated? Run ${0##*/} --list to update it." && exit 1
+          echo "Unable to find zone ID of this zone. Zones list is outdated? Run ${0##*/} --list to update it." && exit 1
         fi
       fi
     fi
-    printf "Zone name: ${name}\tZone id: ${id}\n" > $TMPDIR/r53.${name}.records
-    echo "--------------------------------------------------" >> $TMPDIR/r53.${name}.records
-    for type in `echo $types | sed 's|,| |g'` ; do
-      $CURL -H "Content-Type: text/xml; charset=UTF-8" -H "Date: $server_date" -H "X-Amzn-Authorization: AWS3-HTTPS AWSAccessKeyId=$AWS_ACCESS_KEY_ID,Algorithm=HmacSHA1,Signature=$signature" "https://route53.amazonaws.com/2011-05-05/hostedzone/$id/rrset?name=${name%.}&type=${type}" > $request
+    if [ -n "$wholezone" ] ; then
+      request=$TMPDIR/r53.${id}.listzone.wholezone
+    else
+      request=$TMPDIR/r53.${id}.listzone.${name}.${type}.${items}
+    fi
+    echo "------------------------------------------------------------------------------"
+    printf "Zone name: ${zone}\tZone id: ${id}\n"
+    echo "------------------------------------------------------------------------------"
+#    for type in `echo $types | sed 's|,| |g'` ; do
+    if [ -z "$noupdate" ] || [ ! -f $request ] ; then
+      if [ -z "$wholezone" ] ; then
+        $CURL -H "Content-Type: text/xml; charset=UTF-8" -H "Date: $server_date" -H "X-Amzn-Authorization: AWS3-HTTPS AWSAccessKeyId=$AWS_ACCESS_KEY_ID,Algorithm=HmacSHA1,Signature=$signature" "https://route53.amazonaws.com/2011-05-05/hostedzone/$id/rrset?name=${name%.}&type=${type}&maxitems=${items}" > $request
+      else
+        $CURL -H "Content-Type: text/xml; charset=UTF-8" -H "Date: $server_date" -H "X-Amzn-Authorization: AWS3-HTTPS AWSAccessKeyId=$AWS_ACCESS_KEY_ID,Algorithm=HmacSHA1,Signature=$signature" "https://route53.amazonaws.com/2011-05-05/hostedzone/$id/rrset?name=${name%.}" > $request
+      fi
+    fi
+    if [ -z "$noupdate" ] || [ ! -f ${request}.txt ] ; then
       ${rpath}/../../lib/xml2txt $request > ${request}.txt
-      grep ^ListResourceRecordSetsResponse_ResourceRecordSets_ResourceRecordSet_Name ${request}.txt | cut -d' ' -f2 > ${request}.names
-      while read recname ; do
-        while read txtline ; do
+    fi
+    grep ^ListResourceRecordSetsResponse_ResourceRecordSets_ResourceRecordSet_Name ${request}.txt | cut -d' ' -f2 | sort -n | uniq > ${request}.names
+    while read recname ; do
+      unset thiszone
+      ns=`grep -n "ListResourceRecordSetsResponse_ResourceRecordSets_ResourceRecordSet_Name $recname" ${request}.txt | cut -d':' -f1`
+      for n in `echo $ns` ; do
+        cat ${request}.txt | tail -n +${n} | while read txtline ; do
           var=`echo $txtline | cut -d' ' -f1`
           value=`echo $txtline | cut -d' ' -f2`
           [ "X$var" == "XListResourceRecordSetsResponse_ResourceRecordSets_ResourceRecordSet_Name" ] && [ "X$value" == "X$recname" ] && thiszone=1
-          [ "X$var" == "XListResourceRecordSetsResponse_ResourceRecordSets_ResourceRecordSet_Name" ] && [ "X$value" != "X$recname" ] &&  unset thiszone
+          [ "X$var" == "XListResourceRecordSetsResponse_ResourceRecordSets_ResourceRecordSet_Name" ] && [ "X$value" != "X$recname" ] && unset thiszone && break
           if [ -n "$thiszone" ] ; then
             case ${var##*_} in 
             Type)
@@ -146,10 +167,12 @@ case $action in
             ;;
             esac
           fi
-          [ -n "$value" ] && printf "$recname\t$rectype\t$recttl\t$recvalue\n" && unset recvalue
-        done < ${request}.txt
-      done < ${request}.names
-    done
+          [ -n "$recvalue" ] && printf "$recname\t$rectype\t$recttl\t$recvalue\n" && unset recvalue
+        done
+      done
+    done < ${request}.names
+# done
+    ;;
   *)
     postrequest=1
   esac
@@ -158,5 +181,6 @@ case $action in
     $CURL -X POST --upload-file $request -H "Content-Type: text/xml; charset=UTF-8" -H "Date: $server_date" -H "X-Amzn-Authorization: AWS3-HTTPS AWSAccessKeyId=$AWS_ACCESS_KEY_ID,Algorithm=HmacSHA1,Signature=$signature" https://route53.amazonaws.com/2011-05-05/hostedzone
     unset postrequest
   fi
-  rm -f ${request}*
+#  rm -f ${request}*
+for option in `echo $possible_options | sed 's/,//g'`; do unset $option ; done
 
