xml2txt finished, bugfixes and enhancements

diff --git a/cloud/ec2/route53query b/cloud/ec2/route53query
--- a/cloud/ec2/route53query
+++ b/cloud/ec2/route53query
@@ -24,7 +24,7 @@ LINKS=`which links 2>/dev/null`
 WGET=`which wget 2>/dev/null`
 SSLEX=`which openssl 2>/dev/null`
 
-possible_options="region action"
+possible_options="region action id name"
 necessary_options="action"
 [ "X$*" == "X" ] && echo "Can't run without options. Possible options are: ${possible_options}" && exit 1
 for s_option in "${@}"
@@ -76,10 +76,36 @@ request=/tmp/m_script/cloud/r53query.$$
 server_date=`curl -q -s -S -I --max-time 5 --url https://route53.amazonaws.com/date | grep ^Date | awk -F'Date: ' '{print $2}' | sed 's|\r||'`
 
 signature=`printf "$server_date" | $SSLEX dgst -sha1 -hmac $AWS_SECRET_ACCESS_KEY -r | awk '{print $1}' | base64`
-if [ "$action" == "list" ] ; then
-  $CURL -H "Content-Type: text/xml; charset=UTF-8" -H "Date: $server_date" -H "X-Amzn-Authorization: AWS3-HTTPS AWSAccessKeyId=$AWS_ACCESS_KEY_ID,Algorithm=HmacSHA1,Signature=$signature" https://route53.amazonaws.com/2011-05-05/hostedzone
-else
-  $CURL -X POST --upload-file $request -H "Content-Type: text/xml; charset=UTF-8" -H "Date: $server_date" -H "X-Amzn-Authorization: AWS3-HTTPS AWSAccessKeyId=$AWS_ACCESS_KEY_ID,Algorithm=HmacSHA1,Signature=$signature" https://route53.amazonaws.com/2011-05-05/hostedzone
-fi
+case $action in 
+  list)
+    $CURL -H "Content-Type: text/xml; charset=UTF-8" -H "Date: $server_date" -H "X-Amzn-Authorization: AWS3-HTTPS AWSAccessKeyId=$AWS_ACCESS_KEY_ID,Algorithm=HmacSHA1,Signature=$signature" https://route53.amazonaws.com/2011-05-05/hostedzone > $request
+    ${rpath}/lib/xml2txt $request | grep ^ListHostedZonesResponse_HostedZones_HostedZone_Id | cut -d' ' -f2 | sed 's|/hostedzone/||' > ${request}.ids
+    while read zoneid ; do
+    zonename=`grep -A 1 "${zoneid}$" $request | tail -1 | cut -d' ' -f2`
+    [[ `grep -c ^$zoneid|$zonename$ ${rpath}/$CLOUD.dnszones.list` -eq 0 ]] && echo "$zoneid|$zonename" >> "${rpath}/$CLOUD.dnszones.list"
+    done < ${request}.ids
+  ;;
+  show)
+    if [ -z "$id" ] ; then
+      if [ -z "$name" ] ; then
+        echo "Either zone ID or zone name should be defined" && exit 1
+      else
+        id=`grep "|${name}$" "${rpath}/$CLOUD.dnszones.list" | tail -1| cut -d' ' -f1`
+        if [ -z "$id" ] ; then
+          echo "Unable to find zone ID by this name. Zones list is outdated? Run ${0##*/} --list to update it." && exit 1
+        fi
+      fi
+    fi
+    $CURL -H "Content-Type: text/xml; charset=UTF-8" -H "Date: $server_date" -H "X-Amzn-Authorization: AWS3-HTTPS AWSAccessKeyId=$AWS_ACCESS_KEY_ID,Algorithm=HmacSHA1,Signature=$signature" https://route53.amazonaws.com/2011-05-05/hostedzone/$id > $request
+    ${rpath}/lib/xml2txt $request
+  ;;
+  *)
+    postrequest=1
+  esac
+  
+  if [ -n "$postrequest" ] ; then
+    $CURL -X POST --upload-file $request -H "Content-Type: text/xml; charset=UTF-8" -H "Date: $server_date" -H "X-Amzn-Authorization: AWS3-HTTPS AWSAccessKeyId=$AWS_ACCESS_KEY_ID,Algorithm=HmacSHA1,Signature=$signature" https://route53.amazonaws.com/2011-05-05/hostedzone
+    unset postrequest
+  fi
 
 
