node save

diff --git a/cloud/ec2/save_node b/cloud/ec2/save_node
--- a/cloud/ec2/save_node
+++ b/cloud/ec2/save_node
@@ -1,5 +1,4 @@
 #!/bin/bash
-
 # Copyright (C) 2008-2011 Igor Simonov (me@igorsimonov.com)
 #
 # This program is free software: you can redistribute it and/or modify
@@ -15,94 +14,94 @@
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
-
 rcommand=${0##*/}
 rpath=${0%/*}
-#*/ (this is needed to fix vi syntax highlighting)
+[ -z "$M_ROOT" ] && M_ROOT=$(readlink -f "$rpath/../../")
+#*/
 
-possible_options="cloud name aki region"
-necessary_options="name"
-[ "X$*" == "X" ] && echo "Can't run without options. Possible options are: ${possible_options}" && exit 1
-for s_option in "${@}"
+CURL=`which curl 2>/dev/null`
+[ -z "$CURL" ] && echo "Curl not found" && exit 1
+SSLEX=`which openssl 2>/dev/null`
+[ -z "$SSLEX" ] && echo "openssl binary not found" && exit 1
+
+possible_options="name log_request cloud action instanceid description noreboot"
+necessary_options="name instanceid"
+IFS1=$IFS
+IFS='-'
+for s_option in "$@"
 do
-  found=0
-  case ${s_option} in
-  --*=*)
-    s_optname=`expr "X$s_option" : 'X[^-]*-*\([^=]*\)'`  
-    s_optarg=`expr "X$s_option" : 'X[^=]*=\(.*\)'` 
-    ;;
-  --*)
-    s_optname=`expr "X$s_option" : 'X[^-]*-*\([^=]*\)'`    
-    s_optarg='yes' 
-    ;;
-  *=*)
-    echo "Wrong syntax: options must start with a double dash"
-    exit 1
-    ;;
-  *)
-    s_param=${s_option}
-    s_optname=''
-    s_optarg=''
-    ;;
-  esac
-  for option in `echo $possible_options | sed 's/,//g'`; do 
-    [ "X$s_optname" == "X$option" ] && eval "$option=${s_optarg}" && found=1
+  found=false
+  s_option=${s_option/--/}
+  s_optname=${s_option%%=*}
+  s_optarg=${s_option##*=}
+  [ "_$s_optarg" == "_$s_optname" ] && s_optarg="yes"
+
+  for option in ${possible_options// /-} ; do
+    [ "_$s_optname" == "_$option" ] && eval "$s_optname=\"$s_optarg\"" && found=true && break
   done
-  [ "X$s_option" == "X$s_param" ] && found=1
-  if [[ $found -ne 1 ]]; then 
+  
+  if ! $found ; then 
     echo "Unknown option: $s_optname"
     exit 1
   fi
 done
-found=0
+IFS=$IFS1
 
+found=0
 for option in `echo $necessary_options | sed 's/,//g'`; do
-  [ "X$(eval echo \$$option)" == "X" ] && missing_options="${missing_options}, --${option}" && found=1
+  [ -z "$(eval echo \$$option)" ] && missing_options="${missing_options}, --${option}" && found=1
 done
 if [[ found -eq 1 ]]; then
   missing_options=${missing_options#*,}
-  echo "Necessary options: ${missing_options} not found"
+  echo "Necessary options: $missing_options not found"
   exit 1
 fi
 
-source ${rpath}/../../conf/clouds/${CLOUD}.conf
-for var in BUCKETNAME EXCLUDE_PATHS SAVED_FILES_PATH AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY EC2_TOOLS_BIN_PATH JAVA_HOME EC2_HOME EC2_PRIVATE_KEY EC2_CERT EC2_REGION ; do
-  [ -z "`eval echo \\$\$var`" ] && echo "$var is not defined! Define it in conf/clouds/${CLOUD}.conf please." && exit 1
-done
-PATH="${EC2_TOOLS_BIN_PATH}:${EC2_AMI_TOOLS_BIN_PATH}:${PATH}"
-export JAVA_HOME EC2_HOME EC2_PRIVATE_KEY EC2_CERT AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY EC2_REGION PATH
-[ -n "$region" ] && EC2_REGION=$region
-M_TEMP=/tmp/m_script/cloud/ec2
-if [[ $BUCKETNAME =~ ^s3 ]] ; then
-  FULLBUCKETNAME="$BUCKETNAME"
-  BUCKETNAME="${BUCKETNAME#*://}"
-else
-  FULLBUCKETNAME="s3://$BUCKETNAME"
-fi
-install -d $M_TEMP
-install -d $SAVED_FILES_PATH
-EXCLUDE_PATHS=`echo $EXCLUDE_PATHS | sed 's|,| |g'`
-for E in $EXCLUDE_PATHS
-do
-  [ -e $E ] || ex=0
-done
-[ "X$ex" != "X0" ] && EXCLUDE="-e ${EXCLUDE_PATHS}/" || EXCLUDE=""
-[ "X$name" == "X" ] && echo "Name needed" && exit 1
-[ "X`which ec2-bundle-vol`" == "X" ] && echo "AMI Tools needed" && exit 1
-[ "X`which ec2-register`" == "X" ] && echo "API Tools needed" && exit 1
+[ -n "$cloud" ] && CLOUD=$cloud
+[ -z "$CLOUD" ] && echo "No cloud defined" && exit 1
 
-S3CMD=`which s3cmd 2>/dev/null`
-if [ -n "$S3CMD" ] ; then
-  echo "Removing AMI with the same name, if any"
-  $S3CMD del "${FULLBUCKETNAME}/${name}"*
-else
-  echo "Warning: S3cmd not found, so S3 bucket ${BUCKETNAME} has not been searched for previously saved AMI with the same name. No worries, this search is just a precaution."
-fi
-[ -n "$aki" ] && aki="--kernel $aki"
-rm -rf ${SAVED_FILES_PATH%/}/image* ${SAVED_FILES_PATH%/}/img-mnt* ${SAVED_FILES_PATH%/}/${name} ${SAVED_FILES_PATH%/}/${name}.manifest.xml ${SAVED_FILES_PATH%/}/${name}.part.* 2>/dev/null
-ec2-bundle-vol -r $ARCH --prefix "${name}" -d ${SAVED_FILES_PATH} --user $EC2_USERID $EXCLUDE -k $EC2_PRIVATE_KEY -c $EC2_CERT "$aki"
-ec2-upload-bundle -b "${BUCKETNAME}" -m "${SAVED_FILES_PATH%/}/${name}".manifest.xml -a $AWS_ACCESS_KEY_ID -s $AWS_SECRET_ACCESS_KEY --location $EC2_REGION
-amiID=`ec2-describe-images -K "$EC2_PRIVATE_KEY" -C "$EC2_CERT" --region $EC2_REGION | grep ^IMAGE | awk '{print $2" "$3}' | grep "${name}" | head -1 | awk '{print $1}'`
-[ -n "$amiID" ] && echo "The name ${name} is registered. De-registering first" && echo "Deregistered: `ec2-deregister -K $EC2_PRIVATE_KEY -C $EC2_CERT --region $EC2_REGION $amiID | cut -d' ' -f2`" 
-echo "Registered: `ec2-register -K $EC2_PRIVATE_KEY -C $EC2_CERT --region $EC2_REGION ${BUCKETNAME}/${name}.manifest.xml -n ${name} | cut -d' ' -f2`"
+source "$M_ROOT/conf/mon.conf"
+source "$M_ROOT/conf/clouds/${CLOUD}.conf"
+source "$M_ROOT/lib/cloud_functions.sh"
+LOG="$M_ROOT/logs/cloud.log"
+
+M_TEMP="$M_TEMP/cloud/$CLOUD"
+[ -d "$M_TEMP" ] || install -d "$M_TEMP"
+
+CURL="$CURL -s -k"
+
+# TODO: add this to cloud config
+SignatureMethod=HmacSHA256
+SignatureVersion=2
+Version="2013-07-15"
+
+qparams="${qparams}\nSignatureMethod=${SignatureMethod}\nSignatureVersion=${SignatureVersion}\nVersion=${Version}\nInstanceId=${instanceid}\nName=${name}"
+[ -n "$noreboot" ] && qparams="${qparams}\nNoReboot=true"
+[ -n "$description" ] && qparams="${qparams}\nDescription=${description}"
+
+request() {
+  timestamp=`date +"%Y-%m-%dT%H%%3A%M%%3A%S"`
+  qparams="${qparams}\nTimestamp=${timestamp}"
+  qparams=`echo -e -n "$qparams" | sort | grep -v ^$ | tr '\n' '&'`
+  query=`echo -n "AWSAccessKeyId=${AWS_ACCESS_KEY_ID}&Action=${1}&${qparams%&}"`
+  Q=`echo -ne "GET\nec2.amazonaws.com\n/\n$query"`
+  signature=`echo -n "$Q"| $SSLEX dgst -binary -sha256 -hmac "$AWS_SECRET_ACCESS_KEY" | base64 | "$M_ROOT"/lib/urlencode`
+  if [ "_$log_request" == "_yes" ]; then
+    log "$CURL \"https://ec2.amazonaws.com/?AWSAccessKeyId=${AWS_ACCESS_KEY_ID}&Action=${1}&${qparams}Signature=$signature\""
+    reqres=`$CURL "https://ec2.amazonaws.com/?AWSAccessKeyId=${AWS_ACCESS_KEY_ID}&Action=${1}&${qparams}Signature=$signature"`
+    log "$reqres"
+    echo "$reqres" | "$M_ROOT"/lib/xml2txt | grep -v ^$ > "$M_TEMP/${rcommand}.resp"
+  else
+    $CURL "https://ec2.amazonaws.com/?AWSAccessKeyId=${AWS_ACCESS_KEY_ID}&Action=${1}&${qparams}Signature=$signature" | "$M_ROOT"/lib/xml2txt | grep -v ^$ > "$M_TEMP/${rcommand}.resp"
+  fi
+}
+
+request CreateImage
+reqparsed=`cat "$M_TEMP/${rcommand}.resp"`
+[ `echo "$reqparsed" | wc -l` -eq 0 ] && log "file $M_TEMP/${rcommand}.resp is empty" && proper_exit 1 90
+[ `echo "$reqparsed" | grep -c Error` -ne 0 ] && log "request failed with error `echo "$reqparsed" | grep Error | cut -d'|' -f2`" && proper_exit 1 91
+
+echo "$reqparsed"
+
+
 
