bits

diff --git a/cloud/ec2/show_servers b/cloud/ec2/show_servers
--- a/cloud/ec2/show_servers
+++ b/cloud/ec2/show_servers
@@ -32,6 +32,17 @@ IFCFG=`which ifconfig 2>/dev/null`
 # have different OSes there with different paths to hostname utility.
 HOSTNAME=`which hostname 2>/dev/null`
 
+get_hostname() {
+  if [ `echo $localip | grep -c "^$1$"` -ne 0 ] ; then
+    sname=`$HOSTNAME`
+  else
+    sname=`$SSH -i "${rpath}/../../keys/${key}" -o StrictHostKeyChecking=no -o ConnectionAttempts=1 -o ConnectTimeout=10 $1 hostname 2>/dev/null`
+  fi
+  [ `expr "$sname" : .*[\"\t\s_,.\']` -ne 0 ] && unset sname
+  [ "X$sname" == "X" ] && log "Unable to retrieve hostname of the server with IP $inIP|$extIP$message" && unset message && return 1
+  return 0
+}
+
 add_server() {
   if [ "X$NETWORK" == "Xexternal" ] ; then
     IP=$extIP
@@ -47,19 +58,18 @@ add_server() {
       message=" (key ${rpath}/../../keys/${keypair}{.pem} not found)"
     fi
   fi
-  # altname was supposed to be an alternative source (from instance tags), but
-  # it is reconsidered due to no good way to inject the name into the new server
-  if [ -n "$altname" ]; then
-    sname=$altname
-  elif [ -n "$IP" ] ; then
-    log "Name not found, retrieving one from the host"
-    if [ `echo $localip | grep -c "^$IP$"` -ne 0 ] ; then
-      sname=`$HOSTNAME`
-    else
-      sname=`$SSH -i "${rpath}/../../keys/${key}" -o StrictHostKeyChecking=no -o ConnectionAttempts=1 -o ConnectTimeout=10 $inIP hostname 2>/dev/null` || sname=`$SSH -i "${rpath}/../../keys/${key}" -o StrictHostKeyChecking=no -o ConnectionAttempts=1 -o ConnectTimeout=10 $extIP hostname 2>/dev/null`
+  if [ "X$NAME_SOURCE" == "Xtag" ] ; then
+    if [ -n "$altname" ]; then
+      sname=$altname
+    elif [ -n "$IP" ] ; then
+      log "Name not found, retrieving one from the host"
+      get_hostname $IP || sname=unknown
     fi
-    [ `expr "$sname" : .*[\"\t\s_,.\']` -ne 0 ] && unset sname
-    [ "X$sname" == "X" ] && log "Unable to retrieve hostname of the server with IP $inIP|$extIP$message" && unset message
+  else
+    get_hostname $IP
+    if [ $? -ne 0 ]; then
+      [ -n "$altname" ] && sname=$altname || sname=unknown
+    fi
   fi
   echo "$inIP|$extIP|$iID|$ami|$state|$keypair|$isize|$secgroup|$started|$zone|$aki|$ari|$sname|$cluster" >> "$M_TEMP/servers.${region}.ips"
   if [ -n "${bID[*]}" ]; then
