ec2 and linode show_nodes enhanced

diff --git a/cloud/ec2/show_nodes b/cloud/ec2/show_nodes
--- a/cloud/ec2/show_nodes
+++ b/cloud/ec2/show_nodes
@@ -14,163 +14,18 @@
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
-
 rcommand=${0##*/}
 rpath=${0%/*}
 [ -z "$M_ROOT" ] && M_ROOT=$(readlink -f "$rpath/../../")
 #*/
-DIFF=`which diff 2>/dev/null`
-[ -z "$DIFF" ] && echo "Diff utility not found, exiting..  " && exit 1
-SED=`which sed 2>/dev/null`
-[ -z "$SED" ] && echo "Sed utility not found, exiting..  " && exit 1
-SSH=`which ssh 2>/dev/null`
-SSLEX=`which openssl 2>/dev/null`
+
 CURL=`which curl 2>/dev/null`
-CURL="$CURL -s"
-[ -z "$SSH" ] && echo "Ssh utility not found, exiting..  " && exit 1
-IFCFG=`which ifconfig 2>/dev/null`
-# Normally needed for localhost only, and not always: depends on system.
-# Hostnames of remote nodes are obtained via ssh which is a login shell;
-# this is why the variable below is not used for remote nodes: you may
-# have different OSes there with different paths to hostname utility.
-HOSTNAME=`which hostname 2>/dev/null`
+[ -z "$CURL" ] && echo "Curl not found" && exit 1
+
 [ -z "$CLUSTER_TAG" ] && CLUSTER_TAG="cluster"
 LOG="$M_ROOT/logs/cloud.log"
 
-request() {
-  timestamp=`date +"%Y-%m-%dT%H%%3A%M%%3A%S"`
-  query=`echo -n "AWSAccessKeyId=${AWS_ACCESS_KEY_ID}&Action=DescribeInstances&SignatureMethod=HmacSHA256&SignatureVersion=2&Timestamp=${timestamp}&Version=2013-07-15"`
-  Q=`echo -ne "GET\nec2.amazonaws.com\n/\n$query"`
-  signature=`echo -n "$Q"| $SSLEX dgst -binary -sha256 -hmac "$AWS_SECRET_ACCESS_KEY" | base64 | "$M_ROOT"/lib/urlencode`
-  $CURL "https://ec2.amazonaws.com/?AWSAccessKeyId=${AWS_ACCESS_KEY_ID}&Action=DescribeInstances&SignatureMethod=HmacSHA256&SignatureVersion=2&Timestamp=${timestamp}&Version=2013-07-15&Signature=$signature" | "$M_ROOT"/lib/xml2txt | awk -F'"reservationSet"/' '{print $2}' | grep -v ^$ > "$M_TEMP/${rcommand}.resp"
-}
-
-get_iname() {
-  for ns in $NAME_SOURCE $NAME_SOURCE_FALLBACK ; do
-    case $ns in
-      host)
-        get_hostname $1
-        ;;
-      metadata)
-        sname=`echo "$node" | grep '/"privateDnsName"/0' | cut -d'|' -f2 | tr -d '"'`
-        ;;
-      dnsName)
-        sname=`echo "$node" | grep '/"dnsName"/0' | cut -d'|' -f2 | tr -d '"'`
-        ;;
-      *)
-        # anything else is considered to be a tag as the source
-        NAMETAG="${ns#*:}"
-        nametagind=`echo "$tags" | grep '/"key"/' | grep \|\"$NAMETAG\" | cut -d'/' -f7`
-        sname=`echo "$tags" | grep "$nametagind/\"value\"/" | cut -d'|' -f2 | head -1 | tr -d '"'`
-        ;;
-    esac
-    [ -n "$sname" ] && break
-  done
-  echo "$sname"
-}
-
-list_nodes() {
-  $debug && [ -n "$update_nodes_list" ] && echo -e "\n`date`\n=====================\n" >> $LOG
-  IFS1=$IFS
-  IFS='
-'
-
-  if [ `cat "$M_TEMP/${rcommand}.resp" 2>/dev/null | wc -l` -gt 0 ]; then
-    [ "_$view" == "_raw" ] && cat "$M_TEMP/${rcommand}.resp" && return
-    declare -a nodelist
-    
-#==============================================================================
-    for sn in `cat "$M_TEMP/${rcommand}.resp" | grep instancesSet | cut -d'/' -f1,2,3,4,5,6,7 | sort | uniq` ; do
-      unset id name istatus extIP intIP IP imageId flavorId icluster
-
-      node=`grep ^$sn\/ "$M_TEMP/${rcommand}.resp"`
-      
-      intIP=`echo "$node" | grep '/"privateIpAddress"/0' | cut -d'|' -f2 | tr -d '"'`
-      extIP=`echo "$node" | grep '/"ipAddress"/0' | cut -d'|' -f2 | tr -d '"'`
-      id=`echo "$node" | grep '/"instanceId"/0' | cut -d'|' -f2 | tr -d '"'`
-      imageId=`echo "$node" | grep '/"imageId"/0' | cut -d'|' -f2 | tr -d '"'`
-      istatus=`echo "$node" | grep '/"instanceState"/0/"name"/0' | cut -d'|' -f2 | tr -d '"'`
-      flavorId=`echo "$node" | grep '/"instanceType"/0' | cut -d'|' -f2 | tr -d '"'`
-      secgroup=`echo "$node" | grep '/"groupSet"/0/"item"/0/"groupName"' | cut -d'|' -f2 | sort | uniq | tr -d '"' | tr '\n' ','`
-      izone=`echo "$node" | grep '/"placement"/0/"availabilityZone"/0' | cut -d'|' -f2 | tr -d '"'`
-      iaki=`echo "$node" | grep '/"kernelId"/0' | cut -d'|' -f2 | tr -d '"'`
-      #iari=`echo "$sn" | grep '/"ipAddress"/0' | cut -d'|' -f2 | tr -d '"'`
-      if [ "_$NETWORK" == "_external" ] ; then
-        IP=$extIP
-      else
-        IP=$intIP
-      fi
-      iname=`get_iname $IP`
-      
-      tags=`echo "$node" | grep '/"tagSet"/'`
-      iclustertag=`echo "$tags" | grep '/"key"/' | grep \|\"$CLUSTER_TAG\" | cut -d'/' -f11`
-      if [ -n "$iclustertag" ]; then
-        icluster=`echo "$tags" | grep "$iclustertag/\"value\"/" | cut -d'|' -f2 | head -1 | tr -d '"'`
-      else
-        [ -z "$all" ] && continue
-      fi
-      
-      ikey=`echo "$node" | grep '/"keyName"/0' | cut -d'|' -f2 | tr -d '"'`
-      
-      bdevs=`echo "$node" | grep '/"blockDeviceMapping"/'`
-      unset ebs
-      for bdev in `echo "$bdevs" | grep '|"attached"' | cut -d'/' -f11 | sort | uniq` ; do
-        bdevname=`echo "$bdevs" | grep "/$bdev/\"deviceName\"" | cut -d'|' -f2 | tr -d '"'`
-        bdevid=`echo "$bdevs" | grep "/$bdev/\"volumeId\"" | cut -d'|' -f2 | tr -d '"'`
-        bdevsince=`echo "$bdevs" | grep "/$bdev/\"attachTime\"" | cut -d'|' -f2 | tr -d '"'`
-        ebs+=("$bdevid|$bdevname|$bdevsince")
-      done
-
-      if [ -z "$update_nodes_list" ] ; then
-
-        if [ -n "$cluster" ]; then
-          [ "$cluster" != "$icluster" ] && continue
-        fi
-        [ "_$status" != "_$istatus" ] && [ "_$status" != "_all" ] && continue
-        case $view in
-          list)
-            echo "ID: $id  Name: $iname  Status: $istatus  ext IP: $extIP  intIP: $intIP  Cluster: $icluster  Image: $imageId  Size: $flavorId  AKI: $iaki  ARI: $iari  Security group: $secgroup  Zone: $izone  Keypair: $ikey"
-            echo "${ebs[*]}" | sed 's_^_EBS: _g;s_|_  _g'
-            ;;
-          table)
-            echo "$id|$iname|$istatus|$extIP|$intIP|$icluster|$imageId|$flavorId|$iaki|$iari|$secgroup|$izone|$ikey"
-            echo "${ebs[*]}" | sed 's_^_EBS: _g'
-            ;;
-          column)
-            echo -e "ID: $id\nName: $iname\nStatus: $istatus\next IP: $extIP\nintIP: $intIP\nImage: $imageId\nAKI: $iaki\nARI: $iari\nSize: $flavorId\nSecurity group: $secgroup\nZone: $izone\nKeypair: $ikey\n"
-            echo "${ebs[*]}" | sed 's_^_EBS: _g;s_|_  _g'
-            ;;
-          none)
-            ;;
-          *)
-            echo -e "------------------------------------------------------------------------------\nNode ID: $id    Name: $iname    Cluster: $icluster\nPublic IP: $extIP    Private IP: $intIP\nNode image: $imageId    AKI: $iaki    ARI: $iari\nNode size: $flavorId    Status: $istatus    Keypair: $ikey\nSecurity group: $secgroup    Zone: $izone"
-            echo "${ebs[*]}" | sed 's_^_  EBS: _g;s_|_  _g'
-            ;;
-        esac
-        icount+=1
-
-      else
-        if [ -n "$icluster" ] ; then
-          if [ `grep -c ^${icluster}\| "$M_ROOT/conf/clusters.conf"` -ne 0 ] ; then
-            key=`grep ^${icluster}\| "$M_ROOT/conf/clusters.conf" | cut -d'|' -f2`
-            [ "_$key" != "_$ikey" ] && log "Warning: key name from conf/clusters.conf ($key) for node $IP (name: $iname) doesn't match the one from node metadata ($ikey)" && key="$ikey"
-            sed -i /^$IP\|/d "$M_ROOT/nodes.list"
-            [ "_$istatus" == "_running" ] && echo "$IP|$key|$region|$iname|$icluster|$CLOUD" >> "$M_ROOT/nodes.list"
-
-          fi
-        fi
-      fi
-      
-    done
-  else
-    [ -z "$noupdate" ] && echo "No data to output. Check API request result: $M_TEMP/${rcommand}.resp" || echo "No data. Check if there is any existing data to output: $M_TEMP/${rcommand}.resp and run without --noupdate if necessary."
-    exit 1
-  fi
-  for listip in `cat "$M_ROOT/nodes.list" | grep -v ^# | grep -v ^$ | cut -d'|' -f1` ; do
-    [ `grep -c \|\"$listip\"$ "$M_TEMP/${rcommand}.resp"` -eq 0 -o $(grep -c "^`grep ^${listip}\| "$M_ROOT/nodes.list" | cut -d'|' -f5`|" "$M_ROOT/conf/clusters.conf") -eq 0 ] && sed -i /^${listip}\|/d "$M_ROOT/nodes.list"
-  done
-  IFS=$IFS1
-}
+debug=false
 
 possible_options="cloud help region verbose cluster state status filter short noupdate view update_nodes_list forceupdate all count resolveids id name_source"
 necessary_options=""
@@ -195,15 +50,14 @@ do
 done
 IFS=$IFS1
 
-if [ "_$help" == "_yes" ] ; then
-  echo "Usage: ${0##*/} <options>"
-  echo 
-  echo "Without options all found clusters will be synced"
-  echo
-  echo "Options:"
-  echo
-  echo "  --region=region          - syncs only nodes in this region."
-  exit 0
+found=0
+for option in `echo $necessary_options | sed 's/,//g'`; do
+  [ -z "$(eval echo \$$option)" ] && missing_options="${missing_options}, --${option}" && found=1
+done
+if [[ found -eq 1 ]]; then
+  missing_options=${missing_options#*,}
+  echo "Necessary options: $missing_options not found"
+  exit 1
 fi
 
 [ -n "$cloud" ] && CLOUD=$cloud
@@ -211,22 +65,165 @@ fi
 
 source "$M_ROOT/conf/mon.conf"
 source "$M_ROOT/conf/clouds/${CLOUD}.conf"
-source "$M_ROOT/lib/functions.sh"
 source "$M_ROOT/lib/cloud_functions.sh"
 LOG="$M_ROOT/logs/cloud.log"
 
 M_TEMP="$M_TEMP/cloud/$CLOUD"
-[ -d "$M_TEMP/cloud/$CLOUD" ] || install -d "$M_TEMP"
+[ -d "$M_TEMP" ] || install -d "$M_TEMP"
 
 [ -z "$region" ] && region=$EC2_REGION
-
 [ -z "$status" ] && [ -n "$state" ] && status=$state
 [ -z "$status" ] && status="running"
-
 [ -n "$name_source" ] && NAME_SOURCE=$name_source
 [ -z "$NAME_SOURCE_FALLBACK" ] && NAME_SOURCE_FALLBACK=metadata
 
-localip=`"$M_ROOT"/helpers/localips`
+export IAMACHILD M_TEMP CLOUD
+lock_cloudops || exit 10
+
+CURL="$CURL -s -k"
+declare -i icount
+[ -n "$forceupdate" ] && unset noupdate # for compatibility
+[ -n "$filter" ] && filter="${filter},addresses,cluster"
+
+request() {
+  timestamp=`date +"%Y-%m-%dT%H%%3A%M%%3A%S"`
+  query=`echo -n "AWSAccessKeyId=${AWS_ACCESS_KEY_ID}&Action=DescribeInstances&SignatureMethod=HmacSHA256&SignatureVersion=2&Timestamp=${timestamp}&Version=2013-07-15"`
+  Q=`echo -ne "GET\nec2.amazonaws.com\n/\n$query"`
+  signature=`echo -n "$Q"| $SSLEX dgst -binary -sha256 -hmac "$AWS_SECRET_ACCESS_KEY" | base64 | "$M_ROOT"/lib/urlencode`
+  $CURL "https://ec2.amazonaws.com/?AWSAccessKeyId=${AWS_ACCESS_KEY_ID}&Action=DescribeInstances&SignatureMethod=HmacSHA256&SignatureVersion=2&Timestamp=${timestamp}&Version=2013-07-15&Signature=$signature" | "$M_ROOT"/lib/xml2txt | awk -F'"reservationSet"/' '{print $2}' | grep -v ^$ > "$M_TEMP/${rcommand}.resp"
+}
+
+get_iname() {
+  for ns in $NAME_SOURCE $NAME_SOURCE_FALLBACK ; do
+    case $ns in
+      host)
+        get_hostname $1
+        ;;
+      privateDnsName)
+        sname=`echo "$node" | grep '/"privateDnsName"/0' | cut -d'|' -f2 | tr -d '"'`
+        ;;
+      dnsName)
+        sname=`echo "$node" | grep '/"dnsName"/0' | cut -d'|' -f2 | tr -d '"'`
+        ;;
+      *)
+        # anything else is considered to be a tag as the source (see config)
+        NAMETAG="${ns#*:}"
+        nametagind=`echo "$tags" | grep '/"key"/' | grep \|\"$NAMETAG\" | cut -d'/' -f11`
+        sname=`echo "$tags" | grep "$nametagind/\"value\"/" | cut -d'|' -f2 | head -1 | tr -d '"'`
+        ;;
+    esac
+    [ -n "$sname" ] && break
+  done
+  echo "$sname"
+}
+
+list_nodes() {
+  $debug && [ -n "$update_nodes_list" ] && log "Updating node list"
+  IFS1=$IFS
+  IFS='
+'
+  if [ `cat "$M_TEMP/${rcommand}.resp" 2>/dev/null | wc -l` -gt 0 ]; then
+    [ "_$view" == "_raw" ] && cat "$M_TEMP/${rcommand}.resp" && return
+    declare -a nodelist
+    
+#==============================================================================
+    for sn in `cat "$M_TEMP/${rcommand}.resp" | grep instancesSet | cut -d'/' -f1,2,3,4,5,6,7 | sort | uniq` ; do
+      unset id name istatus extIP intIP IP imageId flavorId icluster
+
+      node=`grep ^$sn\/ "$M_TEMP/${rcommand}.resp"`
+      
+      intIP=`echo "$node" | grep '/"privateIpAddress"/' | cut -d'|' -f2 | tr -d '"'` # may be multiple
+      extIP=`echo "$node" | grep '/"ipAddress"/' | cut -d'|' -f2 | tr -d '"'` # may be multiple
+      
+      id=`echo "$node" | grep '/"instanceId"/0' | cut -d'|' -f2 | tr -d '"'`
+      imageId=`echo "$node" | grep '/"imageId"/0' | cut -d'|' -f2 | tr -d '"'`
+      istatus=`echo "$node" | grep '/"instanceState"/0/"name"/0' | cut -d'|' -f2 | tr -d '"'`
+      flavorId=`echo "$node" | grep '/"instanceType"/0' | cut -d'|' -f2 | tr -d '"'`
+      secgroup=`echo "$node" | grep '/"groupSet"/0/"item"/0/"groupName"' | cut -d'|' -f2 | sort | uniq | tr -d '"' | tr '\n' ','`
+      izone=`echo "$node" | grep '/"placement"/0/"availabilityZone"/0' | cut -d'|' -f2 | tr -d '"'`
+      iaki=`echo "$node" | grep '/"kernelId"/0' | cut -d'|' -f2 | tr -d '"'`
+      #iari=`echo "$sn" | grep '/"ipAddress"/0' | cut -d'|' -f2 | tr -d '"'`
+      if [ "_$NETWORK" == "_external" ] ; then
+        IP=$extIP
+      else
+        IP=$intIP
+      fi
+
+      tags=`echo "$node" | grep '/"tagSet"/'`
+      iname=`get_iname $IP`
+      iclustertag=`echo "$tags" | grep '/"key"/' | grep \|\"$CLUSTER_TAG\" | cut -d'/' -f11`
+      if [ -n "$iclustertag" ]; then
+        icluster=`echo "$tags" | grep "$iclustertag/\"value\"/" | cut -d'|' -f2 | head -1 | tr -d '"'`
+      else
+        [ -z "$all" ] && continue
+      fi
+      
+      ikey=`echo "$node" | grep '/"keyName"/0' | cut -d'|' -f2 | tr -d '"'`
+      
+      bdevs=`echo "$node" | grep '/"blockDeviceMapping"/'`
+      unset ebs
+      for bdev in `echo "$bdevs" | grep '|"attached"' | cut -d'/' -f11 | sort | uniq` ; do
+        bdevname=`echo "$bdevs" | grep "/$bdev/\"deviceName\"" | cut -d'|' -f2 | tr -d '"'`
+        bdevid=`echo "$bdevs" | grep "/$bdev/\"volumeId\"" | cut -d'|' -f2 | tr -d '"'`
+        bdevsince=`echo "$bdevs" | grep "/$bdev/\"attachTime\"" | cut -d'|' -f2 | tr -d '"'`
+        ebs+=("$bdevid|$bdevname|$bdevsince")
+      done
+
+      if [ -z "$update_nodes_list" ] ; then
+
+        if [ -n "$cluster" ] || [ -n "$all" ]; then
+          [ -n "$cluster" ] && [[ "$cluster" != "$icluster" ]] && continue
+
+          [ "_$status" != "_$istatus" ] && [ "_$status" != "_all" ] && continue
+          extIPprint=`echo "$extIP" | sed 's|\n|,|'`
+          intIPprint=`echo "$intIP" | sed 's|\n|,|'`
+          case $view in
+            list)
+              echo "ID: $id  Name: $iname  Status: $istatus  ext IP: $extIPprint  intIP: $intIPprint  Cluster: $icluster  Image: $imageId  Size: $flavorId  AKI: $iaki  ARI: $iari  Security group: $secgroup  Zone: $izone  Keypair: $ikey"
+              echo "${ebs[*]}" | grep -v ^$ | sed 's_^_EBS: _g;s_|_  _g'
+              ;;
+            table)
+              echo "$id|$iname|$istatus|$extIPprint|$intIPprint|$icluster|$imageId|$flavorId|$iaki|$iari|$secgroup|$izone|$ikey"
+              echo "${ebs[*]}" | grep -v ^$ | sed 's_^_EBS: _g'
+              ;;
+            column)
+              echo -e "ID: $id\nName: $iname\nStatus: $istatus\next IP: $extIPprint\nintIP: $intIPprint\nImage: $imageId\nAKI: $iaki\nARI: $iari\nSize: $flavorId\nSecurity group: $secgroup\nZone: $izone\nKeypair: $ikey\n"
+              echo "${ebs[*]}" | grep -v ^$ | sed 's_^_EBS: _g;s_|_  _g'
+              ;;
+            none)
+              ;;
+            *)
+              echo -e "------------------------------------------------------------------------------\nNode ID: $id    Name: $iname    Cluster: $icluster\nPublic IP: $extIPprint    Private IP: $intIPprint\nNode image: $imageId    AKI: $iaki    ARI: $iari\nNode size: $flavorId    Status: $istatus    Keypair: $ikey\nSecurity group: $secgroup    Zone: $izone"
+              [ ${#ebs[*]} -ne 0 ] && echo "${ebs[*]}" | grep -v ^$ | sed 's_^_  EBS: _g;s_|_  _g'
+              ;;
+          esac
+          icount+=1
+        fi
+      else
+        if [ -n "$icluster" ] ; then
+          if [ `grep -c ^$icluster\| "$M_ROOT/conf/clusters.conf"` -ne 0 ] ; then
+            key=`grep ^$icluster\| "$M_ROOT/conf/clusters.conf" | cut -d'|' -f2`
+            [ "_$key" != "_$ikey" ] && log "Warning: key name from conf/clusters.conf ($key) for node $IP (name: $iname) doesn't match the one from node metadata ($ikey)" && key="$ikey"
+            check_super_cluster $ip "$icluster" && continue
+            nodelist+=("$IP|$key|$region|$iname|$icluster|$CLOUD")
+          fi
+        fi
+      fi
+    done
+    if [ -z "$noupdate" ]; then
+      if [ ${#nodelist[*]} -eq 0 ]; then
+        log "ERROR: generated list is empty, not saving it"
+      else
+        log "saving generated list (${#nodelist[*]} nodes)"
+        for ((i=0; i<${#nodelist[*]}; i++)); do echo "${nodelist[$i]}"; done > "$M_ROOT/cloud/nodes.list.${CLOUD}"
+      fi
+    fi
+  else
+    [ -z "$noupdate" ] && echo "No data to output. Check API request result: $M_TEMP/${rcommand}.resp" || echo "No data. Check if there is any existing data to output: $M_TEMP/${rcommand}.resp and run without --noupdate if necessary."
+    proper_exit 1 223
+  fi
+  IFS=$IFS1
+}
 
 if [ -z "$noupdate" ]; then
   changed=0
@@ -238,7 +235,7 @@ if [ -z "$noupdate" ]; then
 else
   # force update if the tmp file is older than FORCE_LIST_UPDATE_AFTER
   # if no setting, force update is disabled
-  if [ -n "$FORCE_LIST_UPDATE_AFTER" ] ; then
+  if [ -n "$FORCE_LIST_UPDATE_AFTER" ]; then
     tmpfileage=$(expr `date +"%s"` - `stat -c "%Z" "$M_TEMP/${rcommand}.resp" || echo 0` || echo 86400)
     [ $tmpfileage -gt $FORCE_LIST_UPDATE_AFTER ] && unset noupdate
   fi
diff --git a/cloud/linode/show_nodes b/cloud/linode/show_nodes
--- a/cloud/linode/show_nodes
+++ b/cloud/linode/show_nodes
@@ -22,10 +22,7 @@ rpath=${0%/*}
 CURL=`which curl 2>/dev/null`
 [ -z "$CURL" ] && echo "Curl not found" && exit 1
 
-#debug=1
-
-[ -n "$debug" ] && debug=true || debug=false
-$debug && LOG="$M_ROOT/logs/show_nodes.log"
+debug=false
 
 possible_options="cluster state filter region short noupdate view update_nodes_list forceupdate all status count resolveids cloud"
 necessary_options=""
@@ -67,7 +64,6 @@ source "$M_ROOT/conf/mon.conf"
 source "$M_ROOT/conf/clouds/${CLOUD}.conf"
 source "$M_ROOT/lib/cloud_functions.sh"
 
-[ -n "$update_nodes_list" -a -n "$filter" ] && echo "Impossible options combination" && exit 1
 M_TEMP="$M_TEMP/cloud/$CLOUD"
 [ -d "$M_TEMP" ] || install -d "$M_TEMP"
 export IAMACHILD M_TEMP CLOUD
@@ -150,13 +146,13 @@ request() {
 }
 
 list_nodes() {
-  $debug && [ -n "$update_nodes_list" ] && echo -e "\n`date`\n=====================\n" >> $LOG
   IFS1=$IFS
   IFS='
 '
   if [ `cat "$M_TEMP/${rcommand}.resp" 2>/dev/null | wc -l` -gt 0 ]; then
     [ "_$view" == "_raw" ] && cat "$M_TEMP/${rcommand}.resp" && return
     declare -a nodelist
+    # full IP data as returned by api_action=linode.ip.list
     allips=`cat "$M_TEMP/ips.list"`
     for sn in `cat "$M_TEMP/${rcommand}.resp" | cut -d'/' -f3 | sort | uniq` ; do
       unset id name istatus extIP intIP IP imageId flavorId region icluster
@@ -192,8 +188,12 @@ list_nodes() {
             ;;
         esac
       done
+      # full IP data correspondent to the ID of the node under serial
+      # number $sn
       IPsn=`echo "$allips" | grep "\"LINODEID\"|$id" | cut -d'/' -f3`
+      # node may have multiple IPs
       for ipsn in $IPsn ; do
+        # full IP data for a single IP number $ipsn of the node number $sn
         ipdata=`echo "$allips" | grep \/$ipsn\/`
         if `echo "$ipdata" | grep -q '"ISPUBLIC"|1'` ; then
           extIP="$extIP`echo "$ipdata" | grep '"IPADDRESS"|' | cut -sd'|' -f2 | tr -d '"'`\n"
@@ -206,6 +206,7 @@ list_nodes() {
       else
         IP="$intIP"
       fi
+      # variable $IP may contain multiple IPs
       IPsanitized=`echo -e "$IP" | grep -v ^$`
       if [ -n "$IPsanitized" ]; then
         for ip in $IPsanitized ; do
@@ -213,18 +214,23 @@ list_nodes() {
           if [ -z "$icluster" ] ; then
             # nodes having no cluster in metadata but added manually to nodes.list
             icluster=`grep ^$ip\| "$M_ROOT/nodes.list" | cut -d'|' -f5`
-            $debug && [ -n "$update_nodes_list" ] && ecf=1 && log "missing cluster for IP ${ip}, assumed `[ -n "$icluster" ] && echo "$icluster" || echo "none"`"
-            break
+            if [ -n "$icluster" ]; then
+              $debug && [ -n "$update_nodes_list" ] && ecf=1 && log "missing cluster for IP ${ip}, assumed $icluster"
+              # this IP is found in nodes.list, end of search
+              break
+            fi
           else
             # no icluster means that node will not be shown, but only if there
             # is no option --all. With this option, however, we want to see all
             # clusters assigned via metadata
-            [ `grep -c ^$icluster\| "$rpath/../../conf/clusters.conf"` -eq 0 ] && [ -z "$all" ] && unset icluster
+            [ `grep -c ^$icluster\| "$M_ROOT/conf/clusters.conf"` -eq 0 ] && [ -z "$all" ] && unset icluster
             $debug && [ -n "$update_nodes_list" ] && unset ecf
+            # in case of multiple IPs the first one is enough
+            break
           fi
         done
       else
-        # if no IP, it shouldn't make way to nodes.list
+        # if no IP, it shouldn't make its way to nodes.list
         [ -n "$update_nodes_list" ] && continue
       fi
       if [ -z "$update_nodes_list" ] ; then
@@ -235,33 +241,25 @@ list_nodes() {
         if [ -n "$icluster" ] || [ -n "$all" ] ; then
           [ -n "$cluster" ] && [[ "$cluster" != "$icluster" ]] && continue
           [ "_$status" != "_$istatus" ] && [ "_$status" != "_all" ] && continue
-          if [ -n "$extIP" ]; then
-            extIP=`echo -e "$extIP" | tr -d ' ' | tr '\n' ' '`
-            extIP="${extIP%% *}"
-            check_super_cluster $extIP "$icluster" && continue
-          fi
-          if [ -n "$intIP" ]; then
-            intIP=`echo -e "$intIP" | tr -d ' ' | tr '\n' ' '`
-            intIP="${intIP%% *}"
-            check_super_cluster $intIP "$icluster" && continue
-          fi
+          extIPprint=`echo "$extIP" | sed 's|\n|,|'`
+          intIPprint=`echo "$intIP" | sed 's|\n|,|'`
           case $view in
             list)
-              echo "ID: $id  Name: $name  Status: $istatus  Region: $region  ext IP: $extIP  intIP: $intIP  Cluster: $icluster  Image: $imageId  Size: $flavorId"
+              echo "ID: $id  Name: $name  Status: $istatus  Region: $region  ext IP: $extIPprint  intIP: $intIPprint  Cluster: $icluster  Image: $imageId  Size: $flavorId"
               ;;
             table)
-              echo "$id|$name|$istatus|$region|$extIP|$intIP|$icluster|$imageId|$flavorId"
+              echo "$id|$name|$istatus|$region|$extIPprint|$intIPprint|$icluster|$imageId|$flavorId"
               ;;
             column)
-              echo -e "ID: $id\nName: $name\nStatus: $istatus\nRegion: $region\next IP: $extIP\nintIP: $intIP\nImage: $imageId\nSize: $flavorId\n"
+              echo -e "ID: $id\nName: $name\nStatus: $istatus\nRegion: $region\next IP: $extIPprint\nintIP: $intIPprint\nImage: $imageId\nSize: $flavorId\n"
               ;;
             none)
               ;;
             *)
               echo "------------------------------------------------------------------------------"
               echo "Node ID: $id    Name: $name    Cluster: $icluster"
-              echo "Public IP: $extIP"
-              echo "Private IP: $intIP"
+              echo "Public IP: $extIPprint"
+              echo "Private IP: $intIPprint"
               echo "Node image: $imageId"
               echo "Node size: $flavorId    Status: $istatus    Region: $region"
               ;;
@@ -270,26 +268,14 @@ list_nodes() {
         fi
       else
         if [ -n "$icluster" ] ; then
-          if [ `grep -c ^$icluster\| "$rpath/../../conf/clusters.conf"` -ne 0 ] ; then
-            
-            key=`grep ^$icluster\| "$rpath/../../conf/clusters.conf" | cut -d'|' -f2`
-            for ip in $IP ; do
-              ip=`echo $ip | tr -d ' '`
-              check_super_cluster $ip "$icluster" && continue
-              nodelist+=("$ip|$key|$region|$name|$icluster|$CLOUD")
-              $debug && [ -n "$ecf" ] && log "$ip ($name) added"
-            done
-          fi
-        elif [ -n "$all" ]; then
-          for ip in $IP ; do
-            ip=`echo $ip | tr -d ' '`
+          if [ `grep -c ^$icluster\| "$M_ROOT/conf/clusters.conf"` -ne 0 ] ; then
+            key=`grep ^$icluster\| "$M_ROOT/conf/clusters.conf" | cut -d'|' -f2`
             check_super_cluster $ip "$icluster" && continue
             nodelist+=("$ip|$key|$region|$name|$icluster|$CLOUD")
             $debug && [ -n "$ecf" ] && log "$ip ($name) added"
-          done
+          fi
         fi
       fi
-      
     done
     if [ -z "$noupdate" ]; then
       if [ ${#nodelist[*]} -eq 0 ]; then
@@ -300,7 +286,7 @@ list_nodes() {
       fi
     fi
   else
-    echo "No local data found. Run without --noupdate"
+    [ -z "$noupdate" ] && echo "No data to output. Check API request result: $M_TEMP/${rcommand}.resp" || echo "No data. Check if there is any existing data to output: $M_TEMP/${rcommand}.resp and run without --noupdate if necessary."
     proper_exit 1 304
   fi
   IFS=$IFS1
