ec2 show_servers fix

diff --git a/cloud/ec2/show_servers b/cloud/ec2/show_servers
--- a/cloud/ec2/show_servers
+++ b/cloud/ec2/show_servers
@@ -33,20 +33,27 @@ IFCFG=`which ifconfig 2>/dev/null`
 HOSTNAME=`which hostname 2>/dev/null`
 
 add_server() {
-  if [ -f "${rpath}/../../keys/${keypair}.pem" ] ; then
-    key=${keypair}.pem
-  elif [ -f "${rpath}/../../keys/${keypair}" ] ; then
-    key=${keypair}
+  if [ "X$NETWORK" == "Xexternal" ] ; then
+    IP=$extIP
   else
-    message=" (key ${rpath}/../../keys/${keypair}\{.pem\} not found)"
+    IP=$intIP
+  fi
+  if [ -n "$IP" ] ; then
+    if [ -f "${rpath}/../../keys/${keypair}.pem" ] ; then
+      key=${keypair}.pem
+    elif [ -f "${rpath}/../../keys/${keypair}" ] ; then
+      key=${keypair}
+    else
+      message=" (key ${rpath}/../../keys/${keypair}{.pem} not found)"
+    fi
   fi
   # altname was supposed to be an alternative source (from instance tags), but
   # it is reconsidered due to no good way to inject the name into the new server
   if [ -n "$altname" ]; then
     sname=$altname
-  else
+  elif [ -n "$IP" ] ; then
     log "Name not found, retrieving one from the host"
-    if [ `echo $localip | grep -c "^$inIP$"` -ne 0 ] ; then
+    if [ `echo $localip | grep -c "^$IP$"` -ne 0 ] ; then
       sname=`$HOSTNAME`
     else
       sname=`$SSH -i "${rpath}/../../keys/${key}" -o StrictHostKeyChecking=no -o ConnectionAttempts=1 -o ConnectTimeout=10 $inIP hostname 2>/dev/null` || sname=`$SSH -i "${rpath}/../../keys/${key}" -o StrictHostKeyChecking=no -o ConnectionAttempts=1 -o ConnectTimeout=10 $extIP hostname 2>/dev/null`
@@ -54,7 +61,9 @@ add_server() {
   fi
   [ "X$sname" == "X" ] && log "Unable to retrieve hostname of the server with IP $inIP|$extIP$message" && unset message
   echo "$inIP|$extIP|$iID|$ami|$state|$keypair|$isize|$secgroup|$started|$zone|$aki|$ari|$sname|$cluster" >> "$M_TEMP/servers.${region}.ips"
-  [ -n "${bID[*]}" ] && for ((i=0; i<${#bID[*]}; i++)) ; do echo "$iID|${bID[$i]}|${bdev[$i]}|${bstarted[$i]}" >> $M_TEMP/servers.${region}.bdevs
+  if [ -n "${bID[*]}" ]; then
+    for ((i=0; i<${#bID[*]}; i++)) ; do echo "$iID|${bID[$i]}|${bdev[$i]}|${bstarted[$i]}" >> $M_TEMP/servers.${region}.bdevs ; done 
+  fi
   unset inIP extIP iID ami state keypair isize secgroup started zone aki ari cluster sname altname bID bdev bstarted
 }
 
@@ -224,15 +233,16 @@ source $M_ROOT/lib/functions.sh
 source $M_ROOT/lib/cloud_functions.sh
 LOG=$M_ROOT/logs/cloud.log
 
-for var in JAVA_HOME EC2_HOME EC2_PRIVATE_KEY EC2_CERT region EC2_TOOLS_BIN_PATH ; do
+for var in JAVA_HOME EC2_HOME EC2_PRIVATE_KEY EC2_CERT EC2_REGION EC2_TOOLS_BIN_PATH ; do
   [ -z "`eval echo \\$\$var`" ] && log "$var is not defined! Define it in conf/cloud.conf please." && exit 1
 done
 PATH="${EC2_TOOLS_BIN_PATH}:${PATH}"
-export JAVA_HOME EC2_HOME EC2_PRIVATE_KEY EC2_CERT region PATH
+export JAVA_HOME EC2_HOME EC2_PRIVATE_KEY EC2_CERT EC2_REGION PATH
 M_TEMP=$M_TEMP/cloud/ec2
 install -d $M_TEMP
 
-[ -n "$region" ] && region=$EC2_REGION
+[ -z "$region" ] && region=$EC2_REGION
+log "region: $region"
 
 [ "X$IFCFG" == "X" ] || localip=`$IFCFG | sed '/inet\ /!d;s/.*r://;s/\ .*//' | grep -v '127.0.0.1'`
 
@@ -242,6 +252,9 @@ changed=0
 [ ! -x ${EC2_TOOLS_BIN_PATH}/ec2-describe-instances ] && log "ec2-describe-instances binary not found! Exiting.." && exit 1
 
 [ -z "$noupdate" ] && ${EC2_TOOLS_BIN_PATH}/ec2-describe-instances -K "$EC2_PRIVATE_KEY" -C "$EC2_CERT" --region $region | sed 's/\t/|/g' > $M_TEMP/servers.${region}.tmp
+
+[ ! -f "$M_TEMP/servers.${region}.tmp" ] && log "file $M_TEMP/servers.${region}.tmp not found" && exit 1
+[ `cat "$M_TEMP/servers.${region}.tmp" | wc -l` -eq 0 ] && log "file $M_TEMP/servers.${region}.tmp is empty" && exit 1
 
 firstline=1
 IFS1=$IFS
