Mongoose config file workaround. EC2 updates (tickets 34, 36, 37)

diff --git a/cloud/ec2/update_hosts_file b/cloud/ec2/update_hosts_file
--- a/cloud/ec2/update_hosts_file
+++ b/cloud/ec2/update_hosts_file
@@ -20,10 +20,11 @@ rpath=${0%/*}
 #*/ (this is needed to fix vi syntax highlighting)
 IFS1=$IFS
 IFS='|'
-cat ${rpath}/../../servers.list | grep -v ^[[:space:]]*$ | grep -v ^[[:space:]]*# | awk '{print $1" "$2}' | while read HOST
+cat ${rpath}/../../servers.list | grep -v ^[[:space:]]*$ | grep -v ^[[:space:]]*# | awk '{print $1" "$4}' | while read HOST
 do
   ip=`echo $HOST | awk '{print $1}'`
   hname=`echo $HOST | awk '{print $2}'`
+  [ -z "$hname" ] && error=1 && continue
   if [ `grep -c "$ip[[:space:]]*$hname" /etc/hosts` -eq 0 ] ; then
     if [ `grep -c "$ip " /etc/hosts` -eq 1 ] ; then
       sed -i -e "/$ip/d" /etc/hosts
@@ -38,4 +39,4 @@ do
   fi
 done
 IFS=$IFS1
-
+[ -n "$error" ] && echo "Error adding to hosts file! Server without name" && exit 1
